### ISSUE TITLE
Pass fail with CTC_MIN_ACCURACY ?

### ISSUE THREAD

**Issue by shimbalama** [nanoporetech/bonito#100]
Hi all,

Just wondering if I can use CTC_MIN_ACCURACY to filter output similar to Guppy? From memory Guppy 'pass' is reads with median Phred score >7. Can I use CTC_MIN_ACCURACY in a similar way? If not what post Bonito QC/filtering do you recommend?

Also does `--recursive` inprove accuracy?

Is there a resource somewhere that details these parameters?

Thanks!

**Comment by iiSeymour** [comment]
Hey @shimbalama 

The `--ctc-min-accuracy` flag is only used when creating training data when combined with `--save-ctc`. It is not used to filter any basecalling results, the latest model in bonito doesn't provide calibrated qscores just yet. 

By default bonito will only basecall all the `.fast5` files in the directory you provide - if you want to basecall all the `fast5` files in all the subdirectories then use `--recursive`.

HTH

Chris.

**Comment by shimbalama** [comment]
Great - thanks for your propt response!
