### ISSUE TITLE
Graphcore M2000?

### ISSUE THREAD

**Issue by RichardCorbett** [nanoporetech/bonito#103]
Hi folks,

Just wondering if anyone has tried bonito on a Graphcore M2000 or if they would expect it to work?    We might be bringing in a system like that and we're hoping to plug our nanopore pipelines in to it.

**Comment by iiSeymour** [comment]
We do have the CTC-CNN model running on the M2000 but not the CRF-RNN model.

**Comment by ridelane** [comment]
@RichardCorbett I learned from a colleague that you had posted this message. Sorry for the slow response. I have emailed you as well. I'd be happy to hop on a call with you. Actually based in Seattle, not far from you. richies@graphcore.ai (425) 922 4041. Looking forward to the dialog.
