### ISSUE TITLE
bonito v0.3.1 crf decoder can not output q score

### ISSUE THREAD

**Issue by waka45** [nanoporetech/bonito#108]
Hi 
I have tried bonito v0.3.1 crf decoder for basecalling, I saw an argument `--fastq` in source coda for fastq and changed the default to **Ture**(`parser.add_argument("--fastq", action="store_true", default=True)`). Then q score in fastq is all  **?** markers, here is my command and if I want to get q score with crf decode, how should I do.

My running command:
```
bonito basecaller dna_r9.4.1 /data/reads > basecalls.fastq  # the output format is acturally fastq
```

output sample:

```
@sample
GGCATCACGTCAGCTCACTCACCCGCGAGCAGTTAAC
+
?????????????????????????????????????
```

Thanks

**Comment by iiSeymour** [comment]
Hey @waka45 

We don't have qscores implemented for the latest models in bonito yet. You can run the models in guppy with [rerio](https://github.com/nanoporetech/rerio) however.

**Comment by waka45** [comment]
thanks @iiSeymour
