### ISSUE TITLE
Bonito base quality scoring broken?

### ISSUE THREAD

**Issue by jonkristoffersen** [nanoporetech/bonito#109]
I used Bonito (from within Guppy 441, GTX 1080 GPU) with the model res_dna_r941_min_crf_v031. The base quality scoring seems broken. With Guppy there is some correlation between percent identity to the reference and the quality score, while with Bonito there is not. 
![Guppy441](https://user-images.githubusercontent.com/46820591/106284808-5818f800-624c-11eb-835d-433421a62eaa.png)
![Bonito441](https://user-images.githubusercontent.com/46820591/106284842-5fd89c80-624c-11eb-8738-f725d58eb5d9.png)

I used this script:
guppy_basecaller --config res_dna_r941_min_crf_v031.cfg --input_path /fast5_test --save_path /fast5_test/Bonito441 --device cuda:0 -r --calib_detect
then Samtools and NanoPlot for the plots.

**Comment by iiSeymour** [comment]
Hey @jonkristoffersen 

I was just reading your blog. Thanks for trying out the initial bonito model support in guppy, the feedback is really useful.

We will need to investigate if the qscores are just poorly calibrated or if something else is going on.

**Comment by femiliani** [comment]
To bring this topic back up. I have just run some basecalling with guppy_hac, bonito, and bonito through guppy/rerio. When looking at the quality through NanoFilt bonito-rerio gave a surprising improvement in quality (below compared to guppy-hac, maybe too good to be true?). 

Unfortunately the consensus sequences I generated with the bonito-rerio reads was a lot worse than the guppy_hac and bonito reads consensus sequences. 


![BonitoLengthvsQualityScatterPlot_kde](https://user-images.githubusercontent.com/58233098/109015893-98209e80-7683-11eb-8263-01305925148d.png)
![GuppyLengthvsQualityScatterPlot_kde](https://user-images.githubusercontent.com/58233098/109015894-98b93500-7683-11eb-996a-586a92e3eca2.png)

**Comment by iiSeymour** [comment]
All the new CRF models in v0.5 have been calibrated and should be inline with guppy.
