### ISSUE TITLE
having problems with bonito installation

### ISSUE THREAD

**Issue by drdna** [nanoporetech/bonito#11]
Bonito repeatedly fails at parasail1.1.19 installation. Tried installing 1.1.17 first but no success.

make of autoconf failed

**Comment by iiSeymour** [comment]
Parasail 1.1.19 required you to compile and build the Python package on your local machine but we have worked to get precompiled wheels available - https://github.com/jeffdaily/parasail-python/issues/11

Bonito now depends on parasail 1.2 which should solve your problem. 

If you are installing Bonito from pip then grab the latest version -

```
(venv3) $ pip install ont-bonito==0.0.7
```

Or if you are using the repo then update master and reinstall the latest dependencies -

```
(venv3) $ git pull
(venv3) $ pip install --upgrade pip
(venv3) $ pip install -r requirements.txt
(venv3) $ python setup.py develop
```
