### ISSUE TITLE
Basecall models - modbases and research models

### ISSUE THREAD

**Issue by gringer** [nanoporetech/bonito#117]
Question from ONT community by Gabriel Wagner (Med Uni Graz):

> I was just wondering, if someone evaluated the new Bonito CRF research models compared to HAC basecalling in case of bacterial isolates. How much better does it get and does it depend on the bacterial species?

> Furthermore, could it make sense to use a modbases model, would such a model increase accuracy, because modifications are detected that would otherwise result in a basecalling error?
I am asking because I read a paper where the compared HAC to HAC+mod and it made a difference (although it seems that it depends on the bacteria which one is better).

**Comment by Kamouyiaraki** [comment]
Hey, I'm just leaving this comment here because I have the same question and maybe this will help it gain some attention?  I'm not working on bacterial isolates so I'm even more unsure about performance for non-model species.
