### ISSUE TITLE
Does bonito require an existing pre-trained model for the workflow? 

### ISSUE THREAD

**Issue by computingforhelp** [nanoporetech/bonito#12]
You mentioned in https://github.com/nanoporetech/bonito/issues/8 that you used the prepare_mapped_reads.py script in Taiyaki to generate the training set. However, the script require a pre-trained basecaller model.

Does that mean running bonito will also require me to fetch an existing basecalling pre-trained model, for example, to generate the training set? Sorry, I'm new to this area and trying to learn how to start my own training with my own data.

**Comment by iiSeymour** [comment]
That is correct, an existing pre-trained model is required to create a custom training set and typically our production basecaller `guppy` would be used for this.
