### ISSUE TITLE
bonito --device and nvidia-smi device number not matching

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/bonito#120]
Dear,

i found that bonito and nvidia-smi do not match the device number. I started to google around and i found this page:
[https://stackoverflow.com/questions/52815708/order-of-cuda-devices](url)

do you think that you can implement in order to have a better link between bonito and nvidia-smi?

cheers
Luigi

**Comment by iiSeymour** [comment]
Hey @lfaino 

This isn't really a bonito decision. `nvidia-smi` uses the PCI-e bus enumeration order where as PyTorch uses GPU device type order. This can be a pain on heterogeneous systems but the recommended solution is to set the following environment variable:    

```bash
export CUDA_DEVICE_ORDER=PCI_BUS_ID
```

**Comment by lfaino** [comment]
ok thanks
