### ISSUE TITLE
Recursive FAST5 file search

### ISSUE THREAD

**Issue by philres** [nanoporetech/bonito#121]
Hey,

small feature request. Not important at all but nice to have. 

An `--recursive` option that makes it search FAST5 files recursively in the input folder.

Cheers,
Philipp

**Comment by iiSeymour** [comment]
Hey @philres 

The basecaller supports recursive search with `--recursive` - see [here](https://github.com/nanoporetech/bonito/blob/master/bonito/cli/basecaller.py#L91).

Is that what you are after?

**Comment by philres** [comment]
Well that's embarrassing. Don't know how I missed that. Was probably too late yesterday evening. 

Yes that's what I was asking for.

Thanks!
