### ISSUE TITLE
bonito basecaller to have a resume mode

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/bonito#122]
Hi 

It would be great if the bonito basecaller had a --resume mode in case something crashes or more reads are generated to avoid having to basecall everything from scratch or manually figure out which files have been basecalled.

Best regards
Rasmus

**Comment by iiSeymour** [comment]
Hey @Kirk3gaard 

You can use `--skip --read-ids` with the output redirection append operator `>>` to achieve this.

```
$ grep -Po '^>\K.*' calls.fasta > read-ids.txt
$ bonito basecaller dna_r9.4.1 --skip --read-ids read-ids.txt reads >> calls.fasta
```

_Note: if providing a reference and outputting sam you'll want to use a new output file as appending will produce an invalid file._

**Comment by Kirk3gaard** [comment]
Hi Chris

Thanks. That is a nice workaround.

Best Rasmus

**Comment by davidnewman02** [comment]
Closing as issue is resolved by the workaround provided.
