### ISSUE TITLE
Low qscore when bascalling by bonito 

### ISSUE THREAD

**Issue by libenping** [nanoporetech/bonito#133]
Hi,thank you for the new basecalling software bonito!
       However,when I use the bonito basecalling the human data, I found that the qscore reduced significantly.
      Here is my code and result:
       1 Using the bonito :(CUDA Version: 10.2,GPU)
          code:
`bonito basecaller /home/prom/software/bonito/bonito_20210315/bonito/bonito/models/dna_r10.3 ./R10.3_2020_human/ >basecalls.fasta`
         result:
          The sequence length is as good as  the length basecalling by guppy,however the qscores are all 0;
      2 Using guppy+rerio:(CentOS Linux release 7.9.2009,CPU)
        code:
        `guppy_basecaller -i ./R10.3_fast5 -s ./basecalled_R10.3_fast5  --cpu_threads_per_caller 8 --num_callers 6 \
    -d /ALNAS01/software/PUBLIC/guppy/20201231/rerio/rerio/basecall_models \
    -c res_dna_r103_prom_rle_v001.cfg`
         result:
               Mean read quality: 12.1(guppy)/5.5(bonito);
Recently，I use the guppy V4.4.2 and res_dna_r103_prom_modbases_5mC_v001.cfg basecalling the same dada,the qscore is higher than before, however also lower than guppy.
So can you give me some suggestion to improve my result? Thank you !

**Comment by iiSeymour** [comment]
Hello @libenping 

Yes, the mean qscore values in the summary file for Bonito are placeholders as this is not implemented. Bonito style CRF models will be the default models in the Guppy 5.0 release and will include calibrated per base and mean qscores.

**Comment by davidnewman02** [comment]
Closing as issue has been resolved.
