### ISSUE TITLE
Converting custom Bonito model to Guppy model

### ISSUE THREAD

**Issue by menickname** [nanoporetech/bonito#135]
Dear @iiSeymour 

Is there an (easy) way to convert custom-trained Bonito models to Guppy models? I found current Bonito model config files via the rerio github ([https://github.com/nanoporetech/rerio]). I assume the best **general** model that's currently available is the _res_dna_r941_min_crf_v032.cfg_? Hence, I would like to generate a similar .cfg file which is compatible with Guppy basecaller.

Thank you in advance.

**Comment by iiSeymour** [comment]
Hey @menickname 

I just pushed https://github.com/nanoporetech/bonito/commit/651b9c14bbac7fb8a1b01db1610dde97eb4d2d76 which adds the ability to convert the PyTorch weights to the guppy compatible format - 

```
$ bonito export model-dir/weights_1.tar > model-dir/weights_1.jsn
```

_Note: If the model was trained for more than one epoch don't forget to take the highest set of wieghts._
