### ISSUE TITLE
Does kit matter for model?

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/bonito#136]
G'day,

quick question.

Does the kit used, (LSK-109 vs LSK-110) matter when selecting a bonito model?

In this light, a compatibility table of kit/pore model -> basecall model for both bonito and Guppy would be awesome.
Some combo's are missing in guppy for example, like SLK110 and PRO002, and it's confusing people.

Cheers,
James

**Comment by iiSeymour** [comment]
Hey @Psy-Fer 

You can the guppy compatibility table with `guppy_basecaller --print_workflow`.

Bonito tries to keep it simple here and the only factor is pore, so either `r9.4.1` or `r10.3` regardless of the device type.

Does that clear it up?

**Comment by Psy-Fer** [comment]
Thanks Chris,

Yea that helps. I know guppy isn't your wheel. House, but should we just use the R9.4.1 hac prom model with the PRO002 flowcell and lsk-110 kit? 
Trying to clear that one up specifically.

Cheers

**Comment by stureid** [comment]
> should we just use the R9.4.1 hac prom model with the PRO002 flowcell and lsk-110 kit?

Yes. There are a few other "kit10s" already in the config. We'll get that fixed up.

**Comment by Psy-Fer** [comment]
i see this is fixed now. Cheers
