### ISSUE TITLE
Guppy Model from Bonito export Error (or howto question).

### ISSUE THREAD

**Issue by rfinkers** [nanoporetech/bonito#138]
Using bonito export, I have exported a model to the guppy compatible format. In addition to the .jsn (from the export), I added a config file (comparable to the .cfg files found in the rerio archive; crf v32 model; only changing the name of the cfg and modified the name of the.jsn) 

Upon running (Guppy v4.5.2) the following error (partially printed) is shown on screen.

Am I correct in my assumption that I need to define a .cfg file comparable to which is in the rerio archive and 2) how to move forward with the error below?

`Error parsing config file: 'the options configuration file contains an invalid line '{"type": "serial", "sublayers": [{"type": "convolution", "insize": 1, "size": 4, "bias": true, "winlen": 5, "stride": 1, "padding": [2, 2], "activation"
: "swish", "params": {"W": [[[-0.025925470516085625, -0.23480789363384247, -0.353717565536499, -0.07104074954986572, 0.036408353596925735]], [[-0.035260483622550964, 0.3765697181224823, -0.39679813385009766, -0.061161577701568604, 0.0860
2681010961533]], [[0.06162600964307785, -0.11495587974786758, -0.48795416951179504, 0.4073488414287567, -0.021766895428299904]], [[-0.040096353739500046, -0.0077209691517055035, 0.24949483573436737, 0.3015221655368805, 0.1478450894355774
]]], "b": [0.06845813989639282, 0.1794242113828659, 0.1347373127937317, -0.06062815338373184]}}, {"type": "convolution", "insize": 4, "size": 16, "bias": true, "winlen": 5, "stride": 1, "padding": [2, 2], "activation": "swish", "params":
 {"W": [[[-0.162832617759 ... etc`

**Comment by iiSeymour** [comment]
Hey @rfinkers 

I can't reproduce this - can you share the PyTorch weights _(.tar)_ and the converted weights _(.jsn)_ [here](https://nanoporetech.ent.box.com/f/7c4375e2b71b48258ebed29f198b89ab)?

**Comment by rfinkers** [comment]
> Hey @rfinkers
> 
> I can't reproduce this - can you share the PyTorch weights _(.tar)_ and the converted weights _(.jsn)_ [here](https://nanoporetech.ent.box.com/f/7c4375e2b71b48258ebed29f198b89ab)?

Did you receive the files in good order?

**Comment by iiSeymour** [comment]
Yes, I received the model and I see you send a 768 wide model.

```
 md5sum=7c809d87d973d8dd23c6ff0d5618afde type=serial 
  activation=swish stride=1 bias=True type=convolution size=4 padding=[2, 2] winlen=5 insize=1 
  activation=swish stride=1 bias=True type=convolution size=16 padding=[2, 2] winlen=5 insize=4 
  activation=swish stride=5 bias=True type=convolution size=768 padding=[9, 9] winlen=19 insize=16 
  type=reverse 
   activation=tanh bias=True type=LSTM gate=sigmoid size=768 insize=768 
  activation=tanh bias=True type=LSTM gate=sigmoid size=768 insize=768 
  type=reverse 
   activation=tanh bias=True type=LSTM gate=sigmoid size=768 insize=768 
  activation=tanh bias=True type=LSTM gate=sigmoid size=768 insize=768 
  type=reverse 
   activation=tanh bias=True type=LSTM gate=sigmoid size=768 insize=768 
  activation=tanh bias=True type=GlobalNormTransducer size=5120 scale=5.0 insize=768 
```

However I still can't reproduce as guppy 4.5.2 runs your model in my hands

```
$ guppy_basecaller -d /opt/ont/guppy/data/ -c res_dna_r941_min_crf_v032.cfg -x cuda:0 -i test -s /tmp/test -m weights_16.jsn 
ONT Guppy basecalling software version 4.5.2+bcc53d3
config file:        res_dna_r941_min_crf_v032.cfg
model file:         weights_16.jsn
input path:         test
save path:          /tmp/test
chunk size:         720
chunks per runner:  320
minimum qscore:     7
records per file:   4000
num basecallers:    4
gpu device:         cuda:0
kernel path:        
runners per device: 4

Found 15 fast5 files to process.
Init time: 5575 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Caller time: 44061 ms, Samples called: 118937308, samples/s: 2.69938e+06
```

**Comment by rfinkers** [comment]
Can confirm that it is Ok now. I used a different approach to load the model in guppy. tnx.
