### ISSUE TITLE
reproducing Medaka results

### ISSUE THREAD

**Issue by kishwarshafin** [nanoporetech/bonito#14]
Hey @iiSeymour ,

I'm trying to reproduce the results you reported here: https://github.com/nanoporetech/bonito#medaka

I want to make sure I do things right. You followed that same Medaka procedure of Racon-Medaka and not Medaka alone, is that correct? Also, which assessment tool did you use? Pomoxis?

**Comment by iiSeymour** [comment]
Hey @kishwarshafin 

[Katuali](https://github.com/nanoporetech/katuali) was used, it has model training and evaluation.

HTH,

Chris.

**Comment by kishwarshafin** [comment]
so the Q values came from Katuali? And did you train and tested on Racon polished assemblies?

**Comment by iiSeymour** [comment]
Yes, the Q values are from Katuali and standard config was used *(canu + racon)*.
