### ISSUE TITLE
Bonito v0.3.2 medaka model

### ISSUE THREAD

**Issue by Sumsarium** [nanoporetech/bonito#145]
Hi @iiSeymour. I am using the recent Bonito v0.3.2 model (it ultimately improves the outcome of my UMI binning endeavors). Is the medaka v0.3.1 model (bonito_medaka_0.3.1.hdf5) linked from this repo compatible or do you have a bonito_medaka_0.3.2.hdf5? Best regards, Rasmus

**Comment by iiSeymour** [comment]
Hi @Sumsarium, the linked model is compatible.

**Comment by JWDebler** [comment]
Just picking this back up with 0.38, is this medaka model still valid, since the link has disappeared from the readme.

**Comment by Sumsarium** [comment]
@JWDebler If you are just looking for the model file: https://github.com/nanoporetech/bonito/tree/v0.3.6

**Comment by JWDebler** [comment]
@Sumsarium thanks, I found that one already. Is it still applicable to calls made by the latest bonito 0.38 models?
