### ISSUE TITLE
During training, CTC-CRF model only calls ~ground_truth[:-state_len]

### ISSUE THREAD

**Issue by TimD1** [nanoporetech/bonito#148]
Hi @iiSeymour,

I've been working on a basecaller project that borrows bonito's architecture, and recently found the time to upgrade from the old CNN+CTC model to the new CTC-CRF model. I've noticed that now during training the CTC-CRF model ignores the last state_len bases, and just doesn't call them. Here are a few examples of what I'm seeing (this happens for every training example):

```
Truth: GTCTGGGCGGTCCCTTCCCGTGTCCGGCCCTGGAGTGGGTG
Call:  GTCTGGGCGGTCCCTTCCCGTGCCCGGCCCTGGAGT

Truth: AGCTCTGGTGAGGAGGCCTGTGAGAGGCCGGTTTCTCCCAG
Call:  AGCTC AGTGAGGAGGCCTGTGAGAGGCCGGTTTCT

Truth: TCTTATTTCATTTGGCTGTGTCGAGTG TTTTTAAAATATCA
Call:  TCTTATTTCATTTGGCTGTATCGAGTGGGTTTCAACA
```

I just reproduced the same issue with Bonito v3.8, by printing `refs` and `seqs` [here](https://github.com/nanoporetech/bonito/blob/44e5db76de13d3b1c4110718c773ee27b5179aa2/bonito/training.py#L214). It's possible that the backpropagation and training is still happening correctly, but seqdist path-finding or decoding just isn't printing the full sequence. Wouldn't this impact the basecalling results as well?

**Comment by TimD1** [comment]
I think with sufficient overlap on the stitching during basecalling, you won't see this artifact in the final basecalled result (except for the last chunk, where each read will be missing 5 bases on the end).

**Comment by iiSeymour** [comment]
Hey @TimD1 - yes, we decode the dropped base for the called sequence _(not the state)_ so this is expected and as you have discovered the overlap should account for this when stitching.

**Comment by TimD1** [comment]
Ah, I didn't notice until now that Bonito now uses different decoding methods for training vs. basecalling. Closing, since this behavior is expected.

Thanks for the clarification!
