### ISSUE TITLE
Error during pip install -  scipy 1.6.2 not found

### ISSUE THREAD

**Issue by ilnamkang** [nanoporetech/bonito#149]
Hi,

I'm experiencing an error during pip installation of bonito.

The error message is below.

\----
Collecting scipy==1.6.2 (from ont-bonito)
  Could not find a version that satisfies the requirement scipy==1.6.2 (from ont-bonito) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
No matching distribution found for scipy==1.6.2 (from ont-bonito)
\----

How can I solve this problem?

FYI, I'm using Python 3.6.9 on Ubuntu 18.04.

Thanks.

Ilnam

**Comment by iiSeymour** [comment]
Hi @ilnamkang 

I did not realize scipy had dropped Python 3.6 support in 1.6+ and have just downgraded to 1.5.4.

**Comment by ilnamkang** [comment]
Thanks for a quick response.

But, I'm still getting the same error with pip installation.

**Comment by iiSeymour** [comment]
I will need to upload a new version _(v0.3.9)_ to PyPI for `pip install ont-bonito` to work on Python 3.6 again. I have a few other minor fixes going in first so this should be available in a few days.

**Comment by iiSeymour** [comment]
Resolved with the release of v0.4.
