### ISSUE TITLE
rebasecalling best practice

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/bonito#15]
Hi, 

More of a general question than an issue here. 

While rebasecalling PromethION runs, should reads from failed_fast5's also be rebasecalled or should one only take the pass_fast5 files? 
As fail or pass criteria is most likely based on the outcome of current basecalle guppy, i would think fail_fast5 reads should also be recalled. 
Although it will be difficult in the output to distinguish bad quality reads from high quality reads in fail_fast5 basecalled reads as bonito does not report quality scores yet. 

Do you think a general filter for read-length (>4000 bp) would make sense?

Thanks, 
Michel

**Comment by iiSeymour** [comment]
Hey @MichelMoser 

Sure, it’s worth rebasecalling all the data. If you have a good reference I would suggest mapping with `minimap2` and then using `stats_from_bam` from `pomoxis` which will give you csv output that can be used for filtering.

HTH

Chris.

**Comment by MichelMoser** [comment]
Great, will do that. Thanks
