### ISSUE TITLE
Bonito Export does not run

### ISSUE THREAD

**Issue by menickname** [nanoporetech/bonito#150]
Dear @iiSeymour 

I have tested the Bonito export command today on one of my pre-trained datasets. This training was done using an older version of the Bonito software. However, I got following error messages:

`File "/home/ymir/1_software/bonito-0.3.8/bonito-0.3.8/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/home/ymir/1_software/bonito-0.3.8/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/ymir/1_software/bonito-0.3.8/bonito/cli/export.py", line 78, in main
    model = bonito.util.load_model(args.model, device='cpu')
  File "/home/ymir/1_software/bonito-0.3.8/bonito/util.py", line 290, in load_model
    raise FileNotFoundError("no model weights found in '%s'" % dirname)
FileNotFoundError: no model weights found in 'Bonito_model_Nick_epochs75_barcodes_solved/weights_75.tar'`

Any idea what could have gone wrong here?
Thank you in advance!

**Comment by iiSeymour** [comment]
Hey @menickname 

The export command needs to read the `config.toml` and the `weights_i.tar` so it expects the model directory to passed.

```
$ bonito export /data/models/my-model > /data/models/my-model/weights.jsn
``` 

I've just pushed a commit that checks the export argument is a directory.

**Comment by menickname** [comment]
Dear @iiSeymour 

Makes sense indeed. Now it proceeds, however I do get following error. I did get the same error when running the Bonito basecaller command:

`Traceback (most recent call last):
  File "/home/ymir/1_software/bonito-0.3.8/bonito-0.3.8/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito', 'console_scripts', 'bonito')()
  File "/home/ymir/1_software/bonito-0.3.8/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/ymir/1_software/bonito-0.3.8/bonito/cli/export.py", line 83, in main
    model = bonito.util.load_model(args.model, device='cpu')
  File "/home/ymir/1_software/bonito-0.3.8/bonito/util.py", line 297, in load_model
    Model = load_symbol(config, "Model")
  File "/home/ymir/1_software/bonito-0.3.8/bonito/util.py", line 264, in load_symbol
    imported = import_module(config['model']['package'])
TypeError: string indices must be integers`

Thank you in advance.
Best regards

**Comment by iiSeymour** [comment]
Is this a CRF model from Bonito v0.3.X - export won't work for earlier ctc-cnn models _(as guppy can't run them)._

**Comment by menickname** [comment]
This also implies pre-trained models on older Bonito versions (<v0.3.X) are not supported on newer Bonito versions?

**Comment by iiSeymour** [comment]
No, bonito has kept backwards compatibility for older models but you will need to add a `[model]` section to the config - see [here](https://github.com/nanoporetech/bonito/blob/master/bonito/models/configs/dna_r9.4.1%40v2.toml#L4).

The newer CRF models have many advantages so it's worth considering upgrading.
