### ISSUE TITLE
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/bonito#153]
The torch==1.8.0 requirement in bonito is breaking for 3090 cards. I get the error as listed in the subject line when I try to run the bonito basecaller.

By making a vanilla environment with conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch, I can verify that the environment works with python -c "import torch;print(torch.max(torch.rand((30,30),device='cuda')))". It breaks the moment I run pip install ont-bonito. It forces in 1.8.0 and breaks the environment.

To fix, I ran pip uninstall ont-bonito and pip uninstall torch. Then I ran conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch --force to restore conda's environment. I verified that CUDA works with the python command above. Downloading the github package for bonito, I modified the torch requirement to >=1.7.0, then ran pip install . inside the bonito folder. Verifying that the CUDA environment is still working, I was now able to successfully basecall. 

I suggest revising the requirements so that it doesn't break for those cards.

**Comment by Sumsarium** [comment]
I am struggling quite a bit with getting it to work on my RTX 3090.....should i downgrade to cuda 11.1 (currently running 11.2) since the latest version of genomeworks-cuda is 11.1 (i.e. genomeworks-cuda-11-1)? For the sake of consistency, does anyone have a bonito dockerfile? Hope to get duplex up and running soon...

**Comment by mawa86** [comment]
hi @billytcl 

I have the same CUDA version (11.0) but a 2080 card, trying to fix the same problem.
so to follow what you have done, but bear with me, I am a total novice to the command line and linux (ubuntu 18.04), so I have three - highlighted down- noob questions for you if you could be so nice to help me:

So in my conda environment i ran:

```
pip uninstall ont-bonito 
pip uninstall torch
pip uninstall cupy-cuda102
```
(The latter was a remnant pulled by `pip install ont-bonito`)

Then I ran 
`conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch --force `

Which installed pytorch-1,7.1, but upon running pip freeze i now have these weird lines among all the installations:

> numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1620831194891/work
> olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
> Pillow @ file:///tmp/build/80754af9/pillow_1617386154241/work
> six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
> typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1622748266870/work

### **Does anyone know why is that?**
I then tried to verify whether CUDA works with the python command
 
`python -c "import torch;print(torch.max(torch.rand((30,30),device='cuda')))"`

which returned 

> tensor(0.9997, device='cuda:0')

### **not sure whether this is what to expect?**

About the next step you mention

> _Downloading the github package for bonito, I modified the torch requirement to >=1.7.0_, then ran pip install . inside the bonito folder. Verifying that the CUDA environment is still working,[...]

### How did you do that? using git clone?

Thanks very much for any help!

**Comment by iiSeymour** [comment]
https://github.com/nanoporetech/bonito/commit/98acb6f91ac2d4f452d18f7d5f421bc3b617ce87 adds basic support for CUDA 11.1 builds suitable for ampere GPUs.

```
pip install -f https://download.pytorch.org/whl/torch_stable.html ont-bonito-cuda111
```
