### ISSUE TITLE
Duplicate read identifiers

### ISSUE THREAD

**Issue by Tipplynne** [nanoporetech/bonito#155]
Good Day bonito devs

We have been using Bonito to recall some sequencing data for termite genome assembly, with some improvements over guppy called reads which has made bonito reads useful for correcting and rescaffolding our assemblies. However when trying to assemble with the bonito reads we have problems with finding reads with duplicate sequence Ids, i.e. flye assembler fails, unless the reads have been deduplicated with seqkit rmdup using either default parameter or -n (full seq name) as a filter. However, this % of reads is very small and is variable between samples, and some samples do not have these duplicated ID's at all. Can you explain why that is happening and if it is cause for concern about the way I am recalling the reads?

I sequentially split my .fast5 data up into 10-20 batches (60-80gb per batch of raw data) per sample, and then simply cat the resulting 10-20 .fasta files in to one to get final set of reads. is this approach potentially creating duplicates?

Thanks for any feedback
Crystal

**Comment by iiSeymour** [comment]
Hi @Tipplynne 

I think you must be feeding duplicate reads into bonito as it's not possible for bonito to produce more than one record per read.
