### ISSUE TITLE
Reference free duplex reads?

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/bonito#156]
Hi 

Is it possible to run the duplex command denovo when sequencing stuff without a reference? https://github.com/nanoporetech/bonito/releases/tag/v0.4.0

Best regards
Rasmus

**Comment by iiSeymour** [comment]
Hey @Kirk3gaard 

The `--pairs` interface to `duplex` is open so you can pair up read ids in any way you'd like.

A few methods I have thought about but are not implemented here in bonito (yet?) are:   
 1. providing just a sequencing summary _(no alignment)_ and pairing on channel/mux, time and rough duration.
 2. as per 1. but build the pairs from the metadata in the fast5 files as a first step _(no summary files)_.
 3. taking a PAF file and building pairs from that.

**Comment by Kirk3gaard** [comment]
Hi @iiSeymour 

Okay yeah I assume that checking each read against the read before and after it should be feasible.  Can you provide and example of the pairs file so I know what it should look like?

Best regards
Rasmus

**Comment by iiSeymour** [comment]
Sure, just a space-separated pair of read-ids per line -

```
$ head pairs.csv
0f6b2c5c-9bce-4adf-899c-efa8560791a7 87e21c53-938d-41b3-8c8b-11827c692cfb
31541851-d7e7-4815-bb4d-d5ab3954b1a9 bef76852-c48c-4142-bb68-1f74aeeb152b
0a72fd68-2618-480a-9153-1b563b1d7158 da8ad8ca-50f9-447a-950a-90d5089ccf7f
787c66f6-0fce-48b3-8b76-0d5aa4fa0e8a 3f176dcb-479f-4117-b557-1791cee39dbf
c13a36c9-5e5e-4eef-97ab-af389941d0d6 f9363846-e266-4fc0-beaf-c40ca57591a9
952904e6-91f4-4749-bd34-9a5f94d3040f f801f464-ac76-4b94-87ba-c1d672b6bf55
62d7f17b-b6db-417b-a18d-9e2a15883c38 acec478f-7200-4163-939e-55e7e597d798
813098a5-5ece-422b-a81d-13d1e6fb51c6 4eb9a324-4c30-40e7-903b-61cb9ecea5ac
60a4869c-861a-412b-ba0b-1f8853acbb8b b69b92c7-decd-4542-8015-a2c1fcc1bc2b
c5f048a1-ed10-4163-822b-c645ab26b7a4 4bd6a966-1a96-48af-84cb-757bc53561dc
```

**Comment by Kirk3gaard** [comment]
Perfect thanks a lot.

**Comment by Kirk3gaard** [comment]
If anyone is going to need this here is some R code to extract candidate duplex pairs denovo from the summary file produced by bonito. It basically groups all reads by channel and compares the length of each read to the previous one going through the pore and and only keeps read pairs that are of similar relative length (>0.95) and I added a filter for absolute read lengths (>1000) . Motivation for this filtering (https://twitter.com/kirk3gaard/status/1397898567898079232),  bonito compares the pairs and will deal with the poor pairs (https://twitter.com/iiSeymour/status/1398222097701298184).

SUMMARYFILE=bonito_summary.tsv

R --slave --silent --args "$SUMMARYFILE" << 'generateCANDIDATEduplexPAIRS'
  # Extract passed args from shell script
	args <- commandArgs(trailingOnly = TRUE)

library(tidyverse)
# Load summary file
simplex<-read_tsv(file = args[[1]])
# Process summary file
time_simplex<-simplex  %>% 
  group_by(channel,mux) %>% 
  mutate(end_time=start_time+duration) %>% 
  arrange(start_time) %>% 
  mutate(previous_start=lag(start_time),
         previous_end_time=lag(end_time),
         prev_read_id=lag(read_id),
         prev_read_length=lag(sequence_length_template)) %>% 
  ungroup() %>%
  drop_na() %>%
  select(prev_read_id,read_id,sequence_length_template,prev_read_length,previous_start,previous_end_time,start_time) %>%
  mutate(time_dif=start_time-previous_end_time,
         rel_seq_len=ifelse(test= (prev_read_length>sequence_length_template),yes =sequence_length_template/prev_read_length,no = prev_read_length/sequence_length_template ))
# Filter read pairs by relative length (will not work for filtering amplicons as they will have the same size regardless of whether they are a true duplex pair)
rel_len_cutoff<-0.95
abs_len_cutoff<-1000
time_simplex %>% filter(rel_seq_len>rel_len_cutoff & sequence_length_template>abs_len_cutoff) %>% select(prev_read_id,read_id) %>% write_delim(file = "candidate_duplex_pairs.txt",delim = " ",col_names = F)

generateCANDIDATEduplexPAIRS
