### ISSUE TITLE
OSError: Unable to open file (truncated file: eof = 211189760, sblock->base_addr = 0, stored_eof = 228307433)

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [nanoporetech/bonito#157]
Hello,
I just wanted to report an issue I had, though I debugged it and I can run bonito now.
What happened was that I had a file whose integrity was compromised in the batch of ~700 files I ran. 
As a results the basecalling was interupted midway and I lost some computing time.
I ran that snipset to detect the incriminated file : 

```
import h5py
fail=[]
for file in glob.glob(*.fast5"):
    try : 
        test = [el for el in h5py.File(file,"r")]
    except OSError:
        fail.append(file)
```

Best,
Seb

**Comment by iiSeymour** [comment]
Thanks for the report Seb.

**Comment by TrentPrall** [comment]
@Sebastien-Raguideau I have been running into this issue pretty regularly. Did you have a way to recover the compromised fast5 file or did you exclude it from basecalling?

**Comment by Sebastien-Raguideau** [comment]
@TrentPrall I did just exclude these files. Depending on how h5py works, it may or may not be possible to save part of files: if you can iterate over entries along the file until the faulty/incomplete one, then you should also be able to write back these non corrupted entries. If h5py loads the whole file at once then, it will directly throw an error and you won't be able to do anything.
