### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by s4251484** [nanoporetech/bonito#158]
Hi there i got the following errors after i ran `bonito download --models` and `bonito download --models --latest`
@iiSeymour 

```
(/scratch/qaafi/uqcong/conda-bonito) [uqcong7@wiener bonito]$ bonito download --models
/scratch/qaafi/uqcong/conda-bonito/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554790289/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
[downloading models]
  5%|##9                                                      | 1.31M/25.0M [00:29<11:23, 34.7kiB/s]
 84%|###############################################6         | 20.9M/25.0M [10:24<02:10, 31.7kiB/s]
[downloaded dna_r9.4.1@v1.zip]                                                                      
[downloaded dna_r9.4.1@v2.zip]                                                                      
[downloaded dna_r9.4.1@v3.zip] 

Traceback (most recent call last):
  File "/scratch/qaafi/uqcong/conda-bonito/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/scratch/qaafi/uqcong/bonito/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/scratch/qaafi/uqcong/bonito/bonito/cli/download.py", line 109, in main
    File(__models__, model, args.force).download()
  File "/scratch/qaafi/uqcong/bonito/bonito/cli/download.py", line 65, in download
    with ZipFile(self.location(fname), 'r') as zfile:
  File "/scratch/qaafi/uqcong/conda-bonito/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/scratch/qaafi/uqcong/conda-bonito/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

(/scratch/qaafi/uqcong/conda-bonito) [uqcong7@wiener bonito]$ bonito download --models --latest
/scratch/qaafi/uqcong/conda-bonito/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554790289/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
[downloading models]
  1%|3                                                       | 288k/50.1M [00:27<1:46:51, 7.76kiB/s]
 13%|#######2                                               | 6.59M/50.1M [09:57<1:43:47, 6.98kiB/s]
 44%|#########################2                               | 22.2M/50.1M [32:59<48:07, 9.65kiB/s]
 53%|##############################2                          | 26.6M/50.1M [40:09<31:23, 12.5kiB/s]
 64%|####################################6                    | 32.2M/50.1M [49:13<26:34, 11.2kiB/s]
[downloaded dna_r9.4.1.zip]                                                                         

Traceback (most recent call last):
  File "/scratch/qaafi/uqcong/conda-bonito/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/scratch/qaafi/uqcong/bonito/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/scratch/qaafi/uqcong/bonito/bonito/cli/download.py", line 109, in main
    File(__models__, model, args.force).download()
  File "/scratch/qaafi/uqcong/bonito/bonito/cli/download.py", line 65, in download
    with ZipFile(self.location(fname), 'r') as zfile:
  File "/scratch/qaafi/uqcong/conda-bonito/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/scratch/qaafi/uqcong/conda-bonito/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`
```

Please advice! thank you!

**Comment by iiSeymour** [comment]
@s4251484 I can't reproduce this issue, does this happen every time? Can you try again with `bonito download --models -f`.

Could this be your network security/proxy settings? If `/scratch/qaafi/uqcong/bonito/bonito/models/dna_r9.4.1.zip` isn't a zip file can you check what type of file you are getting by running `file /scratch/qaafi/uqcong/bonito/bonito/models/dna_r9.4.1.zip`. The progress does show a 50.1MB is received so it's a little strange.

**Comment by s4251484** [comment]
> @s4251484 I can't reproduce this issue, does this happen every time? Can you try again with `bonito download --models -f`.
> 
> Could this be your network security/proxy settings? If `/scratch/qaafi/uqcong/bonito/bonito/models/dna_r9.4.1.zip` isn't a zip file can you check what type of file you are getting by running `file /scratch/qaafi/uqcong/bonito/bonito/models/dna_r9.4.1.zip`. The progress does show a 50.1MB is received so it's a little strange.

Hi! thanks for attending to this.
i followed the get method as mentioned in https://github.com/nanoporetech/bonito/issues/69#issuecomment-728163288
I managed to unzip dna_r9.4.1@v1 and dna_r9.4.1
but not the rest, below is the output I got for some of the models ()

[uqcong7@wiener models]$ ls -lht
total 192M
-rw-r--r-- 1 uqcong7 wiener-qaafi  41M May 27 15:25 uetgwsnb8yfqvuyoka8p09mxilgskqc7.zip
-rw-r--r-- 1 uqcong7 wiener-qaafi  40M May 27 13:35 47t2y48zw4waly25lmzx6sagf4bbbqqz.zip
-rw-r--r-- 1 uqcong7 wiener-qaafi  39M May 27 11:55 hrv649cvx8lvomu1u0tsd47e5u2bbabt.zip
-rw-r--r-- 1 uqcong7 wiener-qaafi  48M May 27 11:13 arqi4qwcj9btsd6bbjsnlbai0s6dg8yd.zip
-rw-r--r-- 1 uqcong7 wiener-qaafi  24M May 27 10:52 n8c07gc9ro09zt0ivgcoeuz6krnwsnf6.zip
drwxr-sr-x 2 uqcong7 wiener-qaafi 4.0K May 24 22:32 configs
-rw-r--r-- 1 uqcong7 wiener-qaafi  115 May 24 07:39 README.md
drwxr-sr-x 2 uqcong7 wiener-qaafi 4.0K Apr 20 06:38 dna_r9.4.1
drwxr-sr-x 2 uqcong7 wiener-qaafi 4.0K Oct 22  2020 dna_r9.4.1@v1

# dna_r9.4.1@v3.1
`[uqcong7@wiener` models]$ unzip uetgwsnb8yfqvuyoka8p09mxilgskqc7.zip`
Archive:  uetgwsnb8yfqvuyoka8p09mxilgskqc7.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of uetgwsnb8yfqvuyoka8p09mxilgskqc7.zip or
        uetgwsnb8yfqvuyoka8p09mxilgskqc7.zip.zip, and cannot find uetgwsnb8yfqvuyoka8p09mxilgskqc7.zip.ZIP, period.

# dna_r9.4.1@v3.2
`[uqcong7@wiener` models]$ unzip 47t2y48zw4waly25lmzx6sagf4bbbqqz.zip`
Archive:  47t2y48zw4waly25lmzx6sagf4bbbqqz.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 47t2y48zw4waly25lmzx6sagf4bbbqqz.zip or
        47t2y48zw4waly25lmzx6sagf4bbbqqz.zip.zip, and cannot find 47t2y48zw4waly25lmzx6sagf4bbbqqz.zip.ZIP, period.

# dna_r9.4.1@v3.3
`[uqcong7@wiener` models]$ unzip hrv649cvx8lvomu1u0tsd47e5u2bbabt.zip`
Archive:  hrv649cvx8lvomu1u0tsd47e5u2bbabt.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of hrv649cvx8lvomu1u0tsd47e5u2bbabt.zip or
        hrv649cvx8lvomu1u0tsd47e5u2bbabt.zip.zip, and cannot find hrv649cvx8lvomu1u0tsd47e5u2bbabt.zip.ZIP, period.
