### ISSUE TITLE
Memory leak in version 0.4? 

### ISSUE THREAD

**Issue by dominik-handler** [nanoporetech/bonito#162]
Hi,

I am trying to basecall my data using bonito 0.4 with the embedded, or a self-trained model. In both cases the memory requirements grow over time to a point at which my cluster jobs with 40G of memory are terminated with an out of memory error. 

Do you know something that could help?

Thank you,
Dominik

**Comment by iiSeymour** [comment]
Hi @dominik-handler 

Are you using conda by any chance? I'm seeing most reports of memory issues linked to using conda.

It's also worth noting that now [guppy 5.0 is out](https://community.nanoporetech.com/posts/guppy-v5-0-7-release-note) you will benefit from faster basecalling and qscores by using that.

**Comment by dominik-handler** [comment]
No, I built my own singularity container and installed bonito using pip. 

I also just realized that I can export my own model and use guppy to basecall. Will try that now. Des guppy 5.0 fully support the exported crf models?

**Comment by iiSeymour** [comment]
Yes, that's correct you can export your model with: 

```
$ bonito export /path/to/bonito-model > /path/to/bonito-model/weights.jsn
```

Then use `-m ` with `guppy_basecaller -m /path/to/bonito-model/weights.jsn ...` with guppy. 

```
-m [ --model_file ] arg               Path to JSON model file.
```

**Comment by dominik-handler** [comment]
I close it as basecalling with Guppy using the custom model functions very nicely.
