### ISSUE TITLE
Merging ctc training datasets after bonito basecalling

### ISSUE THREAD

**Issue by menickname** [nanoporetech/bonito#163]
Dear @iiSeymour 

I am currently trying the "shorter-way" Bonito training using the --save-ctc and --reference functions to automatically generate the ctc training data. This successfully worked for a single dataset, however I was wondering how I could merge training data from different datasets together? I am not sure if this would be possible? 

That would be interesting as I do not have the possibility to use a single reference file for different datasets.

Thank you in advance.
Regards,
Nick Vereecke

**Comment by iiSeymour** [comment]
Hey @menickname 

Yes, you can stack multiple CTC training data together and you can find some code here https://github.com/nanoporetech/bonito/discussions/113#discussioncomment-395352

Does this solve your use case?

**Comment by menickname** [comment]
Exactly what I was looking for. Thanks a lot!
