### ISSUE TITLE
Bonito v0.4.0 uses dna_r9.4.1 or dna_r9.4.1@v3.3 by default?

### ISSUE THREAD

**Issue by menickname** [nanoporetech/bonito#164]
Dear @iiSeymour 

A rather basic question, but does Bonito v.0.4.0 automatically use the latest dna_r9.4.1@v3.3 model for basecalling or should this be specified?

Thank you in advance.
Best regards,
Nick Vereecke

**Comment by iiSeymour** [comment]
When installing `ont-bonito` via pip the latest models will be downloaded automatically, if you are pulling from github this won't be the case. Using the long form of the model name is the safest way to ensure which model is running.

**Comment by menickname** [comment]
Perfect, that's what I thought. We have an installation on our HPC at the university, so I guess it will be safest to go for the latter and simply include the full name. Thanks for the quick reply!
