### ISSUE TITLE
recommended medaka model for latest release

### ISSUE THREAD

**Issue by menickname** [nanoporetech/bonito#168]
Dear @iiSeymour 

I think you are currently working on a new Bonito v0.4.0 model for medaka? But in meanwhile, do you recommend to use current r941_min_sup_g507_model model?

Thank you in advance.
Best regards,
Nick

**Comment by iiSeymour** [comment]
Hey Nick,

Yes, the `sup_g507` models are what you want. There is no need for new medaka models for the v0.4.0 release.

HTH.

**Comment by menickname** [comment]
Perfect! Thanks for the quick response!
