### ISSUE TITLE
Question about blank_score 

### ISSUE THREAD

**Issue by HaoDreamlong** [nanoporetech/bonito#169]
I notice that there is a blank_score in this release for crf model, and seems like to be a fix number for stay scores. I wonder why you think it is better ? and what's the  benefits?

**Comment by Hybol1993** [comment]
> I notice that there is a blank_score in this release for crf model, and seems like to be a fix number for stay scores. I wonder why you think it is better ? and what's the benefits?

Hello, I am using bonito 0.4.0 with the model dna_r10.3@v3.3  but I still get blank scores (all "????"). Have you already received the quality scores with the latest model? Maybe something is wrong on my side.

**Comment by iiSeymour** [comment]
@Hybol1993 see my response on qscores values in https://github.com/nanoporetech/bonito/issues/144.

@HaoDreamlong a score per state makes it harder for the optimizer in certain contexts.
