### ISSUE TITLE
Pretrained Larger Quartznet Models

### ISSUE THREAD

**Issue by kedartatwawadi** [nanoporetech/bonito#17]
Hi! 

Thanks for providing this very useful repo, and the pre-trained model. I am using the bonito model as a transfer learning model for the application of designing error correction techniques for DNA based data storage. 

Did you also try training the larger (10x15) quartznet models? Would it be possible to share their weights? Any other trained models would be useful to try out! (especially the ones which work well on shorter lengths)

Thanks,
Kedar

**Comment by iiSeymour** [comment]
Hi @kedartatwawadi 

Yes, both the 10x15 and 15x15 models have been tried but did not yield better results at the time. Shorter _(sequence)_ lengths for inference? The training set used to produce the pretrained model is available along with this repo and `bonito tune` can be use to automatically explore new model architectures. You can set a large budget in terms of the number of total network parameters if you are interested in exploring larger models.

HTH,

Chris.

**Comment by kedartatwawadi** [comment]
Thanks a lot!
