### ISSUE TITLE
bonito with CUDA v 11.0

### ISSUE THREAD

**Issue by mawa86** [nanoporetech/bonito#170]
Hi
Im trying to pip install bonito, but i see a problem with dependencies. It installs cupy-cuda102 and then warns me that CuPy is not installed correctly. I checked, and found that for my version of CUDA (11.0), cupy-cuda110 is needed rather than 102. 

Is there a way to bypass automatic pulling of a specific version of CuPy while installing bonito? Or even telling pip to bring along the right version?
I'd like to retain my CUDA version...

**Comment by chAwater** [comment]
Maybe this will help you: https://github.com/nanoporetech/bonito/issues/153#issuecomment-848085336

**Comment by iiSeymour** [comment]
https://github.com/nanoporetech/bonito/commit/98acb6f91ac2d4f452d18f7d5f421bc3b617ce87 adds basic support for CUDA 11.1 builds suitable for ampere GPUs.

```
pip install -f https://download.pytorch.org/whl/torch_stable.html ont-bonito-cuda111
```
