### ISSUE TITLE
crf-beam ppc64le wheel?

### ISSUE THREAD

**Issue by btu6626** [nanoporetech/bonito#173]
First, I would like to thank you for developing and maintaining this extraordinary piece of software. I am currently trying to run bonito on a POWER9 cluster but the source code of crf-beam is not publicly available. Is it possible to push a wheel targeting ppc64le architecture and python 3.7?

**Comment by iiSeymour** [comment]
Thanks @btu6626 - unfortunately it would be hard to support `ppc64le` as I don't have a development environment.
