### ISSUE TITLE
bonito train to have a resume/continue mode

### ISSUE THREAD

**Issue by menickname** [nanoporetech/bonito#174]
Dear @iiSeymour 

It would be interesting to be able to resume/continue a basecall training process after it has crashed or reserved time on a HPC facility is reached. Is this already available or is there a workaround for this as for the [https://github.com/nanoporetech/bonito/issues/122](url) by @Kirk3gaard. 

Thank you in advance.
Regards

**Comment by iiSeymour** [comment]
Hey @menickname 

See the finetuning section under https://github.com/nanoporetech/bonito#training-your-own-model

**Comment by menickname** [comment]
Dear @iiSeymour 

Thanks for the reply, so I guess my command would look something like this then?

`bonito train [options] --pretrained MYMODELPART1_IN --directory MYMODELPART2_OUT`

What would be the file I have to input, the last weightX.tar or the config.toml file within the trained directory?

Thank you in advance.
Nick
