### ISSUE TITLE
Memory problem when running on cluster

### ISSUE THREAD

**Issue by lkerr34** [nanoporetech/bonito#184]
I have been using bonito on a small test dataset of only 4000 reads.  Working on an interactive gpu node on a computer cluster I can get everything working fine. However, when I try to submit the same job to the cluster (requesting the same resources of 1 gpu and 64G) the jobs fail. For example, when I try to use bonito basecaller it fails with exit status "failed  46  : execd enforced h_vmem limit". In this case maxvmem was 621.689G which I think is surprisingly large considering the small amount of data I am working with. I am struggling to understand why there are memory issues when using qsub but no memory issues when things are run interactively. I'd appreciate any suggestions/help!

**Comment by lkerr34** [comment]
Also, the job ends after only about a 90 seconds and the output is 

> loading model
^M> calling: 0 reads [00:00, ? reads/s]

so it appears that no basecalls are made.

**Comment by iiSeymour** [comment]
It's not obvious what is going on here - this is not something I've seen. 

Is this just for regular basecalling jobs? If yes, is there any reason to not use guppy as all the simplex improvements are available in guppy 5.

**Comment by lkerr34** [comment]
For now it is just for regular basecalling but I want to use the duplex feature in the future which I believe means I will need to use bonito?

**Comment by iiSeymour** [comment]
Duplex hasn't made a full guppy release quite yet but a beta version was made available last week. See https://community.nanoporetech.com/posts/q20-community-update for more info.

**Comment by lkerr34** [comment]
I'll have a look at this thanks!
