### ISSUE TITLE
Right way to evaluate a model

### ISSUE THREAD

**Issue by singagan** [nanoporetech/bonito#193]
Hi, 
I was wondering: When we change a basecaller's architecture and train the model on the default dataset, to evaluate the accuracy should we use the ctc data from the default architecture (before we modified the model), or we should generate ctc data again using the new model and then use it to evaluate the new basecaller's performance.

Also: Does `bonito --evaluate` provide us with the read accuracy or consensus accuracy?

I would really appreciate any feedback on it.

Thanks!!

**Comment by iiSeymour** [comment]
I wouldn't recommend using `bonito evaluate` and ctc data for model evaluation. The best thing to do is use the basecaller and provide a reference _(either a `.fasta` or `.mmi`)_, this will give you a SAM file and a summary file with per read information including alignment accuracy.

```
$ bonito basecaller model_dir data_dir --reference ref.mmi > basecalls.sam
$ column -t basecalls_summary.tsv | less -S
```
