### ISSUE TITLE
pair decoding of R2C2 data

### ISSUE THREAD

**Issue by christopher-vollmers** [nanoporetech/bonito#194]
Hi,

I am very interested in experimenting with the pair decoding of bonito for our R2C2 data. 

Two questions:
1) Is there still a way to produce .npy files required by poreover? Is seems like the patch poreover came with was version specific and doesn't even work on that specific version anymore. 

2) Have you looked at making consensus sequences from multiple raw reads?
 
Thank you,
Chris

**Comment by christopher-vollmers** [comment]
Still interested in this or other ways to enable duplex calling on R2C2 data. We could probably generate split fast5 files by going the fast5->slow5->fast5 route and using the bonito move table. But I'm sure having the reads in the same orientation would break the guppy duplex module. Any advice would be great.

**Comment by davidnewman02** [comment]
Closing as inactive. 
Doing a signal-based consensus is out of scope for the Bonito project. `dorado polish` and `medaka consensus` are our recommend base-space consensus tools.
