### ISSUE TITLE
model for R10.3 flowcells

### ISSUE THREAD

**Issue by thackl** [nanoporetech/bonito#206]
Hi, 

I have some data from R10.3 flowcells. bonito-v0.5.0 doesn't seem to have pre-trained models for those cells. I tried R10.4 but the results look poor. The older bonito version seemed to have R10.3 models. Any chance to make those available for v0.5.0 as well?

**Comment by thackl** [comment]
Ah, just saw that this is appears to be also the issue in #195

**Comment by iiSeymour** [comment]
All the old model [URLs are stable and still available](https://github.com/nanoporetech/bonito/blob/v0.4.0/bonito/cli/download.py#L93) - here's how you can run `dna_r10.3@v3.3` under bonito v0.5.0.

```
$ wget https://nanoporetech.box.com/shared/static/ci6xdu7d4wczmhorhw1sweyg4gczx97t.zip
$ unzip ci6xdu7d4wczmhorhw1sweyg4gczx97t.zip 
$ bonito basecaller ./dna_r10.3@v3.3 data > calls.sam
```

**Comment by thackl** [comment]
Awesome. Will check it out right away. Thanks for the quick reply!

**Comment by thackl** [comment]
Works like a charm!
