### ISSUE TITLE
Define e8 and e8.1?

### ISSUE THREAD

**Issue by nextgenusfs** [nanoporetech/bonito#210]
What do the e8 and e8.1 tags refer to in the models? `R9.4.1 E8` versus  `R9.4.1 E8.1`

**Comment by jdemeul** [comment]
They refer to the version of the motor enzyme used if I'm not mistaking.
E8 is the motor in kits like RAD004, LSK109 and 110 that while E8.1 is used in the new Q20+ kit.

**Comment by nextgenusfs** [comment]
Great thanks. That's what I had assumed but wanted clarification. So I guess that also means they run at different speeds, we have not yet tried the new Q20 kits.

**Comment by iiSeymour** [comment]
That's right, E8 is Kit 9, 10, 11 and E8.1 is the new Kit 12 _(Q20+)._
