### ISSUE TITLE
Bonito doesn't appear to go through all of the fast5 files

### ISSUE THREAD

**Issue by amijalis** [nanoporetech/bonito#211]
Hello! I recently ran Bonito on my first Minion data set. I ran the following command

```bonito basecaller --batchsize 64 dna_r9.4.1_e8_hac@v3.3 ./fast5_pass > ./sam/basecalls.sam```

and the program ran uninterrupted for ~90 minutes, generating an even 348,000 reads and exiting. However, I had an estimated 4M reads from the sequencer, and going through the output file, it appears that Bonito only went through a small fraction of the reads. There were ~86 Fast5 files in the folder and no error message. Is there anything obvious that I missed here? Thanks!

**Comment by iiSeymour** [comment]
Hi @amijalis 

The default number of reads in a Fast5 file is 4,000 and you have ~86 files in your `fast5_pass` folder - I don't think any reads have been mised as 4,000 * 86 = 344,000. Have you accounted for the reads in `fast5_fail`?

**Comment by amijalis** [comment]
Thanks for the information and the prompt reply. You are correct, that’s where the missing reads went. Sorry for the false alarm!
