### ISSUE TITLE
Multi-GPU training Issue

### ISSUE THREAD

**Issue by cuzy-zhi** [nanoporetech/bonito#213]
Hi Bonito developer,

I am training my own model with "multi-gpu” enabled and "CUDA_VISIBLE_DEVICES=4,5,6,7".
Below is the command I use (by the way I am using bonito v0.4.0):
CUDA_VISIBLE_DEVICES=4,5,6,7 bonito train -f --epochs 40 --batch 32 --multi-gpu --directory /path/to/training/datasets --config /path/to/config/config.toml /path/to/output/dir

So I expect the model should use 4 GPUs. However, when I monitor the GPU usage, I find the model training is only using one GPU like below:

![图片](https://user-images.githubusercontent.com/77615590/145978605-c9a38dcf-c693-4fbe-a4c1-1863260a3744.png)

Do you have any idea on this issue? Thanks

**Comment by iiSeymour** [comment]
Hi @cuzy-zhi - bonito no longer supports multi-gpu training and the command option was removed in v0.5.0.

**Comment by cuzy-zhi** [comment]
> 

Hi @iiSeymour, got it. I will check the latest version later.
