### ISSUE TITLE
question about beamsearch method in koi package in Bonito v0.5 version。

### ISSUE THREAD

**Issue by piaohe111** [nanoporetech/bonito#215]
hi
     firstly，thank you very much for excellent work about new beamsearch decode with qstring output.  But I have some problems . I found the shape of crf model output is T,N,C, and beamsearch input in basecaller.py require score shape is N,T,C . after I use permute method ,I can run basecall with beamsearch decode, however I run minmap result is 0 with basecall result .  I do not modify code in bonito v0.5 . Hope to get reply ,thank you  !!!

**Comment by iiSeymour** [comment]
Hi @piaohe111 

You are correct that the scores will come out model in `T, N, C` and the beam search requires `N, T, C` so your model should look something like this: 

```
Model(
  (encoder): Serial(
    (0): Convolution(
      (conv): Conv1d(1, 4, kernel_size=(5,), stride=(1,), padding=(2,))
      (activation): Swish()
    )
    (1): Convolution(
      (conv): Conv1d(4, 16, kernel_size=(5,), stride=(1,), padding=(2,))
      (activation): Swish()
    )
    (2): Convolution(
      (conv): Conv1d(16, 768, kernel_size=(19,), stride=(5,), padding=(9,))
      (activation): Swish()
    )
    (3): Permute(2, 0, 1)
    (4): LSTM(
      (rnn): LSTM(768, 768)
    )
    (5): LSTM(
      (rnn): LSTM(768, 768)
    )
    (6): LSTM(
      (rnn): LSTM(768, 768)
    )
    (7): LSTM(
      (rnn): LSTM(768, 768)
    )
    (8): LSTM(
      (rnn): LSTM(768, 768)
    )
    (9): Permute(1, 0, 2)
    (10): LinearCRFEncoder(
      (linear): Linear(in_features=768, out_features=4096, bias=True)
      (activation): Tanh()
    )
  )
)
```

The new beam search also requires a fixed blank score model and for the scores not to be expanded with the blank - so `blank_score=2.0, expand_blanks=False`.

https://github.com/nanoporetech/bonito/blob/cf64bae38a2bd5acabf5d9ccdd64b72b11e10935/bonito/crf/model.py#L142

**Comment by piaohe111** [comment]
thank you very much, I will check this problem !

**Comment by piaohe111** [comment]
hi
      I want to train the crf model  with dna_r9.4.1@v3.1.toml ，so blank_score=2.0,expand_blanks=True，if expand_blanks=False,model output dimension is 4096 ,loss computation will be wrong . Such as the wrong location from logZ function below. I am wondered whether the blank_score and expand_blanks is different in train and basecall code. hope to have answer ,sorry for disturbing you !
def logZ(self, scores, S:semiring=Log):
    T, N, _ = scores.shape
    Ms = scores.reshape(T, N, -1, len(self.alphabet))  ##if set 4096 this code will not correct
    alpha_0 = Ms.new_full((N, self.n_base**(self.state_len)), S.one)
    beta_T = Ms.new_full((N, self.n_base**(self.state_len)), S.one)
    return seqdist.sparse.logZ(Ms, self.idx, alpha_0, beta_T, S)

**Comment by piaohe111** [comment]
I have answer now !  when train model ,the train setting is blank_score=2.0,expand_blanks=True, model output dimension is 4096 ,5120 aftering padding with fixed blank_score. when basecalling use pretrained model,expand_blanks should set False to remove pad operation ,  hahaha,I will close the issue !
