### ISSUE TITLE
the question about beamsearch 

### ISSUE THREAD

**Issue by piaohe111** [nanoporetech/bonito#218]
hi：
        With new beamsearch method with qstring output ，the speed of basecall with CRF model is very fast，and minmap result is good 。 Now I hope to know something about the new beamsearch theory。Or is there some docs about it ?  Thank you very much for this excellent work ！！

**Comment by iiSeymour** [comment]
Thanks @piaohe111 - does this help https://towardsdatascience.com/an-intuitive-explanation-of-beam-search-9b1d744e7a0f
