### ISSUE TITLE
trimming adapter about bonito

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/bonito#219]
Hi, I just would like to know whether guppy or bonito will trim adapter during the basecalling process? If yes, we would like to know whether it is by default or needs setting some parameters manually. By the way, will bonito basecall all electric signal to sequence, or remove some electric signals and then basecall the remain signals to sequences?
Thank you very much.

**Comment by iiSeymour** [comment]
Hi @Flower9618 

Bonito only does a [simple peak detection](
https://github.com/nanoporetech/bonito/blob/master/bonito/fast5.py#L136) in signal space to trim the start of each [read](https://github.com/nanoporetech/bonito/blob/master/bonito/fast5.py#L78). No sequence-based trimming is done currently.

**Comment by Flower9618** [comment]
> Hi @Flower9618
> 
> Bonito only does a [simple peak detection](https://github.com/nanoporetech/bonito/blob/master/bonito/fast5.py#L136) in signal space to trim the start of each [read](https://github.com/nanoporetech/bonito/blob/master/bonito/fast5.py#L78). No sequence-based trimming is done currently.

Thank you very much for your reply. Why does the peak in signal space needs to be trimmed? What does that mean if there is a peak in the signal?

**Comment by davidnewman02** [comment]
Closing as inactive.

Bonito will by default do a simple trimming at the start of a read: [reader.trim](https://github.com/nanoporetech/bonito/blob/0c7fcceeeca16e300ba427d737282b33d3cb8ec9/bonito/reader.py#L122)

This is done to remove signal which does not correspond to target DNA/RNA transitioning through the pore, which can in some cases cause poor basecall results as this signal can be outside the expected range of current levels.
