### ISSUE TITLE
Training questions

### ISSUE THREAD

**Issue by Heiseweiye** [nanoporetech/bonito#223]
Hi, when i start to train my own model, the following happens:
FileNotFoundError: [Errno 2] No such file or directory: '/data/dna_r9.4.1/dataset.py'

**Comment by zmunro** [comment]
Hello! Can you provide the full command you are executing that produces this error?

**Comment by Heiseweiye** [comment]
command:
$ bonito download --training
$ bonito train /data/training/dna_r9.4.1

Do I need to remove the ‘/’ before 'data'

**Comment by Heiseweiye** [comment]
> Hello! Can you provide the full command you are executing that produces this error?

command:
$ bonito download --training
$ bonito train /data/training/dna_r9.4.1

Do I need to remove the ‘/’ before 'data'

**Comment by zmunro** [comment]
You need to specify whatever the path to the `dna_r9.4.1` file is. What your command is currently telling bonito is that there is a `/data` directory at the root of your filesystem, and in there it can find a `/data/training/` directory with the `dna_r9.4.1` file in it.

**Comment by Heiseweiye** [comment]
> You need to specify whatever the path to the `dna_r9.4.1` file is. What your command is currently telling bonito is that there is a `/data` directory at the root of your filesystem, and in there it can find a `/data/training/` directory with the `dna_r9.4.1` file in it.



> You need to specify whatever the path to the `dna_r9.4.1` file is. What your command is currently telling bonito is that there is a `/data` directory at the root of your filesystem, and in there it can find a `/data/training/` directory with the `dna_r9.4.1` file in it.

![3A8A549C](https://user-images.githubusercontent.com/43317174/150972276-84960ae2-4e72-4f0b-8346-3378510c3f6d.gif)


> You need to specify whatever the path to the `dna_r9.4.1` file is. What your command is currently telling bonito is that there is a `/data` directory at the root of your filesystem, and in there it can find a `/data/training/` directory with the `dna_r9.4.1` file in it.

Thanks for your help, I have already solved it.
