### ISSUE TITLE
Update function arguments with types and add comment descriptions

### ISSUE THREAD

**Issue by zmunro** [nanoporetech/bonito#224]
I think the ability for community contributors to help out on this project would be greatly improved. I am planning on taking this up myself and following the [Google Python Comment style guide](https://google.github.io/styleguide/pyguide.html#244-decision) since it is very easy to read and work with, along with PEP8 everywhere else.

**Comment by zmunro** [comment]
@iiSeymour Many parts of this codebase break conventional python styling rules, which makes it hard to read and understand for people who are unfamiliar with the codebase and are seeing it for the first time. Something as simple as capitalizing global variables and adding comments to each function would massively improve people's ability to contribute. I am happy to undertake this task but want to make sure you are okay with it being done. I would imagine this would be something that would best be accomplished in sections and not all at once.

**Comment by iiSeymour** [comment]
@zmunro thanks for the offer however this is quite subjective and I don't think this is a real problem for bonito.
