### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by shimbalama** [nanoporetech/bonito#23]
HI all,

I can't see any pre-trained models for human DNA. Did I miss them somewhere or do you plan to  release some soon?

Thanks,
Liam

**Comment by iiSeymour** [comment]
Hi @shimbalama 

Bonito provides a pre-trained model for r9.4.1 that is suitable for human DNA. If you are installing Bonito from GitHub then run `./scripts/get-models` to download it. If you are installing Bonito via pip then the model is bundled and no extra steps are required.

HTH.

Chris.
