### ISSUE TITLE
some details about ctc crf model

### ISSUE THREAD

**Issue by xiongjun19** [nanoporetech/bonito#232]
Hi Dear！ 
    I'm a little confused about the code in the ctc crf model, I have four questions: 
1. why 1024 * 5  is needed for the last linear layer? 
2. is the ctc-crf means the CAT？ 
3. why the self.idx designed like this：
     tensor([[   0,    0,  256,  512,  768],
        [   1,    0,  256,  512,  768],
        [   2,    0,  256,  512,  768],
        ...,
        [1021,  255,  511,  767, 1023],
        [1022,  255,  511,  767, 1023],
        [1023,  255,  511,  767, 1023]], dtype=torch.int32)
4. how is the input signal is grouped: in data 9.4.1; 
   for exmple suppose the  sequece is [x1, x2, x3, x4, x5, x6, ..., xN]：
     one way is： 
           [(x1, x2, x3, x4, x5), (x6, x7, x8, x9, x10), ....]；
    another way is： 
         [(x1, ..., x5), (x2, ..., x6), ...., [];](url)
        
it would be very helpful if you give me some insights about this！
thanks you guys open this great repository, I have learn many things from it.

**Comment by protein2019** [comment]
I guess the CTC-CRF model is an extension of the flipflop model, and it may not be related to CAT. The outputs of the last linear layer are scores for six consecutive bases.

**Comment by davidnewman02** [comment]
Closing as inactive.

> why 1024 * 5 is needed for the last linear layer?
This is the size of the state space for the decoder

> ctc-crf
CTC == Connectionist Temporal Classification. This is a loss function that can be used when the output length is variable and not a 1:1 mapping to the input length
CRF == Conditional Random Field. This is a framework for modelling structured prediction tasks, used here as the output has token to token interdependence. 

> self.idx structure and data grouping
I don't understand what the question here is
