### ISSUE TITLE
Initialization error (related to koi)?

### ISSUE THREAD

**Issue by snajder-r** [nanoporetech/bonito#234]
Hi!

We're trying to run bonito basecaller and are experiencing some issues.

    $ bonito basecaller --reference reference.mmi --device cuda:0  -- dna_r9.4.1_e8.1_sup@v3.3 reads_directory
    > loading model dna_r9.4.1_e8.1_sup@v3.3
    > loading reference
    > outputting aligned sam
    > calling: 0 reads [00:00, ? reads/s]@HD        VN:1.5  SO:unknown      ob:0.0.2
    @PG	ID:basecaller	PN:bonito [... SNIP ...]
    Error - initialization error 
    Error - initialization error 
    Error - initialization error 
    Error - initialization error 
    > skipping empty sequence 005fa44f-7f88-4481-ba0c-91d5293dce54
    > calling: 7 reads [00:01,  1.94 reads/s]Error - initialization error 
    Error - initialization error 
    Error - initialization error 

With a little debugging we find that the initializiation error seems to emerge from koi, namely from decode.py lines 54-56

    lib.host_back_guide_step(*args)
    lib.host_beam_search_step(*args)
    lib.host_compute_posts_step(*args)
    lib.host_run_decode(*args)

As described in the bonito readme we use CUDA 10.2, which is also what our GPUs support. We use bonito 0.5.1.

Thanks a lot!

**Comment by vellamike** [comment]
Hi @snajder-r , would it be possible to provide some data to reproduce this error?

**Comment by snajder-r** [comment]
Hi  @vellamike!

Certainly. I can reproduce the error with:

    wget https://ont-exd-int-s3-euwst1-epi2me-labs.s3-eu-west-1.amazonaws.com/fast5_tutorial/sample_fast5.tar
    tar -xvf sample_fast5.tar 
    bonito basecaller -- dna_r9.4.1_e8.1_sup@v3.3 sample_fast5/workspace/

GPU: NVIDIA Corporation TU102 [TITAN RTX] (rev a1)

Driver and CUDA version according to `nvidia-smi`:

    NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2

Conda environment:

    # Name                    Version                   Build  Channel
    _libgcc_mutex             0.1                        main  
    ca-certificates           2021.10.26           h06a4308_2  
    certifi                   2021.10.8        py38h06a4308_2  
    cffi                      1.15.0                   pypi_0    pypi
    chardet                   4.0.0                    pypi_0    pypi
    fast-ctc-decode           0.3.0                    pypi_0    pypi
    flatbuffers               2.0                      pypi_0    pypi
    h5py                      3.6.0                    pypi_0    pypi
    idna                      2.10                     pypi_0    pypi
    joblib                    1.1.0                    pypi_0    pypi
    ld_impl_linux-64          2.35.1               h7274673_9  
    libffi                    3.3                  he6710b0_2  
    libgcc-ng                 9.1.0                hdf63c60_0  
    libstdcxx-ng              9.1.0                hdf63c60_0  
    mappy                     2.24                     pypi_0    pypi
    ncurses                   6.3                  h7f8727e_2  
    numpy                     1.19.5                   pypi_0    pypi
    onnx                      1.11.0                   pypi_0    pypi
    onnxruntime               1.10.0                   pypi_0    pypi
    ont-bonito                0.5.1                     dev_0    <develop>
    ont-fast5-api             3.3.0                    pypi_0    pypi
    ont-koi                   0.0.7                    pypi_0    pypi
    ont-remora                0.1.2                     dev_0    <develop>
    openssl                   1.1.1m               h7f8727e_0  
    packaging                 21.3                     pypi_0    pypi
    pandas                    1.1.5                    pypi_0    pypi
    parasail                  1.2                      pypi_0    pypi
    pip                       21.2.4           py38h06a4308_0  
    progressbar33             2.4                      pypi_0    pypi
    protobuf                  3.19.4                   pypi_0    pypi
    pycparser                 2.21                     pypi_0    pypi
    pyparsing                 3.0.7                    pypi_0    pypi
    pysam                     0.18.0                   pypi_0    pypi
    python                    3.8.12               h12debd9_0  
    python-dateutil           2.8.2                    pypi_0    pypi
    pytz                      2021.3                   pypi_0    pypi
    pyvbz                     1.0.1                    pypi_0    pypi
    readline                  8.1.2                h7f8727e_1  
    requests                  2.25.1                   pypi_0    pypi
    scikit-learn              1.0.2                    pypi_0    pypi
    scipy                     1.5.4                    pypi_0    pypi
    setuptools                58.0.4           py38h06a4308_0  
    six                       1.16.0                   pypi_0    pypi
    sqlite                    3.37.2               hc218d9a_0  
    tabulate                  0.8.9                    pypi_0    pypi
    thop                      0.0.31-2005241907          pypi_0    pypi
    threadpoolctl             3.1.0                    pypi_0    pypi
    tk                        8.6.11               h1ccaba5_0  
    toml                      0.10.2                   pypi_0    pypi
    torch                     1.10.2                   pypi_0    pypi
    tqdm                      4.31.1                   pypi_0    pypi
    typing-extensions         4.1.1                    pypi_0    pypi
    urllib3                   1.26.8                   pypi_0    pypi
    wheel                     0.37.1             pyhd3eb1b0_0  
    xz                        5.2.5                h7b6447c_0  
    zlib                      1.2.11               h7f8727e_4

**Comment by hiroshisuga** [comment]
Same here. 
After a couple of tests, I was successful with cuda=4 option. No luck when cuda=1 or cuda=2 was specified...

**Comment by zhanglzu** [comment]
I got the same question.
After I update nividia driver from 10.2 to 11.7, and everything be fine. I have no idear about what is happening.
ps :centos 7.6 and Tesla V100

**Comment by zhanglzu** [comment]
I also Got a Qustion.
Since I have two V100s, if i use the first one (--device cuda:0), and it got work. But if I use the second one (--devise cuda:1) , and would got the "Error - initialization error " error.

**Comment by davidnewman02** [comment]
Closing as inactive. 
If you are having issues with Bonito using the latest release then please raise a new ticket
