### ISSUE TITLE
Error installing bonito

### ISSUE THREAD

**Issue by bhargava-morampalli** [nanoporetech/bonito#235]
I have trouble installing bonito on Ubuntu 18.04 with RTX 3080 gpu and Cuda version 11.6 

The error I get is in the screenshot below - failed to build wheel for mappy and ont-remora
Please let me know if anyone faced this issue and suggestions to resolve this
![Screenshot 2022-03-08 at 6 48 28 AM](https://user-images.githubusercontent.com/20497781/157089897-50881081-9fda-4dc0-a948-a7f08102eebf.png)

Thanks.

**Comment by bhargava-morampalli** [comment]
![Screenshot 2022-03-08 at 6 59 25 AM](https://user-images.githubusercontent.com/20497781/157091264-7e1ba40d-d261-4296-b525-65a9165547cc.png)

More error code

**Comment by marcus1487** [comment]
This appears to be an error with your conda environment. The error notes missing libraries expected with a python installation that I've observed can be missing for some conda installations. Could you try to install outside of your conda environment to confirm that this is an issue with conda?
