### ISSUE TITLE
Help train

### ISSUE THREAD

**Issue by simonbrd** [nanoporetech/bonito#241]
Hello,
I have a problem regarding using bonito to build my own methylation detection model on microalgae data. I do the following workflow :

```
$ git clone https://github.com/nanoporetech/bonito.git  # or fork first and clone that
$ cd bonito
$ python3 -m venv venv3
$ source venv3/bin/activate
(venv3) $ pip install --upgrade pip
(venv3) $ pip install -r requirements.txt
(venv3) $ python setup.py develop

bonito basecaller dna_r10.4_e8.1_fast@v3.4 --reference ../PrymneGenomeV1.fasta ../fast5/ --cevice cuda:0 > basecalls.bam
```

![image](https://user-images.githubusercontent.com/101809516/158817132-68434e80-0a68-43c1-a678-26bb5ba01a0c.png)

thank you in advance 
For info here is my configuration :
![image](https://user-images.githubusercontent.com/101809516/158811171-8f794936-8bdf-47e2-8920-6d0f34575363.png)

**Comment by iiSeymour** [comment]
@simonbrd you have set `--device cpu` not the GPU in your screenshot.

**Comment by simonbrd** [comment]
Yes it's true sorry...
But I still have an error with the GPUs

![bonito cuda](https://user-images.githubusercontent.com/101809516/158830430-6045d435-bd8b-4763-aaa7-b4b5302c1669.png)

**Comment by iiSeymour** [comment]
The default batch size for the fast model is 1536 and uses about ~10GB of GPU memory so try reducing the batchsize to fit your GPU memory capacity `bonito basecaller dna_r10.4_e8.1_fast@v3.4 --batchsize 512 ...`.

**Comment by simonbrd** [comment]
thank you very much it works !

**Comment by simonbrd** [comment]
Hello, I have a new problem can you help me?
![train_bonito](https://user-images.githubusercontent.com/101809516/159232619-72502bfa-00fc-49e4-8202-a411c4e03ee5.png)

for info i had this before :
`bonito basecaller dna_r10.4_e8.1_fast@v3.4 --batchsize 200 --reference ../PrymneGenomeV1.fasta ../fast5/ --device cuda:0  > data/train/basecalls_sans_ctc.bam`

**Comment by iiSeymour** [comment]
@simonbrd to save data in a training format you need to add `--save-ctc` when basecalling, the error message you are getting is because not training data is present in `data/train`.

**Comment by simonbrd** [comment]
Ok thank you.
But I don't understand because in the basecaller results I only have 2 files but no training data for the bonito train ?
![bonito res](https://user-images.githubusercontent.com/101809516/159731262-9c0f4a3e-6e64-4a36-80ad-000b7d26fb17.png)
![restrain](https://user-images.githubusercontent.com/101809516/159731573-ae61f0e1-6f8f-463b-b142-1a275c72d6fa.png)

**Comment by davidnewman02** [comment]
Closing as inactive.
In order to generate training data you need to specify the `--save-ctc` flag.
