### ISSUE TITLE
toml file and model training

### ISSUE THREAD

**Issue by hd2326** [nanoporetech/bonito#243]
Greetings @iiSeymour !

I am trying to train my own bonito models, and it would be really appreciated if you could provide some insights into the following questions.

1. What exactly do "--save-ctc" do? Specifically, what does the yielded "chunks.npy" contain? Maybe normalized event signal levels?
2. What do the parameters in the toml file mean, specifically:
    [input] features
    [qscore] bias
    [qscore] scale
    [encoder] stride
    [encoder] winlen
    [encoder] scale
    [encoder] blank_score
    [global_norm] state_len
3. Can I use different toml config files (different deep learning architectures) when running "bonito basecaller --save-ctc" and "bonito train"?

Thank you very much in advance for your help!

**Comment by davidnewman02** [comment]
Closing as inactive.
`--save-ctc` outputs a numpy array of normalised signal data (chunks.npy) and associated truth/reference data for each chunk (references.npy), which is zero-padded.

What do these mean
- `[input] features` the number of input channels to the neural-net
- `[qscore]` This is a pre-computed calibration of q-score to accuracy to ensure that the basecaller estimates match the real accuracy
- `[encoder] stride/winlen` These specify the how the signal is passed to the first layer of the neural network
- `[global_norm] state_len` `[encoder] scale/blank_score` These specify the output dimensions and post-processing of the neural network before it is passed to the decoder
