### ISSUE TITLE
About equivalence of Bonito models to that on Guppy

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/bonito#246]
Hi 

Will the results coming from Bonito be similar to that from Guppy if I select similar models?

For instance is my following assumption correct about the model equivalence:
dna_r9.4.1_e8.1_fast@v3.4 = dna_r9.4.1_450bps_fast.cfg
dna_r9.4.1_e8.1_hac@v3.4 = dna_r9.4.1_450bps_hac.cfg
dna_r9.4.1_e8.1_sup@v3.4 = dna_r9.4.1_450bps_sup.cfg

**Comment by iiSeymour** [comment]
Yes, that's right @hasindu2008
