### ISSUE TITLE
Modified base calling: Skipped bases in bam MM tag 

### ISSUE THREAD

**Issue by snajder-r** [nanoporetech/bonito#248]
Hi!

The current SAM specification of the MM tag says:

> Following the base modification codes is an optional ‘.’ or ‘?’ describing how skipped seq bases of the stated base type should be interpreted by downstream tools. When this flag is ‘?’ there is no information about the modification status of the skipped bases provided. When this flag is not present, or it is ‘.’, these bases should be assumed to have low probability of modification

Footnote: 

> The decision whether a base is assumed to be unmodified or has a probability explicitly provided is up to the modification calling program. Some programs will elide calls with modification probabilities below a threshold to provide a more compact modification tag.

Here is an example MM and ML tag I see from an BAM file generated by bonito with modified base calling (from a read that should be fully methylated):

```
MM:Z:C+z,1,7,1,1,0,1,0,0,0,32,0,4,0,2,0,2,0,1,0,11,19,2,6,6,0,6,4,20,5,6,0,1,1,10,3,11,4,2,3,0,6,1,5,5,18,5,5,0,1,0,4,4,1,1,13,6,1,1,6,0,1,0,0,6,5,10,10,0,6,6,0,2,3,1,2,0,0,0,0,0,2,0,1,3,0,4,3,4,1,0,0,0,0,3,0,2,6,2,4,1,1,0,0,3,1,1,2,13,7,0,4,0,0,3,5,0,0,0,2,0,2,1,1,2,0,5,1,0,5,2,2,12,7,1,4,2,3,10,14,4,0,11;
ML:B:C,50,2,2,7,3,5,0,6,4,255,255,252,255,255,255,255,255,1,255,254,255,238,255,255,255,255,255,255,255,255,255,2,252,255,0,255,255,108,255,234,123,255,62,243,255,255,255,255,255,255,254,234,255,255,255,255,255,248,255,255,255,255,255,242,255,255,255,255,255,255,9,7,16,255,255,255,12,253,255,255,255,255,255,255,255,255,103,253,255,255,255,255,251,255,255,0,255,140,255,255,255,255,4,250,255,255,73,255,209,255,255,255,255,255,255,255,0,255,255,255,253,43,255,20,255,255,255,255,1,255,255,255,255,66,255,255,39,255,255,255,255,212
```

Note that there is no "?" in the MM tag, so according to the SAM specification, I am to assume that all skipped Cs are unmethylated. However, there are also Cs with are reported as methylated, but the ML tag says the methylation probability is "0".

When I train a model and estimate the accuracy of methylated and unmethylated data, I find that if I interpret the BAM file as specified, I get 36% TPR and 96% TNR. If I treat the skipped Cs as if they were unknown (i.e. as if the MM tag contained the "?") then I get about 89% TPR and 90% TNR (much better). 

This observation of accuracies combined with the fact that 0 methylation probability is emitted, leads me to believe that perhaps the skipped Cs should be treated as unknown? Is that correct? Should bonito write the "?" parameter in the MM tag?

Thanks!
Rene

**Comment by marcus1487** [comment]
The current MM tag specification was updated less than 2 months ago (to resolve this ambiguity) and we have not yet applied an update to the Bonito/Remora code bases to conform to the new format. The Remora output does correspond to the MM tag with the `?` specification, so this would update the files to conform to the current specification. Though I would note that downstream tools have not yet updated to handle this spec update yet, so you may still run into issues here (I believe the htslib core library needs to be updated and IGV is working on a fix atm). We will apply a fix to Remora shortly (which will port into Bonito).

**Comment by davidnewman02** [comment]
Closing as issue has been resolved
