### ISSUE TITLE
basecalling using m1 mac GPU

### ISSUE THREAD

**Issue by thomasvangurp** [nanoporetech/bonito#254]
As the Web-based Bonito Basecaller is supposed to support m1 mac GPU-based base-calling I am wondering if I can do this on the command line as well?

**Comment by iiSeymour** [comment]
Hey @thomasvangurp no, but we are releasing an alpha preview of our new native caller `dorado` next week.

**Comment by mcrone** [comment]
Will this work with the new Jetson Orin (also ARM architecture)? Current problem is that there are machines with the latest cuda and ARM architectures which cannot be used because ONT hasn't open sourced some of their libraries or provided suitable builds.

**Comment by iiSeymour** [comment]
@mcrone yes we plan to support Jetson - I don't think we will have everything in place for the alpha release but hopefully shortly after.

**Comment by thomasvangurp** [comment]
@iiSeymour great, looking forward to playing around with dorado. Does it support methylation calling as well?

**Comment by iiSeymour** [comment]
We will have methylation calling in the second alpha release. FYI @vellamike will be giving at talk LC on Day 3 and @a-slide will also give an update on methylation calling in the same session https://londoncallingconf.co.uk/lc22/agenda
