### ISSUE TITLE
Can package dependencies be loosened?

### ISSUE THREAD

**Issue by JacobHayes** [nanoporetech/bonito#256]
Hi, I'm trying to install `ont-bonito` into an existing virtualenv, but the package dependencies ([base ones here](https://github.com/nanoporetech/bonito/blob/master/requirements.txt)) are specified quite precisely (`==`), causing conflicts with other packages I'm using. Eg: `requests==2.25.1` (released in 2020); `pysam==0.18.0` (I was using new properties in 0.19), etc

Could the requirements files be relaxed to `>=MAJOR` for most deps (and only upper bound pins for known incompatibilities, if any)?

side question: is `onnxruntime` used by the lib (anymore)? I see the dep but not sure use in the code after a quick search
side question 2: It seems this can only be installed on linux (not Mac, even for CPU only) due to `ont-koi` only having manylinux wheels - is this expected? (not a blocker, just curious)

Thanks!

**Comment by iiSeymour** [comment]
Bonito is now using the latest pysam.
