### ISSUE TITLE
what's the GPU memory utilization rate? Does it depend on read length?

### ISSUE THREAD

**Issue by avilella** [nanoporetech/bonito#257]
what's the GPU memory utilization rate? Does it depend on read length?

**Comment by iiSeymour** [comment]
Hey @avilella - reads are broken up into fixed-size chunks _(i.e. 10,000 samples)_ and those chunks get stacked into a batch _(i.e. 512 chunks)_. Batches are sent to the GPU for calling, so no, for the most part the utilzation does not depend on the read length. If you are looking at fragments that are significantly shorter than the default chunksize this is where you would want to tune the parameters a little.

**Comment by avilella** [comment]
Ok, thanks. I've got a Linux machine with half a dozen Nvidia 4Gb RAM GPUs
connected via Thunderbolt 3, so I wonder if tweaking the parameters, those
would be able to run bonito or similar basecallers.

**Comment by iiSeymour** [comment]
I would bring down the chunksize to 4000 samples to handle 400bp and above. This will reduced the memory required but you will probably need to bring down the batchsize also to fit into 4GB _(the defaults are set in bonito to use ~10GB)_.

**Comment by avilella** [comment]
That's perfect, thank you. I think I can use the batch size to adjust the
basecalling of runs to our cluster of Nvidia cards with 4GB.

Does the software know how to queue tasks to different GPU node ids? E.g.
with a Linux machine where `nvidia-smi` returns the results below, would
the software be able to queue jobs to all 6 GPUs?

|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr.
ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute
M. |
|                               |                      |               MIG
M. |
|===============================+======================+======================|
|   0  NVIDIA T1000        Off  | 00000000:24:00.0 Off |
 N/A |
| 67%   83C    P0    N/A /  50W |   3910MiB /  4096MiB |     98%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA T1000        Off  | 00000000:25:00.0 Off |
 N/A |
| 46%   63C    P0    N/A /  50W |   3870MiB /  4096MiB |    100%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:29:00.0 Off |
 N/A |
| 50%   70C    P3    27W /  90W |   3858MiB /  4096MiB |      0%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:2A:00.0 Off |
 N/A |
| 29%   61C    P3    66W /  90W |   3864MiB /  4096MiB |     99%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA T1000        Off  | 00000000:2E:00.0 Off |
 N/A |
| 68%   84C    P0    N/A /  50W |   3866MiB /  4096MiB |     98%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA T1000        Off  | 00000000:2F:00.0 Off |
 N/A |
| 65%   82C    P0    N/A /  50W |   3866MiB /  4096MiB |     98%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
