### ISSUE TITLE
Test Data and Base Calling Accuracy 

### ISSUE THREAD

**Issue by liyewen521** [nanoporetech/bonito#258]
Hello, I have two questions about using bonito:

- How can I get the correct test data, since the model has different parameters, such as r10.4, r9.4.1, e8, and e8.1. I tried to use the data I can get, but the quality scores of the generated fastq files are very low. Can you provide me with a way to access the test data?

- How do I go about measuring the base calling accuracy? The method I am using is based on the quality score of the generated fastq files.

Thank you very much in advance for your help!

**Comment by davidnewman02** [comment]
For most basecalling tasks we recommend using Dorado: https://github.com/nanoporetech/dorado
This is the production basecaller for Oxford Nanopore data, while Bonito is a research tool intended for model training and development.

You are able to generate data through sequencing on Oxford Nanopore sequencer, additionally there are various public datasets which are available through the open-data-registry: https://labs.epi2me.io/dataindex/ and https://registry.opendata.aws/ont-open-data/ . 

To measure basecall accuracy you should compare the basecalled sequence to a known reference sequence the accuracy can be calculated based on the number of correct bases compared to the number of incorrect bases (substitutions/insertions/deletions). 

If you don't have a reference sequence available then you can estimate your accuracy from the q-scores emitted by the basecaller. These are available in the summary file that will be produced when you run `bonito basecaller`
