### ISSUE TITLE
Error while installing Bonito.

### ISSUE THREAD

**Issue by AzlanNI** [nanoporetech/bonito#261]
Hello everyone! 

I am currently trying to install bonito on my Mac and on the HPC of our University. 

If i try the Developer Quickstart way : 

$ git clone https://github.com/nanoporetech/bonito.git  # or fork first and clone that
$ cd bonito
$ python3 -m venv venv3
$ source venv3/bin/activate
(venv3) $ pip install --upgrade pip
(venv3) $ pip install -r requirements.txt
(venv3) $ python setup.py develop

On my Mac i get an Error while installing requirements.txt which looks like: 

Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
ERROR: Could not find a version that satisfies the requirement ont-koi==0.0.9 (from versions: none)
ERROR: No matching distribution found for ont-koi==0.0.9

Maybe someone has seen a similar Error and can help me out. 

Also if i try to use the PyPi Mirror of our HPC to install bonito i always get the Error : 

      ############################
      # Package would be ignored #
      ############################
      Python recognizes 'remora.trained_models' as an importable package, however it is
      included in the distribution as "data".
      This behavior is likely to change in future versions of setuptools (and
      therefore is considered deprecated).
  
      Please make sure that 'remora.trained_models' is included as a package by using
      setuptools' `packages` configuration field or the proper discovery methods
      (for example by using `find_namespace_packages(...)`/`find_namespace:`
      instead of `find_packages(...)`/`find:`).
  
      You can read more about "package discovery" and "data files" on setuptools
      documentation page.
  
  
  !!
  
    check.warn(importable)
  error: command 'icc' failed: No such file or directory
  [end of output]

I would appreciate some help! 

Kind regards,

Azlan

**Comment by jmbreda** [comment]
I have the same issue, any update on it?
