### ISSUE TITLE
wondering crf_beam package beam search code accessible or not

### ISSUE THREAD

**Issue by zlannnn** [nanoporetech/bonito#262]
Hi Dear
Thanks a lot for your excellent work.
Recently I am looking at the full CPU version at the OPENVINO branch.

I noticed it needs a different beam search for CRF but I can't find the crf_beam source code at the following address since it seems compiled already as a .so file:
https://github.com/dkurt/bonito/blob/210a5d2d58b28d36c0f97be32e687aa78b78285d/bonito/openvino/basecall.py#L2

I am quite curious about the process, wondering may I access the code before compiling to learn the difference.
Thanks a lot.

Regards

**Comment by davidnewman02** [comment]
The ont-koi implementation of beam_search is not publicly released, however you may be interested in the implementation in the fast-ctc-decode module: https://github.com/nanoporetech/fast-ctc-decode
