### ISSUE TITLE
Problem starting bonito after Download (missing mappy Module)

### ISSUE THREAD

**Issue by AzlanNI** [nanoporetech/bonito#267]
Hello, 

I have downloaded Bonito by using the pip install command. 

```
Looking in indexes: http://pypi.repo.test.hhu.de/simple/
Requirement already satisfied: ont-bonito in ./.local/lib/python3.7/site-packages (0.5.3)
Requirement already satisfied: mappy==2.24 in ./.local/lib/python3.6/site-packages (from ont-bonito) (2.24)
Requirement already satisfied: toml==0.10.2 in ./.local/lib/python3.7/site-packages (from ont-bonito) (0.10.2)
Requirement already satisfied: tqdm<5,>4 in ./.local/lib/python3.6/site-packages (from ont-bonito) (4.64.0)
Requirement already satisfied: scipy==1.7.3 in ./.local/lib/python3.7/site-packages (from ont-bonito) (1.7.3)
Requirement already satisfied: numpy~=1.21.5 in ./.local/lib/python3.7/site-packages (from ont-bonito) (1.21.6)
Collecting pysam==0.18.0
  Downloading http://pypi.repo.test.hhu.de/packages/b9/bc/2df0c67e2c2d6130b01fa0e4f8c137d5749bfb3d618d1c6a7dab450133aa/pysam-0.18.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (14.9 MB)
     |████████████████████████████████| 14.9 MB 86.8 MB/s 
Requirement already satisfied: parasail==1.2 in ./.local/lib/python3.7/site-packages (from ont-bonito) (1.2)
Requirement already satisfied: pandas<2,>1 in ./.local/lib/python3.7/site-packages (from ont-bonito) (1.3.5)
Requirement already satisfied: requests==2.25.1 in ./.local/lib/python3.7/site-packages (from ont-bonito) (2.25.1)
Requirement already satisfied: ont-koi==0.0.9 in ./.local/lib/python3.7/site-packages (from ont-bonito) (0.0.9)
Collecting onnxruntime==1.11.0
  Downloading http://pypi.repo.test.hhu.de/packages/54/63/d4d8e39ee760d1d7a838a3d37b94686f6f977042f08a7eec470aea4dc12a/onnxruntime-1.11.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
     |████████████████████████████████| 5.2 MB 96.1 MB/s 
Requirement already satisfied: ont-remora==1.1.0 in ./.local/lib/python3.6/site-packages (from ont-bonito) (1.1.0)
Collecting ont-fast5-api==3.3.0
  Downloading http://pypi.repo.test.hhu.de/packages/30/f7/6ba006930b05e2b1fcf6532acdf565d783b2ee2998db189abf0f64e0b233/ont_fast5_api-3.3.0-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 78.8 MB/s 
Requirement already satisfied: pod5-format==0.0.14 in ./.local/lib/python3.7/site-packages (from ont-bonito) (0.0.14)
Requirement already satisfied: pod5-format-tools==0.0.14 in ./.local/lib/python3.7/site-packages (from ont-bonito) (0.0.14)
Requirement already satisfied: fast-ctc-decode==0.3.2 in ./.local/lib/python3.7/site-packages (from ont-bonito) (0.3.2)
Requirement already satisfied: python-dateutil==2.8.2 in ./.local/lib/python3.7/site-packages (from ont-bonito) (2.8.2)
Collecting torch~=1.11
  Downloading http://pypi.repo.test.hhu.de/packages/94/32/96a0955e5d6ed8a837eda5ca095dd2694c4617cfa70ca599660cd5ff7447/torch-1.11.0-cp37-cp37m-manylinux1_x86_64.whl (750.6 MB)
     |████████████████████████████████| 750.6 MB 143.5 MB/s 
Requirement already satisfied: wheel in ./.local/lib/python3.7/site-packages (from parasail==1.2->ont-bonito) (0.37.1)
Requirement already satisfied: pytz>=2017.3 in ./.local/lib/python3.7/site-packages (from pandas<2,>1->ont-bonito) (2022.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (1.26.9)
Requirement already satisfied: idna<3,>=2.5 in ./.local/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in ./.local/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (2022.5.18.1)
Requirement already satisfied: cffi in ./.local/lib/python3.7/site-packages (from ont-koi==0.0.9->ont-bonito) (1.15.0)
Requirement already satisfied: protobuf in ./.local/lib/python3.6/site-packages (from onnxruntime==1.11.0->ont-bonito) (3.19.4)
Requirement already satisfied: flatbuffers in ./.local/lib/python3.6/site-packages (from onnxruntime==1.11.0->ont-bonito) (2.0)
Requirement already satisfied: thop in ./.local/lib/python3.6/site-packages (from ont-remora==1.1.0->ont-bonito) (0.0.31.post2005241907)
Requirement already satisfied: onnx in ./.local/lib/python3.6/site-packages (from ont-remora==1.1.0->ont-bonito) (1.11.0)
Requirement already satisfied: scikit-learn in ./.local/lib/python3.7/site-packages (from ont-remora==1.1.0->ont-bonito) (1.0.2)
Requirement already satisfied: tabulate in ./.local/lib/python3.6/site-packages (from ont-remora==1.1.0->ont-bonito) (0.8.9)
Requirement already satisfied: packaging in ./.local/lib/python3.6/site-packages (from ont-fast5-api==3.3.0->ont-bonito) (21.3)
Requirement already satisfied: h5py>=2.8 in ./.local/lib/python3.6/site-packages (from ont-fast5-api==3.3.0->ont-bonito) (3.1.0)
Requirement already satisfied: progressbar33>=2.3.1 in ./.local/lib/python3.6/site-packages (from ont-fast5-api==3.3.0->ont-bonito) (2.4)
Requirement already satisfied: more-itertools in ./.local/lib/python3.7/site-packages (from pod5-format==0.0.14->ont-bonito) (8.13.0)
Requirement already satisfied: pyarrow~=7.0.0 in ./.local/lib/python3.7/site-packages (from pod5-format==0.0.14->ont-bonito) (7.0.0)
Requirement already satisfied: iso8601 in ./.local/lib/python3.7/site-packages (from pod5-format==0.0.14->ont-bonito) (1.0.2)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.7/site-packages (from python-dateutil==2.8.2->ont-bonito) (1.16.0)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.6/site-packages (from torch~=1.11->ont-bonito) (4.1.1)
Requirement already satisfied: pycparser in ./.local/lib/python3.7/site-packages (from cffi->ont-koi==0.0.9->ont-bonito) (2.21)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.7/site-packages (from scikit-learn->ont-remora==1.1.0->ont-bonito) (3.1.0)
Requirement already satisfied: joblib>=0.11 in ./.local/lib/python3.7/site-packages (from scikit-learn->ont-remora==1.1.0->ont-bonito) (1.1.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.local/lib/python3.7/site-packages (from packaging->ont-fast5-api==3.3.0->ont-bonito) (3.0.9)
Requirement already satisfied: cached-property; python_version < "3.8" in ./.local/lib/python3.6/site-packages (from h5py>=2.8->ont-fast5-api==3.3.0->ont-bonito) (1.5.2)
Installing collected packages: pysam, onnxruntime, ont-fast5-api, torch
Successfully installed onnxruntime-1.11.0 ont-fast5-api-3.3.0 pysam-0.18.0 torch-1.11.0
```

Now i wanted to start working with it. But when i use the bonito command i always get the Error: 

```
Traceback (most recent call last):
  File "/home/azlan/.local/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')()
  File "/software/python/3.7.8/login/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/software/python/3.7.8/login/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/software/python/3.7.8/login/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/software/python/3.7.8/login/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/azlan/.local/lib/python3.7/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/home/azlan/.local/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 15, in <module>
    from bonito.aligner import align_map, Aligner
  File "/home/azlan/.local/lib/python3.7/site-packages/bonito/aligner.py", line 7, in <module>
    from mappy import Aligner, ThreadBuffer
ModuleNotFoundError: No module named 'mappy'
```

I tried installing mappy==2.24 by using pip install again but it says: 

```
Looking in indexes: http://pypi.repo.test.hhu.de/simple/
Requirement already satisfied: mappy==2.24 in ./.local/lib/python3.6/site-packages (2.24)
```

So i already have mappy installed. 

Maybe u know how to solve this Problem. Thank you very much. 

Kind regards,
Azlan

**Comment by iiSeymour** [comment]
Hey @AzlanNI I am seeing a mixed of `python3.6` and `python3.7` in your output and `python3.6` is end of life.

Are you able to create a new `python3.7` virtual environment and install bonito into that?

```
$ python3.7 -m venv venv3.7
$ source ./venv3.7/bin/activate
$ pip install --upgrade pip
$ pip install ont-bonito
```

**Comment by AzlanNI** [comment]
Hello @iiSeymour i now used a virtualenv in Python3.7.3 and downloaded ont-bonito per pip-install. 
After installing i still get the Error : 

(venv3.7) [azlan@hilbert50 ~]$ bonito
Traceback (most recent call last):
  File "/home/azlan/venv3.7/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')()
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 15, in <module>
    from bonito.aligner import align_map, Aligner
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/bonito/aligner.py", line 7, in <module>
    from mappy import Aligner, ThreadBuffer
ModuleNotFoundError: No module named 'mappy'

This ist the installation process if it helps: 

(venv3.7) [azlan@hilbert50 ~]$ PIP_CONFIG_FILE=/software/python/pip.conf pip install ont-bonito
Looking in indexes: http://pypi.repo.test.hhu.de/simple/
Requirement already satisfied: ont-bonito in ./venv3.7/lib/python3.7/site-packages (0.5.3)
Requirement already satisfied: mappy==2.24 in ./.local/lib/python3.6/site-packages (from ont-bonito) (2.24)
Requirement already satisfied: toml==0.10.2 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (0.10.2)
Requirement already satisfied: tqdm<5,>4 in ./.local/lib/python3.6/site-packages (from ont-bonito) (4.64.0)
Requirement already satisfied: scipy==1.7.3 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (1.7.3)
Requirement already satisfied: numpy~=1.21.5 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (1.21.6)
Collecting pysam==0.18.0
  Downloading http://pypi.repo.test.hhu.de/packages/b9/bc/2df0c67e2c2d6130b01fa0e4f8c137d5749bfb3d618d1c6a7dab450133aa/pysam-0.18.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (14.9 MB)
     |████████████████████████████████| 14.9 MB 59.0 MB/s 
Requirement already satisfied: parasail==1.2 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (1.2)
Requirement already satisfied: pandas<2,>1 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (1.3.5)
Requirement already satisfied: requests==2.25.1 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (2.25.1)
Requirement already satisfied: ont-koi==0.0.9 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (0.0.9)
Collecting onnxruntime==1.11.0
  Downloading http://pypi.repo.test.hhu.de/packages/54/63/d4d8e39ee760d1d7a838a3d37b94686f6f977042f08a7eec470aea4dc12a/onnxruntime-1.11.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
     |████████████████████████████████| 5.2 MB 66.5 MB/s 
Requirement already satisfied: ont-remora==1.1.0 in ./.local/lib/python3.6/site-packages (from ont-bonito) (1.1.0)
Collecting ont-fast5-api==3.3.0
  Downloading http://pypi.repo.test.hhu.de/packages/30/f7/6ba006930b05e2b1fcf6532acdf565d783b2ee2998db189abf0f64e0b233/ont_fast5_api-3.3.0-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 62.8 MB/s 
Requirement already satisfied: pod5-format==0.0.14 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (0.0.14)
Requirement already satisfied: pod5-format-tools==0.0.14 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (0.0.14)
Requirement already satisfied: fast-ctc-decode==0.3.2 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (0.3.2)
Requirement already satisfied: python-dateutil==2.8.2 in ./venv3.7/lib/python3.7/site-packages (from ont-bonito) (2.8.2)
Collecting torch~=1.11
  Downloading http://pypi.repo.test.hhu.de/packages/94/32/96a0955e5d6ed8a837eda5ca095dd2694c4617cfa70ca599660cd5ff7447/torch-1.11.0-cp37-cp37m-manylinux1_x86_64.whl (750.6 MB)
     |████████████████████████████████| 750.6 MB 75.3 MB/s 
Requirement already satisfied: wheel in ./venv3.7/lib/python3.7/site-packages (from parasail==1.2->ont-bonito) (0.37.1)
Requirement already satisfied: pytz>=2017.3 in ./venv3.7/lib/python3.7/site-packages (from pandas<2,>1->ont-bonito) (2022.1)
Requirement already satisfied: certifi>=2017.4.17 in ./venv3.7/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (2022.5.18.1)
Requirement already satisfied: idna<3,>=2.5 in ./venv3.7/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv3.7/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (1.26.9)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venv3.7/lib/python3.7/site-packages (from requests==2.25.1->ont-bonito) (4.0.0)
Requirement already satisfied: cffi in ./venv3.7/lib/python3.7/site-packages (from ont-koi==0.0.9->ont-bonito) (1.15.0)
Requirement already satisfied: flatbuffers in ./.local/lib/python3.6/site-packages (from onnxruntime==1.11.0->ont-bonito) (2.0)
Requirement already satisfied: protobuf in ./.local/lib/python3.6/site-packages (from onnxruntime==1.11.0->ont-bonito) (3.19.4)
Requirement already satisfied: tabulate in ./.local/lib/python3.6/site-packages (from ont-remora==1.1.0->ont-bonito) (0.8.9)
Requirement already satisfied: onnx in ./.local/lib/python3.6/site-packages (from ont-remora==1.1.0->ont-bonito) (1.11.0)
Requirement already satisfied: scikit-learn in ./venv3.7/lib/python3.7/site-packages (from ont-remora==1.1.0->ont-bonito) (1.0.2)
Requirement already satisfied: thop in ./.local/lib/python3.6/site-packages (from ont-remora==1.1.0->ont-bonito) (0.0.31.post2005241907)
Requirement already satisfied: h5py>=2.8 in ./.local/lib/python3.6/site-packages (from ont-fast5-api==3.3.0->ont-bonito) (3.1.0)
Requirement already satisfied: progressbar33>=2.3.1 in ./.local/lib/python3.6/site-packages (from ont-fast5-api==3.3.0->ont-bonito) (2.4)
Requirement already satisfied: packaging in ./.local/lib/python3.6/site-packages (from ont-fast5-api==3.3.0->ont-bonito) (21.3)
Requirement already satisfied: iso8601 in ./venv3.7/lib/python3.7/site-packages (from pod5-format==0.0.14->ont-bonito) (1.0.2)
Requirement already satisfied: pyarrow~=7.0.0 in ./venv3.7/lib/python3.7/site-packages (from pod5-format==0.0.14->ont-bonito) (7.0.0)
Requirement already satisfied: more-itertools in ./venv3.7/lib/python3.7/site-packages (from pod5-format==0.0.14->ont-bonito) (8.13.0)
Requirement already satisfied: six>=1.5 in ./venv3.7/lib/python3.7/site-packages (from python-dateutil==2.8.2->ont-bonito) (1.16.0)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.6/site-packages (from torch~=1.11->ont-bonito) (4.1.1)
Requirement already satisfied: pycparser in ./venv3.7/lib/python3.7/site-packages (from cffi->ont-koi==0.0.9->ont-bonito) (2.21)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./venv3.7/lib/python3.7/site-packages (from scikit-learn->ont-remora==1.1.0->ont-bonito) (3.1.0)
Requirement already satisfied: joblib>=0.11 in ./venv3.7/lib/python3.7/site-packages (from scikit-learn->ont-remora==1.1.0->ont-bonito) (1.1.0)
Requirement already satisfied: cached-property; python_version < "3.8" in ./.local/lib/python3.6/site-packages (from h5py>=2.8->ont-fast5-api==3.3.0->ont-bonito) (1.5.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./venv3.7/lib/python3.7/site-packages (from packaging->ont-fast5-api==3.3.0->ont-bonito) (3.0.9)
Installing collected packages: pysam, onnxruntime, ont-fast5-api, torch

It still shows Mappy as requirement already satisfied in 3.6 which is concerning i guess. 

The Error is the same as before : 

Traceback (most recent call last):
  File "/home/azlan/venv3.7/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')()
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 15, in <module>
    from bonito.aligner import align_map, Aligner
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/bonito/aligner.py", line 7, in <module>
    from mappy import Aligner, ThreadBuffer
ModuleNotFoundError: No module named 'mappy'

**Comment by iiSeymour** [comment]
Can you try..

```
(venv3.7) $ deactivate
$ rm -rf venv3.7
$ python3.7 -m venv venv3.7
$ source ./venv3.7/bin/activate
$ python3.7 -m pip install --upgrade pip
$ python3.7 -m pip install --no-cache-dir ont-bonito
```

**Comment by AzlanNI** [comment]
@iiSeymour  Thank you for ur quick response! 

I just tried ur suggestion and now i get a new Error trying to download ont-bonito: 

After i type the command python3.7 -m pip install --no-cache-dir ont-bonito in the venv i get the Error: 

PIP_CONFIG_FILE=/software/python/pip.conf python3.7 -m pip install --no-cache-dir ont bonito
Traceback (most recent call last):
  File "/software/python/3.7.8/login/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/software/python/3.7.8/login/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_internal/exceptions.py", line 14, in <module>
    from pip._vendor.rich.console import Console, ConsoleOptions, RenderResult
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 55, in <module>
    from .pretty import Pretty, is_expandable
  File "/home/azlan/venv3.7/lib/python3.7/site-packages/pip/_vendor/rich/pretty.py", line 398, in <module>
    @dataclass
  File "/home/azlan/.local/lib/python3.6/site-packages/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/home/azlan/.local/lib/python3.6/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/azlan/.local/lib/python3.6/site-packages/dataclasses.py", line 801, in _process_class
    for name, type in cls_annotations.items()]
  File "/home/azlan/.local/lib/python3.6/site-packages/dataclasses.py", line 801, in <listcomp>
    for name, type in cls_annotations.items()]
  File "/home/azlan/.local/lib/python3.6/site-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/home/azlan/.local/lib/python3.6/site-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'

A Error wit the package dataclasses. 

kind reagrds,

Azlan

**Comment by AzlanNI** [comment]
Alright i resolved the dataclasses problem since it is already implemented in Python3.7. 

But now i am getting a new Error trying to load bonito with the package bz2.py 

 File "/home/azlan/venvboni/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')()
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/azlan/venvboni/lib/python3.7/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/home/azlan/venvboni/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 17, in <module>
    from bonito.io import CTCWriter, Writer, biofmt
  File "/home/azlan/venvboni/lib/python3.7/site-packages/bonito/io.py", line 8, in <module>
    import pandas as pd
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/core/generic.py", line 122, in <module>
    from pandas.core.describe import describe_ndframe
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/core/describe.py", line 39, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import stringify_path
  File "/home/azlan/venvboni/lib/python3.7/site-packages/pandas/io/common.py", line 4, in <module>
    import bz2
  File "/software/python/3.7.8/login/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

But i dont find the bz2 Package on the Package site maybe it called differently ? 

Maybe it is beacause bz2 is not in the venvboni ? As the directory path is showing ? Just an Idea and Thanks a lot for ur help i will see to get to this Problem tomorrow again! And hopefully can resolve this problem with ur help! 

kind regards,

Azlan

**Comment by iiSeymour** [comment]
Where did you get this build of Python 3.7 from? It's missing `bz2` support - see https://stackoverflow.com/questions/12806122/missing-python-bz2-module

**Comment by davidnewman02** [comment]
Closing as inactive.
