### ISSUE TITLE
TypeError: Expected fp16 but received torch.float32

### ISSUE THREAD

**Issue by Saranya-nanobiophotonics-lab** [nanoporetech/bonito#269]
Hello,
I tried using Bonito for basecalling. Following command was used 
"bonito basecaller dna_r10.4_e8.1_sup@v3.4 test/fast5 > test/data.bam" 

OUTPUT
> reading fast5
> outputting unaligned bam
> loading model dna_r10.4_e8.1_sup@v3.4
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-7:                                  
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/saranya/.local/lib/python3.9/site-packages/bonito/multiprocessing.py", line 110, in run
    for item in self.iterator:
  File "/home/saranya/.local/lib/python3.9/site-packages/bonito/crf/basecall.py", line 69, in <genexpr>
    (read, compute_scores(model, batch, reverse=reverse)) for read, batch in batches
  File "/home/saranya/.local/lib/python3.9/site-packages/bonito/crf/basecall.py", line 37, in compute_scores
    sequence, qstring, moves = beam_search(
  File "/home/saranya/.local/lib/python3.9/site-packages/koi/decode.py", line 13, in beam_search
    raise TypeError('Expected fp16 but received %s' % scores.dtype)
TypeError: Expected fp16 but received torch.float32

I am getting the following error
"TypeError: Expected fp16 but received torch.float32".

Could you please help me

Saranya

**Comment by N0toriou5** [comment]
I had the same issue by running Bonito ona a NVIDIA GTX 1050 Ti 4 GB. Upgrading to a RTX 3080 10 GB just solved the issue.

**Comment by Saranya-nanobiophotonics-lab** [comment]
Ok @N0toriou5 .
I am using NVIDIA GTX 1050 Ti 4 GB.

**Comment by Saranya-nanobiophotonics-lab** [comment]
@iiSeymour 
could you please comment whether we can run BONITO using NVIDIA GTX 1050 Ti 4 GB.

**Comment by Saranya-nanobiophotonics-lab** [comment]
@iiSeymour 
Thanks for your response. 
Now we are using NVIDIA GeForce RTX 2070.
I was able to run the base calling successfully, but unable to train model. Please find the error message in the image attached.
![Screenshot 2022-06-27 at 10 43 07 AM](https://user-images.githubusercontent.com/97092812/176327100-5f30d7b2-0f6e-49b6-a702-3c151d7949be.png)

**Comment by davidnewman02** [comment]
Closing as inactive.
