### ISSUE TITLE
WSL2-Ubuntu Bonito train "RuntimeError: CUDA error: unknown error"

### ISSUE THREAD

**Issue by N0toriou5** [nanoporetech/bonito#270]
Does bonito train work on Windows 10 WSL2 Linux distros? Because i got the following error when trying to run the bonito train command `bonito train --epochs 1 --lr 5e-4 --pretrained dna_r10.4_e8.1_sup@v3.4 --batch 19 --directory ctc-data fine-tuned-model ` :

<img width="680" alt="example" src="https://user-images.githubusercontent.com/49403790/174047339-544bec9d-7cc6-4ca4-8c5f-52d520d767ec.PNG">

My config:

<img width="440" alt="example" src="https://user-images.githubusercontent.com/49403790/174047495-b8f2e83e-1838-4b1a-8258-45949292c21c.PNG">

My GPU: NVIDIA RTX 3080 10 GB
Bonito version: 0.5.3 installed through `pip install -f https://download.pytorch.org/whl/torch_stable.html ont-bonito-cuda113`

I saw many using WSL2 are experiencing the same issue (es. #249 , #233  )

**Comment by N0toriou5** [comment]
@vellamike @iiSeymour  could you please tell me if Bonito train can be run in WSL2? Has anyone managed to make it work on any WSL2 Linux distro?

**Comment by N0toriou5** [comment]
@vellamike Thank you! 
Unfortunately, I have no GPU on my Linux machine at the moment, unless I mount a dual boot on my Win pc.

**Comment by vellamike** [comment]
This may not be WSL related. Do you have a minimal dataset which would allow me to reproduce the error?

**Comment by vellamike** [comment]
Thanks @N0toriou5 - it seems like the CUDA error in WSL is not getting reported correctly as I suspect this would be an out of memory exception.

Closing this issue.
