### ISSUE TITLE
Issue: undefined symbol: host_run_lstm_fwd96

### ISSUE THREAD

**Issue by tamara-nano** [nanoporetech/bonito#273]
Hello, I'm trying to get bonito running but I'm getting following issue on an ubuntu machine.

Traceback (most recent call last):
  File "/root/miniconda3/envs/py37/bin/bonito", line 5, in <module>
    from bonito import main
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 17, in <module>
    from bonito.io import CTCWriter, Writer, biofmt
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/io.py", line 21, in <module>
    from bonito.util import mean_qscore_from_qstring
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/util.py", line 18, in <module>
    import koi.lstm
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/koi/lstm.py", line 3, in <module>
    from _runtime import lib
ImportError: /root/miniconda3/envs/py37/lib/python3.7/site-packages/_runtime.abi3.so: undefined symbol: host_run_lstm_fwd96

With recherche I did it might be an issue with gcc and that it can't call this shared library file but I'm stuck on how to resolve that (or if this is even the issue). 

Thank you very much in advance :)

**Comment by anddigital-jh** [comment]
> Hello, I'm trying to get bonito running but I'm getting following issue on an ubuntu machine.
> 
> Traceback (most recent call last): File "/root/miniconda3/envs/py37/bin/bonito", line 5, in from bonito import main File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/**init**.py", line 2, in from bonito.cli import basecaller, train, evaluate, view, convert, download, export File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 17, in from bonito.io import CTCWriter, Writer, biofmt File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/io.py", line 21, in from bonito.util import mean_qscore_from_qstring File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/bonito/util.py", line 18, in import koi.lstm File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/koi/lstm.py", line 3, in from _runtime import lib ImportError: /root/miniconda3/envs/py37/lib/python3.7/site-packages/_runtime.abi3.so: undefined symbol: host_run_lstm_fwd96
> 
> With recherche I did it might be an issue with gcc and that it can't call this shared library file but I'm stuck on how to resolve that (or if this is even the issue).
> 
> Thank you very much in advance :)

Try forcing version 0.5.1 for now and be sure to confirm that 0.5.1 installs correctly.

`pip install --force-reinstall ont-bonito==0.5.1`

**Comment by iiSeymour** [comment]
There was a problem with 3.7 koi wheel with is now fixed.
