### ISSUE TITLE
bonito uses similar amount of memory when using fast and sup model

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/bonito#277]
Hi, I've noticed that bonito uses similar amount of memory when loading fast (~2 GB) and sup (~2.2GB). Why is that?
I'd expect the vRAM to be much less used with fast model as it has only 0.5M parameters, while sup uses 27M parameters.

**Comment by vellamike** [comment]
Hi @lpryszcz  - For performance reasons Pytorch pre-caches GPU memory. This means that calculating how much memory Pytorch requires is not a simple calculation. More information can be found [here](https://blog.paperspace.com/pytorch-memory-multi-gpu-debugging/).

**Comment by lpryszcz** [comment]
thank you for the clarification @vellamike ! Enlightening read :)

**Comment by lpryszcz** [comment]
btw, I've noticed something strange while trying to "enable CPU-mode" myself - it seems both forward and backward is used by bonito model even when you do basecalling. Why is that? I though the backprop is used only for model training. 

```
class _LogZ(torch.autograd.Function):
    @staticmethod
    def forward(ctx, Ms, idx, v0, vT, S:semiring, K):
        idx = idx.to(device=Ms.device)
        logZ, Ms_grad = logZ_fwd_cu(Ms, idx, v0, vT, S, K)
        ctx.save_for_backward(Ms_grad, Ms, idx, vT)
        ctx.semiring = S
        ctx.K = K
        return logZ

    @staticmethod
    def backward(ctx, grad):
        Ms_grad, Ms, idx, vT = ctx.saved_tensors
        S, K = ctx.semiring, ctx.K
        T, N, C, NZ = Ms.shape
        betas = bwd_scores_cu_sparse(Ms, idx, vT, S, K=K)
        Ms_grad = S.mul(Ms_grad, betas[1:,:,:,None])
        Ms_grad = S.dsum(Ms_grad.reshape(T, N, -1), dim=2).reshape(T, N, C, NZ)
        return grad[None, :, None, None] * Ms_grad, None, None, None, None, None
```

**Comment by vellamike** [comment]
Hi @lpryszcz  - these functions re different and unrelated to backproagation. This is a variant of the [forward backward algorithm ](https://en.wikipedia.org/wiki/Forward–backward_algorithm) from hidden Markov models.
