### ISSUE TITLE
basecaller freezes with CUDA error

### ISSUE THREAD

**Issue by ADHDrian** [nanoporetech/bonito#281]
Dear all,

I trained a bonito model on RNA data and the validation numbers look fine. However, when I tried to run basecaller with this model on  fast5 files, it gives a whole bunch of error messages about empty sequences, and finally freezes on a CUDA memory error. Could somebody explain what the issue is?

Here is the command line:
> bonito basecaller \\
> pytorch_models/bonito/rna_r9.4 \\
> Data/nanopore/rna/debug/reads \\
> --device cuda:3 \\
> --verbose \\
> \> Data/nanopore/rna/debug/basecalls/basecalls.fastq

And below are the error messages:
> reading fast5
> outputting unaligned fastq
> loading model /home/achan/pytorch_models/bonito/rna_r9.4
> model basecaller params: {'chunksize': 4000, 'overlap': 500, 'batchsize': 64, 'quantize': None}
> calling: 0 reads [00:00, ? reads/s]> skipping empty sequence 000c37d7-9bba-40fa-bf57-7cdb732e1ea2
> calling: 1 reads [00:01,  1.41s/ reads]> skipping empty sequence 00199d2f-ce37-4f66-9113-e087be0b0cd3
> skipping empty sequence 001d23ae-9d1d-4a1a-9c9a-f697038bd0b4
> skipping empty sequence 0026fef1-2e30-4c58-a089-be89afa67237
> calling: 4 reads [00:01,  3.23 reads/s]> skipping empty sequence 00388a5f-e6f2-475d-a7c4-84c0fd5a06a6
> skipping empty sequence 003a5d54-f029-4f8c-8124-cac0e4d19f51
> skipping empty sequence 00420eb2-bb4e-4bb1-b896-12c5764c7e70
> skipping empty sequence 004f1b34-8c28-42ec-a5e6-19ff587fea0f
> skipping empty sequence 0052d71b-1cc3-47ff-9971-f414aa09d53b
> skipping empty sequence 0054f571-94ec-4b70-b49a-37521734ee85
> calling: 10 reads [00:01,  8.84 reads/s]> skipping empty sequence 0062f98b-1c8d-444f-8da0-948c2aae4389
...
> calling: 1435 reads [00:44, 45.88 reads/s]> skipping empty sequence 5d506f1d-5fc2-46a0-bb9f-f38bbaf8fff4
> skipping empty sequence 5d7e727e-7187-448d-87c9-39e95b4b3ac5
> skipping empty sequence 5d815f2e-be1c-4b52-ab42-4e81591601a7
> skipping empty sequence 5d9f7d00-aea4-48d4-8eda-3c4d0e3e84d5
> skipping empty sequence 5da670da-1ad4-4d2e-8561-67a8f25fd86c
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/achan/miniconda3/envs/bonito/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/achan/miniconda3/envs/bonito/lib/python3.9/site-packages/bonito/multiprocessing.py", line 110, in run
    for item in self.iterator:
  File "/home/achan/miniconda3/envs/bonito/lib/python3.9/site-packages/bonito/crf/basecall.py", line 69, in <genexpr>
    (read, compute_scores(model, batch, reverse=reverse)) for read, batch in batches
  File "/home/achan/miniconda3/envs/bonito/lib/python3.9/site-packages/bonito/crf/basecall.py", line 37, in compute_scores
    sequence, qstring, moves = beam_search(
  File "/home/achan/miniconda3/envs/bonito/lib/python3.9/site-packages/koi/decode.py", line 58, in beam_search
    moves_ = moves.data.reshape(N, -1).cpu()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> calling: 1435 reads [00:59, 45.88 reads/s]

(freezes from this point)

Thank you very much for your help!

**Comment by ADHDrian** [comment]
Hi @iiSeymour ,

The sequences (as called by guppy) can range from 50 to 4000 in length. Is this supposed to be a problem? Even when the batchsize is reduced to 1, the same problem persists.

**Comment by iiSeymour** [comment]
Can you try reducing the chunksize instead of the batchsize. Try with `--chunksize 1000 --overlap 200`.

**Comment by ADHDrian** [comment]
Thanks @iiSeymour  for your answer.
I tried your suggestion but it gave the same error...
While debugging, I noticed that the model is outputting only 0 labels. However, during training, the loss and validation values all looked okay. Does that mean that the npy chunks for training and validation are normalized differently from the fast5 data?

**Comment by davidnewman02** [comment]
Closing as inactive.
If you are still having difficulties with this data on recent projects, please raise a new ticket and we can assist.
