### ISSUE TITLE
How long would it take to convert downloaded dna_r9.4.1.hdf5 training dataset in Tesla V100?

### ISSUE THREAD

**Issue by Saranya-nanobiophotonics-lab** [nanoporetech/bonito#285]
Hi @iiSeymour 
We are using Tesla V100. We have used the "bonito download --training" to download bonito training dataset. It showed around 12Gb. 
Now, it is more than 17 hrs since we started the download. It shows "converting dna_r9.4.1.hdf5". How long would this take ? 
We want to check whether there is any issue from our end as it is taking so long.

![Untitled presentation](https://user-images.githubusercontent.com/97092812/179448309-08178a6b-4425-4b84-b292-f8c889eedb07.jpg)

Saranya

**Comment by Prithvi-Velicheti** [comment]
same issue for me. convert taking forever and automatically getting killed.
![bonitoconvert](https://user-images.githubusercontent.com/25413124/187822127-9e62ccee-f7c0-4ea5-ba2c-1c3bfd1b76b9.png)

**Comment by davidnewman02** [comment]
Closing as HDF training dataset format is no longer supported
