### ISSUE TITLE
Accuracy inconsitency is observed

### ISSUE THREAD

**Issue by waka45** [nanoporetech/bonito#286]
Hi,

We bought the ONT nanopore sequencing machine MinION, and tested using fix-length library (e.g. Eco.li). A confusing result was observed during the sequencing, we found a significant drop of accuracy from about 97% to 80%. in the same channel. Do you have any idea on it? I attached the figure of accuracy vs read (sort by time) below for your information.

![image](https://user-images.githubusercontent.com/35132294/179498076-be5f1e1a-913e-47a0-83f9-378ab9ba0464.png)

Thanks very much!

**Comment by waka45** [comment]
Hi @iiSeymour, please see pic below, seems the accuracy difference could be attributed to mux switch.. 

Why this happend and what setting I can use to make sure that swithch of mux won't decrease my accuracy? Beside, the accuracy drop after mux switch is not occasional. I use kit12, R10.4.1 and MinION. 

Thanks and look forward to your reply.

![image](https://user-images.githubusercontent.com/35132294/180127197-086398e3-f1d0-4368-9804-a2008f506fdb.png)

**Comment by davidnewman02** [comment]
Closing as inactive.
It seems like you were getting poor accuracy from mux=2 in your data. You will be able to get better support for this through the customer support channels and ONT-community.
