### ISSUE TITLE
Installing bonito on mac

### ISSUE THREAD

**Issue by rckeerthivasan** [nanoporetech/bonito#288]
Hi, 

I have been going through the posted issues (both open and closed). I have understood that I cannot install bonito on macOS because CUDA packages aren't available. But if I am installing the CPU-only version by dkurt and commenting out CUDA requirements in the requirements.txt, would be there any problems in installing and running on macOS?

Otherwise, are there are shortcuts to install bonito on macOS?

Thank you for help and time, 
Ken.

**Comment by vellamike** [comment]
This is not something we have tried so YMMV. However even if it works it will be rather slow on a CPU, especially a low core count device like a MacBook.

**Comment by iiSeymour** [comment]
@rckeerthivasan please see dorado for this https://github.com/nanoporetech/dorado
