### ISSUE TITLE
bonito speed question

### ISSUE THREAD

**Issue by jagos01** [nanoporetech/bonito#29]
Hello,
I have installed bonito v0.1.2 and re-basecalled a data set (114 multi fast5 files).  With guppy v3.4.4 basecalling took ~2.5hrs while bonito took ~19hrs.  The bonito command was as follows:   

 bonito basecaller --device cuda:0 --half /home/scott/bonito/lib/python3.6/site-packages/bonito/models/dna_r9.4.1 /home/scott/Data/BaS_P0253Lux_4B_SpoIIA_1Ar/BaS_Lux/20190516_2124_MN26548_FAK49745_133fa243/fast5_pass > /home/scott/Data/BaS_P0253Lux_4B_SpoIIA_1Ar/BaS_Lux/20190516_2124_MN26548_FAK49745_133fa243/Bonito_basecalled/BaS_P0253Lux-4B_SpoIIA-1Ar_Bonito2_GPU.fasta

I am running ubuntu 18.04 with a Quadro RTX 5000 GPU.  Are there options that can be changed to increase the speed of basecalling?
Thanks,
Scott

**Comment by iiSeymour** [comment]
Hey Scott,

Thanks for trying out Bonito. The speed difference is expected as Bonito is still a research project in Python and Guppy is heavily optimized in C++/Cuda. One of the [bottlenecks is known](https://github.com/pytorch/pytorch/issues/18631) in PyTorch already and I'm exploring options for faster runtime.

Chris.

**Comment by jagos01** [comment]
Hello Chris,
Thanks for the quick response.  I look forward to future releases.
Scott
