### ISSUE TITLE
Hope to obtain a well-trained Bonito. CTC model weight

### ISSUE THREAD

**Issue by wangziyuan66** [nanoporetech/bonito#293]
When I use `bonito download --models`

In config.tmol, it used "bonito.crf" model. Considering I would like to develop incremental learning based on ctc model, I need a pretrained weight. We would appreciate it if you could provide it.

Thanks.

**Comment by iiSeymour** [comment]
Sure, here is the last CTC model release: [dna_r9.4.1@v2](
https://nanoporetech.box.com/shared/static/nas0uhf46fd1lh2jndhx2a54a9vvhxp4.zip).
