### ISSUE TITLE
Error in output file

### ISSUE THREAD

**Issue by rlowe-altoslas** [nanoporetech/bonito#295]
Running the following

```
bonito basecaller dna_r10.4_e8.1_sup@v3.4 $input_path --modified-bases 5mC 5hmC --reference $reference > basecalls_with_mods.sam 
```

This is producing output with

```
[downloaded dna_r10.4_e8.1_sup@v3.4.zip]
```

attached to the top of the file. This is also causing issue with BAM files as well. This obviously makes invalid files that don't work in other tools. 

I think the offending line is here: https://github.com/nanoporetech/bonito/blob/f0827d931df550eded9d87744df62ba718db9af6/bonito/cli/download.py#L62

**Comment by iiSeymour** [comment]
Thanks @rlowe-altoslas this is fixed on master - see https://github.com/nanoporetech/bonito/issues/274.
