### ISSUE TITLE
Help us on Bonito expected run time

### ISSUE THREAD

**Issue by Saranya-nanobiophotonics-lab** [nanoporetech/bonito#296]
Hi @iiSeymour 
We are using NVIDIA V100 GPU.
We have created an virtual environment to run bonito. For test training run, we have used a fast 5 file of size 152MB (corresponding to ~2750reads). 
We used the following command
"bonito basecaller dna_r10.4_e8.1_hac@v3.4 --save-ctc --reference ref.mmi fast5_sub >  ctc-data/basecalls.sam"
The code is running for over 24 hrs with 0% preprocessing of reads. 
PFA and please comment.

![image](https://user-images.githubusercontent.com/97092812/182526653-e4eeb3e3-4e70-42d5-a816-8cba393a9fc3.png)

**Comment by Saranya-nanobiophotonics-lab** [comment]
Could someone please comment on this issue.

**Comment by iiSeymour** [comment]
Hi @Saranya-nanobiophotonics-lab this looks like it's stalled with an I/O issue and not specifically a bonito error. 

Is your data on a local disk or a network drive here?

**Comment by Saranya-nanobiophotonics-lab** [comment]
Hi @iiSeymour 
The data is in local disk. I had successfully base-called and performed model training. Further, I tried base-calling using the new model. But, I get poly G as data output.
