### ISSUE TITLE
Much lower reads quality than Guppy

### ISSUE THREAD

**Issue by yanchunzhang** [nanoporetech/bonito#297]
Hi,
I run bonito with 9.4.1_sup model on a R9 datasets while got really low reads quality(median 5) than I got from guppy (median 10). 
Is there anything wrong with the 9.4.1 model?

Thanks,
Yanchun

**Comment by iiSeymour** [comment]
Hi @yanchunzhang 

What is the typical read length in your dataset?

**Comment by CWYuan08** [comment]
@yanchunzhang @iiSeymour hi I am having the exact same issue here, it got reduced from above 10 to around 5. My median read length is ~550, N50=730. I also tried to train my own bonito model, it still remains the same. Do you have any thoughts on this? Thank you very much!

**Comment by CWYuan08** [comment]
@yanchunzhang @iiSeymour hi I am having the exact same issue here, it got reduced from above 10 to around 5. My median read length is ~550, N50=730. I also tried to train my own bonito model, it still remains the same. Do you have any thoughts on this? Thank you very much!

**Comment by davidnewman02** [comment]
Closing as inactive. 
There have been several releases of bonito since this issue was raised. If you are still finding issues with basecall quality on the latest version of bonito then please raise a new issue.
