### ISSUE TITLE
ont-bonito-cuda111 5.1 install rather than 5.3

### ISSUE THREAD

**Issue by rob234king** [nanoporetech/bonito#299]
pip install -f https://download.pytorch.org/whl/torch_stable.html ont-bonito-cuda111
results in 5.1 rather than 5.3 with latest models? Can the cuda 11 install be updated please

**Comment by iiSeymour** [comment]
Hi @rob234king 

I've just released v0.6 which resolves this https://github.com/nanoporetech/bonito/releases/tag/v0.6.0

Please see the `Installation` section at the end of the release as `ont-bonito-cuda111`, `ont-bonito-cuda113` are deprecated and only `ont-bonito` is required now.
