### ISSUE TITLE
Scrappie squiggle prediction feature in bonito 

### ISSUE THREAD

**Issue by nguyennhuttin** [nanoporetech/bonito#300]
I have a question about Scrappies [https://github.com/nanoporetech/scrappie] - that is now deprecated
Why is it discontinued? In Scrappies there is a function called predict squiggle which takes in DNA sequence and generated properties of the squiggle. We can then use it to generate lots of examples. I no longer find this function in any implementation (other open sources and bonito) - why? How do I reliably continue to do this generating squiggles, now that Scrappies is discontinued, any other way ? Is generated squiggle from Scrappie not recommended?

**Comment by hasindu2008** [comment]
For a similar task, I recently isolated the event segmentation from scrappie and reimplemented it along with some other functions such as synthetic reference creation here https://github.com/hasindu2008/sigtk. You can check out the repo and see if it is releavent.

**Comment by nguyennhuttin** [comment]
Thanks a lot for sharing @hasindu2008, can I ask you about the event segmentation from scrappie you implemented - what's algorithm is it, can you direct me to any material to understand it, 
I don't think you have the predict squiggle function I am looking for . This function takes in a sequence of bases and output segment properties of each base ( mean, time, variation). Event segmentation takes in raw signal and output properties. Correct me if I am wrong.  
Any help with understanding the predict squiggle function, how it works is appreciated

**Comment by hasindu2008** [comment]
Could you open an issue in sigtk repo please?
