### ISSUE TITLE
Bonito to infer 5mC in all contexts

### ISSUE THREAD

**Issue by AlineMuyle** [nanoporetech/bonito#301]
Dear developers,
I was advised to use Bonito with Remora's latest all context model to infer 5mC in CG, CHG and CHH contexts.
I just wanted to make sure I am using the correct command line:

bonito basecaller dna_r10.4.1_e8.2_sup@v3.5.1 fast5/ --modified-bases 5mC --reference scaffolds.fasta --modified-base-model 5mC_all_context_sup_r1041_e82 > basecalls_with_mods.bam

Also, is there a way to output a bedmethyl file modified_bases.5mC.bed like megalodon does? Or is there a way to convert the basecalls_with_mods.bam into a bedmethyl file?

Thank you for your help

**Comment by cdebuck** [comment]
Hi @AlineMuyle, I've have also been working with remora data, and I found the modbam2bed module useful (https://github.com/epi2me-labs/modbam2bed), hope this helps you too.

**Comment by AlineMuyle** [comment]
Great thanks!

**Comment by iiSeymour** [comment]
Thanks @cdebuck
