### ISSUE TITLE
bonito for 10.4.1 5mC methylation

### ISSUE THREAD

**Issue by jcolicchio-soundag** [nanoporetech/bonito#303]
When trying to run bonito to identify methylation, we are getting an issue with 3.5.2. It seems that it cannot identify the correct remora model, perhaps, since it (5mC_all_context_sup_r1041_e82 ) is a rerio model, it is not able to find it?

bonito basecaller dna_r10.4.1_e8.2_400bps_sup@v3.5.2 /mnt/NAS2/test/fast5_pass/ --modified-bases 5mC --reference test.mmi --modified-base-model 5mC_all_context_sup_r1041_e82 > basecalls_with_mods.bam

The error I am getting is: remora.RemoraError: No trained Remora models for dna_r10.4.1_e8.2_400bps. Options: dna_r9.4.1_e8, dna_r9.4.1_e8.1, dna_r10.4_e8.1, dna_r10.4.1_e8.2

**Comment by marcus1487** [comment]
Answered in remora repo. https://github.com/nanoporetech/remora/issues/31#issuecomment-1240051393
