### ISSUE TITLE
Relax requests version requirement?

### ISSUE THREAD

**Issue by godotgildor** [nanoporetech/bonito#305]
Currently requests is pegged to `==2.25.1`. I'm hoping it might be possible to relax this, preferably to `>=2.25.1`, but if that's not possible, at least a little more flexibility would be nice. 

https://github.com/nanoporetech/bonito/blob/99a17123122754db23f858b92139770869ac3fdd/requirements.txt#L10

The requests package is incredibly popular and so it's easy to come into conflicts with other packages, especially when the version is strict.

**Comment by davidnewman02** [comment]
Closed as resovled
