### ISSUE TITLE
Question about data formatting

### ISSUE THREAD

**Issue by dberma15** [nanoporetech/bonito#307]
Hi,

I'm a bit confused about the data generation. Could you describe what the fields "Dacs" and "Ref_to_signal" are and how they are derived. I believe Dacs is the signal, which would make sense given the length relative to reference, but I'm not sure what or how "Ref_to_signal" is obtained.

Thanks

**Comment by davidnewman02** [comment]
The DACs are the raw signal values (which are often provided in a normalised form) and the ref_to_signal provides a mapping of the signal to the target reference which the model uses when calculating it's CTC-loss.
