### ISSUE TITLE
AMD GPU rocm support for running CRF models

### ISSUE THREAD

**Issue by singagan** [nanoporetech/bonito#314]
Hi, 
I am trying to run CRF models on AMD GPUs. 
However, I get the following error from `beam_search` module

`ERROR: CUDA driver version is insufficient for CUDA runtime version`

Is there a rocm version for the beam_search module that I could use?

Thanks!

**Comment by arkhodamoradi** [comment]
+1 

I also like to have ROCm support for this function. I also volunteer to help hipify the code :)

The ont-koi beam search returns 3 tensors which is different from other open-source beam search functions.
https://github.com/nanoporetech/bonito/blob/master/bonito/crf/basecall.py#L7

your help is appreciated 

@marcus1487 @iiSeymour

**Comment by vellamike** [comment]
We haven't added any HIP support but this is possible in principle.

@arkhodamoradi could you write to me? mike dot vella at nanoporetech dot com
