### ISSUE TITLE
Bam file created by Bonito contains only primary alignments

### ISSUE THREAD

**Issue by caspargross** [nanoporetech/bonito#318]
We try to use Bam files with included modifications as replacement for "normal" bams in our analysis pipeline.
Bams produced by Bonito do not include supplementary alignments. This makes for example SV calling impossible since we cannot identify BNDs. 

Is there an option to include non primary alignments in the output?

Thanks, Caspar

**Comment by HeleneKretzmer** [comment]
I would like to push this one up - I have a similar question: Reads are soft-clipped and aligned to only one region and the soft-clipped parts are not aligned elsewhere, right? For breakpoint detection for example it would be great to allow for these kinds of alignments too.
Thanks,
Helene

**Comment by sklages** [comment]
I thought I could easily direct `bonito` to keep up to three supplementary alignments by setting `best_n=3` (def:1, actual `minimap2` default:5) in `bonito/cli/basecaller.py`, around line 84:
```python
aligner = Aligner(args.reference, preset='map-ont', best_n=3)
```
... but it didn't make the trick.

So still I'd prefer sth like `--secondary-alignments` but how can I achieve this meanwhile? Which part of the code did I miss?

**Comment by sklages** [comment]
@caspargross - have you found a workaround for that?

**Comment by caspargross** [comment]
@sklages not yet, I think about migrating to megalodon since that seems to be the main development focus of ONT.

**Comment by sklages** [comment]
> @sklages not yet, I think about migrating to megalodon since that seems to be the main development focus of ONT.

AFAIK megalodon is not further developed. See e.g. https://github.com/nanoporetech/megalodon/issues/328#issuecomment-1297105045

One could separate the basecalling/mod step (GPU space) from alignment (CPU space) though to gain more flexibility for mapping ..

**Comment by iiSeymour** [comment]
Dorado v0.3.0 added aligned output support and provides primary, secondary and supplementary alignments.
