### ISSUE TITLE
Run bonito on Jetson AGX Orin

### ISSUE THREAD

**Issue by liyewen521** [nanoporetech/bonito#319]
Hello, I tried to run bonito on Jetson AGX Orin. When I installed the requirements-cuda113.txt, I faced the following errors.

```bash
pip install -r requirements-cuda113.txt

ERROR: Could not find a version that satisfies the requirement ont-koi==0.0.8 (from versions: none)
ERROR: No matching distribution found for ont-koi==0.0.8

ERROR: Could not find a version that satisfies the requirement fast-ctc-decode==0.3.2 (from versions: none)
ERROR: No matching distribution found for fast-ctc-decode==0.3.2
```

My python version is 3.8.10, and my CUDA version is 11.4.

Can you provide some help for me, such as giving me a wheel?

**Comment by iiSeymour** [comment]
See [dorado-0.3.0-linux-arm64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.3.0-linux-arm64.tar.gz) for basecalling on Jetson AGX Orin.
