### ISSUE TITLE
Some help on parameters "beamsize" and "weights"

### ISSUE THREAD

**Issue by ms-gx** [nanoporetech/bonito#32]
What do the parameters `beamsize` and `weights` from bonito basecaller do?

Do you have a quick description? Or were do I find info?

What values can they have?

**Comment by iiSeymour** [comment]
The `beamsize` parameter is used for the [beam search decoder](https://towardsdatascience.com/beam-search-decoding-in-ctc-trained-neural-networks-5a889a3d85a7) and you can find the implmention [here](https://github.com/nanoporetech/fast-ctc-decode). The beamsize takes integer values starting at 1 *(an argmax decoder will be used if 1 is selected)*. 

During model training a set of network weights are serialised to disk after every epoch. By default the latest set of weights will be loaded from the model directory, the `weights` parameter lets you specifiy a particular epoch to load. Valid values are from 1 up to the number of epochs in the training directory.

**Comment by ms-gx** [comment]
Awesome, thx! Will look into it.
