### ISSUE TITLE
GPU memory requirement for remora basecalling 

### ISSUE THREAD

**Issue by Li-Yuanshuo** [nanoporetech/bonito#320]
I understand that the requirement for GPU memory is different for different models, batchsize, and chunksize. For example, the GPU memory for default (batchsize 128 & chunksize 10000) is 10.5Gb. The basecalling speed will not be faster even with more GPU memory. 

Does that mean for larger GPU memory, I could set a larger batchsize and chunksize and allow a faster basecalling? For a given GPU memory (32Gb for instance), how should I set these parameters to basecall with the highest efficiency?  

Thank you very much and look forward to your reply!

**Comment by iiSeymour** [comment]
For highest efficiency of modbase calling please use dorado https://github.com/nanoporetech/dorado
