### ISSUE TITLE
Bonito basecalled reads do not map

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/bonito#321]
Hi,

I have been using Bonito (0.5.1) and Guppy (6.3.8) to basecall some SARS-CoV-2 data. Out of the 20k, reads only ~5000 maps (Minimap2) to the reference when basecalled using Bonito, where almost all reads get mapped  (Minimap2) when basecalled using Guppy. 

Commands used were:
_bonito basecaller --batchsize 200 -v dna_r9.4.1_e8.1_sup@v3.3 test-covid-fast5/ --device cuda > a.fastq
guppy_basecaller -c dna_r9.4.1_e8.1_sup.cfg  -i test-covid-fast5/  -s aaa/   -x cuda:all_

The fast5 dataset can be downloaded below for investigation.
https://www.dropbox.com/s/10r43g1ussjbsrz/cov-test.tgz?dl=0

**Comment by iiSeymour** [comment]
This was a short-read issue for bonito but has been fixed since v0.5.3.
