### ISSUE TITLE
basecalling speed with bonito

### ISSUE THREAD

**Issue by yusmiatiliau** [nanoporetech/bonito#322]
Hello,

I'm running a bonito job with these parameters:
#SBATCH --gpus-per-node=A100:1
#SBATCH --mem=24G
#SBATCH --cpus-per-task=4

bonito basecaller dna_r10.4.1_e8.2_400bps_sup@v3.5.2 /path/fast5_pass/ \
--reference /path/REF.mmi \
--modified-base-model /path/5mC_all_context_sup_r1041_e82.onnx > /path/file_mods.bam

This is a read from Promethion, and the fast5 directory is ~400Gb. So far, it's been running for 48 hours, and only calling ~8% of the reads. Does this seems like the expected speed, or is there anything I did wrong and can change to speed up?

Thanks in advance

**Comment by sklages** [comment]
Are you working with the A100 "as is" or are you using the A100's new Multi-Instance GPU (MIG) feature?
We saw a quite drastic slowdown (appr 4-fold) when using MIG with A100 (NVIDIA A100-PCIE-40GB) ...

E.g. a large dataset (1.1T fast5) with HAC, without alignment: 
it took ~105h for bonito to finish on a 10G partition (batchsize=500), compared to ~26h on an unpartitioned A100 (same batchsize, so same GPU memory consumption).

**Comment by yusmiatiliau** [comment]
Hi @sklages, thank you for your response. I checked with the support person for the HPC we used, who confirmed that I ran on proper A100, and not MIG.
It took me ~29 days to finish. Maybe it is due to the SUP combined with All-context-mod-base calling, and alignment that contribute to the slowness. I would be interested on ways to speed up if possible.

**Comment by iiSeymour** [comment]
@yusmiatiliau dorado on A100 with modbase calling + alignment will be *significantly* faster with dorado - https://github.com/nanoporetech/dorado
