### ISSUE TITLE
Unable to install ont-koi

### ISSUE THREAD

**Issue by samhimes92** [nanoporetech/bonito#323]
I get the following message when trying to install the requirements under developer quick start, (on a mac)

`ERROR: Could not find a version that satisfies the requirement ont-koi (from versions: none)
ERROR: No matching distribution found for ont-koi`

My python version is `Python 3.9.7`
and my pip version is `pip 22.3.1`

I've tried installing it on its own with `install ont-koi`
and `pip install ont-koi==0.1.4`
Each gives the same error message. 

Any tips would be greatly appreciated!

**Comment by ValentinaPeona** [comment]
I do have the same problem, did you solve it?

**Comment by charlottewright** [comment]
I also have the exact same problem! I'd be keen to hear if you find a solution.

**Comment by ValentinaPeona** [comment]
Hi Charlotte!

In the end I "solved" the problem by installing bonito in this way:

```
# code from https://hackmd.io/@aksti/HyOfpv9K7#Install-bonito-via-miniconda

## Install bonito via conda
conda create -n bonito python=3.8
conda activate bonito
pip install ont-bonito
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
pip install numpy==1.21.6

## Models
bonito download --models
```

In this way I got it installed but I haven't tested it much further.

**Comment by natapol** [comment]
Thank you so much for the instruction.

I followed the instruction then it installed bonito version 0.1.5, which is the old one.

**Comment by iiSeymour** [comment]
Bonito is not support on Mac - please use dorado instead https://github.com/nanoporetech/dorado
