### ISSUE TITLE
Clarification on the provided training data

### ISSUE THREAD

**Issue by newalexander** [nanoporetech/bonito#329]
Hello all, and thanks for this tool.

I am wondering if there are details available on the training data downloadable with `bonito download --training`. For example, is it derived from a public dataset? What if any additional preprocessing was performed on it.

Thank you!

**Comment by william-simon** [comment]
I too would be interested in knowing this. Would be nice to give more details than "training and validation data was downloaded from the bonito repository" when reporting on research.

**Comment by davidnewman02** [comment]
The training data in the repository has now been updated to include r10.4.1 data.
The data provided is primarily intended to serve as an example for how to prepare data for use in bonito training, it is insufficient for training large models and you will need to supplement it with your own data if you wish to train further.
