### ISSUE TITLE
Issue with bonito export --format dorado (v0.6.2)

### ISSUE THREAD

**Issue by touala** [nanoporetech/bonito#331]
Hello,

I don't think that `bonito export --format dorado` is functional in the current version (v0.6.2).  [save_tensor](https://github.com/nanoporetech/bonito/blob/23820924eee16d4a07691c97b27ff71b7462d38f/bonito/cli/export.py#L54) function expect a directory but is given (in my case) a path to a `weights_1.tar` file. `args.model` can be replace by `os.path.dirname(model_file)` but this is not a clean solution as users have no control on output directory.

Alan

**Comment by davidnewman02** [comment]
This should be resolved in the latest version of bonito which includes `bonito export {input_dir} --output {output_dir}`
