### ISSUE TITLE
can't locate attribute: 'sample_id'

### ISSUE THREAD

**Issue by NiteshCCMB** [nanoporetech/bonito#334]
Hi, 
I am trying to do basecalling using Bonito on the nanopore-wgs-consortium NA12878 dataset. But I am getting the **can't locate attribute: 'sample_id' error**. Is there something I can do to make it work or to debug the issue.

**Comment by onkar2470** [comment]
Hi Sachin,
Yes, we were able to solve the issue. We have written a Python script which adds sample_id information to older fast5 files.
The script is publically available on GitHub:
https://github.com/SowpatiLab/ONT_scripts

**Comment by sachingadakh** [comment]
Thank you so much Onkar.
