### ISSUE TITLE
bonito export

### ISSUE THREAD

**Issue by fergsc** [nanoporetech/bonito#346]
Hi,
I have used bonito to train a model and have exported it for use in guppy. For my model cfg file I have modified dna_r10.4.1_e8.2_400bps_sup.cfg, pointing it to my jsn file. Is this the correctcfg file to use?

`bonito export --format guppy --config basecalls/config.toml basecalls/weights_20.tar > myModel.jsn`

When I try to use my model in guppy I get this error `[guppy/error] main: Layer type 'GlobalNormTransducer' must not be last layer.`

Bonito version = 0.7.0 
Guppy = 6.4.6

Thanks.

**Comment by iiSeymour** [comment]
@fergsc is this model a custom design of your own?

**Comment by fergsc** [comment]
It was producded from bonito with 3 data subsets, 2 using --pretrained

**Comment by fergsc** [comment]
If I try to export as dorado `bonito export --format dorado --config basecalls/config.toml basecalls/weights_20.tar > dodaro.jsn`

I get this error

`Traceback (most recent call last):
  File "/bonito-0.7.0/venv3/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.7.0', 'console_scripts', 'bonito')()
  File "/bonito-0.7.0/venv3/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/bonito-0.7.0/venv3/lib/python3.8/site-packages/bonito/cli/export.py", line 163, in main
    save_tensor(args.model, name, tensor)
  File "/bonito-0.7.0/venv3/lib/python3.8/site-packages/bonito/cli/export.py", line 62, in save_tensor
    tensors.save(f"{directory}/{name}.tensor")
  File "/bonito-0.7.0/venv3/lib/python3.8/site-packages/torch/jit/_script.py", line 713, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: Parent directory basecalls/weights_20.tar does not exist.`

**Comment by dnawhisperer** [comment]
Hi @iiSeymour  I have the same issue. Export function doesnt seem to work anymore. 

Thanks!

**Comment by jorisbalc** [comment]
Hello,
Same issue here. Exact error as @fergsc posted.

**Comment by davidnewman02** [comment]
This has been resolved in the latest bonito. Please raise a new ticket if you have any further issues with `bonito export`
