### ISSUE TITLE
Failed to install on Mac 12.6.2 (M1)

### ISSUE THREAD

**Issue by wgosal** [nanoporetech/bonito#348]
Struggling to install. Using the "Developer Quickstart" - I get the following output:

Collecting mappy==2.24 (from -r requirements.txt (line 2))
  Using cached mappy-2.24.tar.gz (140 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting toml==0.10.2 (from -r requirements.txt (line 3))
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tqdm<5,>4 (from -r requirements.txt (line 4))
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting scipy==1.10.1 (from -r requirements.txt (line 5))
  Using cached scipy-1.10.1-cp311-cp311-macosx_12_0_arm64.whl (28.7 MB)
Collecting numpy~=1.24.2 (from -r requirements.txt (line 6))
  Using cached numpy-1.24.3-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Collecting pysam==0.21.0 (from -r requirements.txt (line 7))
  Using cached pysam-0.21.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting parasail==1.3.4 (from -r requirements.txt (line 8))
  Using cached parasail-1.3.4.tar.gz (83 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas<2,>1 (from -r requirements.txt (line 9))
  Using cached pandas-1.5.3-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
Collecting requests~=2.28.2 (from -r requirements.txt (line 10))
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement ont-koi==0.3.0 (from versions: none)
**ERROR: No matching distribution found for ont-koi==0.3.0**

**Comment by iiSeymour** [comment]
@wgosal bonito is not support on mac - for m1 basecalling please see dorado https://github.com/nanoporetech/dorado
