### ISSUE TITLE
Is block C2 a TCS block?

### ISSUE THREAD

**Issue by Monzyy** [nanoporetech/bonito#35]
In the default model config it seems that block C2 is a time-separable convolution (TCS):
https://github.com/nanoporetech/bonito/blob/4535398d023e29a72ac41ff12d5591e80480048a/bonito/models/configs/quartznet5x5.toml#L87

Is this an intentional deviation from the quartznet architecture?
I might be misunderstanding what this line does.

**Comment by iiSeymour** [comment]
Hey @Monzyy 

Yes, it's intentional - with `separable = true` in C2 the total network parameter count is 6.7 million *(matching the paper)*, with `separable = false` it's 29.2 million. Not using dilation is also intentional however it's not something I've deeply investigated either.

**Comment by Monzyy** [comment]
Alright thanks. I think I figured out why I got this wrong. I was trying to calculate the number of parameters by hand but I couldn't get it right. It seems they forget to mention that block C2 is separable in the quartznet paper, but in their implementation C2 is separable.
