### ISSUE TITLE
Trace-like output from CTC-CRF models

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/bonito#350]
Hi, [we found Trace reported from flip-flop models quite informative feature for modification detection](https://doi.org/10.1038/s41587-021-00915-6).  

Could you advise how to calculate Trace-like information (probabilities for ACGT bases for each base/signal chunk) from CTC-CRF models?

**Comment by davidnewman02** [comment]
The probabilities can be extracted from the network output, in order to do this you will need to intercept the `scores` before they are passed to the beam-search: https://github.com/nanoporetech/bonito/blob/0c7fcceeeca16e300ba427d737282b33d3cb8ec9/bonito/crf/basecall.py#L36
