### ISSUE TITLE
Train older models

### ISSUE THREAD

**Issue by srrmtt** [nanoporetech/bonito#351]
Good morning @iiSeymour, I'm working on an older version of the bonito basecaller, in particular the one that was inspired by the QuartzNet architecture, I was wondering if the training dataset for that particular architecture is still the same that I can get calling `bonito download --training` or I can find it somewhere else.
I was also wondering if there is some validation dataset for this model still available and where I can find it.
Thanks in advance, best regards

**Comment by iiSeymour** [comment]
Hi @srrmtt yes, the training dataset is still the same and can be downloaded with `bonito download --training`.
