### ISSUE TITLE
bonito failes to load model

### ISSUE THREAD

**Issue by teodorabu** [nanoporetech/bonito#363]
Hello,

I have been using bonito to basecall a few sets of fast5 files by now and everything worked fine. However now I encounter an error when loading trying to load a model or even download models. My basecalling command is the following, after activating the corresponding environment (bonito version 0.7.2)

bonito basecaller dna_r10.4.1_e8.2_400bps_hac@v4.2.0 fast5/ > Bonito_Data/bonito_lambda_hac.bam

The error I get: 

> reading fast5
> outputting unaligned fastq
> loading model dna_r10.4.1_e8.2_400bps_hac@v4.2.0
> error: failed to load dna_r10.4.1_e8.2_400bps_hac@v4.2.0
> available models:
 - dna_r10.4.1_e8.2_260bps_fast@v3.5.2
 - dna_r10.4.1_e8.2_260bps_fast@v4.0.0
 - dna_r10.4.1_e8.2_260bps_fast@v4.1.0
 - dna_r10.4.1_e8.2_260bps_hac@v3.5.2
 - dna_r10.4.1_e8.2_260bps_hac@v4.0.0
 - dna_r10.4.1_e8.2_260bps_hac@v4.1.0
 - dna_r10.4.1_e8.2_260bps_sup@v3.5.2
 - dna_r10.4.1_e8.2_260bps_sup@v4.0.0
 - dna_r10.4.1_e8.2_260bps_sup@v4.1.0
 - dna_r10.4.1_e8.2_400bps_fast@v3.5.2
 - dna_r10.4.1_e8.2_400bps_fast@v4.0.0
 - dna_r10.4.1_e8.2_400bps_fast@v4.1.0
 - dna_r10.4.1_e8.2_400bps_fast@v4.2.0
 - dna_r10.4.1_e8.2_400bps_hac@v3.5.2
 - dna_r10.4.1_e8.2_400bps_hac@v4.0.0
 - dna_r10.4.1_e8.2_400bps_hac@v4.1.0
 - dna_r10.4.1_e8.2_400bps_hac@v4.2.0
 - dna_r10.4.1_e8.2_400bps_sup@v3.5.2
 - dna_r10.4.1_e8.2_400bps_sup@v4.0.0
 - dna_r10.4.1_e8.2_400bps_sup@v4.1.0
 - dna_r10.4.1_e8.2_400bps_sup@v4.2.0
 - dna_r9.4.1_e8_fast@v3.4
 - dna_r9.4.1_e8_hac@v3.3
 - dna_r9.4.1_e8_sup@v3.3

When downloading all the models using bonito download --models, I get:
OSError: [Errno 101] Network is unreachable
 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn.oxfordnanoportal.com', port=443): Max retries exceeded with url: /software/analysis/bonito/dna_r10.4.1_e8.2_400bps_fast@v4.2.0.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b660316a010>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
I was looking to download the models manually using the url in the download.py function, but the link crashes.
Can you please help me solve this problem?

Cheers,
Teodora

**Comment by teodorabu** [comment]
Fixed

**Comment by sklages** [comment]
And what was the actual problem?

**Comment by teodorabu** [comment]
I have taken it up to our cluster maintainers in order to find out if some connections have been blocked for users. 
I was able to download the models manually in the end and feed them into bonito.
