### ISSUE TITLE
RNA model

### ISSUE THREAD

**Issue by ADHDrian** [nanoporetech/bonito#364]
Hello,

I see that dorado already has a model for RNA004 - "rna004_130bps_sup@v3". I would like to retrain it using our own data. However, bonito still says that it is unavailable. Is there any way to get around this?

Thank you very much!

Adrian

**Comment by iiSeymour** [comment]
Hello @ADHDrian I've just published these for you f19c8c9a8fffec17822e9cd98cb7d7a93c4e2274

**Comment by ADHDrian** [comment]
Wonderful! Thank you so much for your prompt response @iiSeymour .

**Comment by VBHerrenC** [comment]
@ADHDrian were you ever able to use these models to train? I'm trying to use the RNA004 models to train a basecaller but am running into many issues - my only thought is that the model with the --save-ctc flag is not outputting correctly. If you were able to make it work though, it must be something on our end. Would appreciate any info you have!
