### ISSUE TITLE
5mC detection for RNA

### ISSUE THREAD

**Issue by keenhl** [nanoporetech/bonito#365]
We have fast5 files generating using the RNA002 chemistry. We are interested in determining the methylation status (5mc) of these reads. 

How do we proceed to do this Bonito?  Alternatively, if this is not something Bonito can do, what application would be recommended?

Thanks for your help.

**Comment by davidnewman02** [comment]
5mC methylation calling is not supported for the RNA002 kit, it is available for the RNA004 kit in Dorado. 
https://dorado-docs.readthedocs.io/en/latest/basecaller/mods/
