### ISSUE TITLE
Model versions

### ISSUE THREAD

**Issue by fergsc** [nanoporetech/bonito#369]
Hi,

I have some 4khz and 5khz data that I will be training a model for. I am seeking clarification on which bonito training models are 4khz and which are 5khz.

5kHz simplex models include:
- dna_r10.4.1_e8.2_400bps_fast@v4.2.0
- dna_r10.4.1_e8.2_400bps_hac@v4.2.0
- dna_r10.4.1_e8.2_400bps_sup@v4.2.0

Are all other models r10.4.1 4khz?

Other than using the correct model are there any other parameters to modify if using 4khz or 5khz data?

Thanks.

**Comment by iiSeymour** [comment]
Hi @fergsc 

Yes, that's correct, and no, there are no other parameters outside the model configs that you need to set differently to account for the sample rate differences.
