### ISSUE TITLE
basecaller cannot read fast5 file

### ISSUE THREAD

**Issue by fulixie** [nanoporetech/bonito#37]
Hello iiSeymour :

Recently, I use bonito basecaller to call the fast5 file which is generated by Minion. I have run the basecaller by the model I trained myself and the dna R9.4.1 model released, neither of them worked. 
The command is 
bonito basecaller dna_r9.4.1 ./minion_phage->minion.fasta

It shows loading model and calling as well, but then it shows there is 0 reads. Such as 
> loading model
> calling
0it [00:00, ?it/s]
> completed reads: 0
> samples per second 0.0E+00
> done

The fast5 files are fine, I read them from the ont-fast5-api, they do contain reads. And I can run the basecaller well just 1 week before. What problem cause this? How can i fix it?

**Comment by iiSeymour** [comment]
Hi @fulixie 

Bonito only looks inside the top level of the specified directory so I assume your reads are further down the folder structure and that is why 0 reads are being reported.

**Comment by fulixie** [comment]
Hi @iiSeymour 
Thank you for your reply.

I put the fast5 file just under the specified drectory, and it worked well before. I just tried to specify the fast5 file itself instead of the folder, and got the same result. Is there any identification of the reads added in this version which the file is missing, or something else may the code believe there is no reads in the file?

> Hi @fulixie
> 
> Bonito only looks inside the top level of the specified directory so I assume your reads are further down the folder structure and that is why 0 reads are being reported.

**Comment by fulixie** [comment]
Hi @iiSeymour:

Thank you for your reply. It looks like the problem of the command, I just delete the - , it works now.
bonito basecaller model read_directory > *.fasta
