### ISSUE TITLE
Optimise training batch_size

### ISSUE THREAD

**Issue by fergsc** [nanoporetech/bonito#371]
Hi,

When I train a model I use as big of a batch size as possible.
Does this have any impact on basecalling in Guppy/Dorado?

Thanks

**Comment by vellamike** [comment]
Larger batch sizes will affect training dynamics, but at inference time the batch size used in basecalling and training are unrelated.

**Comment by fergsc** [comment]
Thanks,

I will continue to use large batch sizes in training.
