### ISSUE TITLE
how bonito normalize raw signals when  save-ctc

### ISSUE THREAD

**Issue by xieyy46** [nanoporetech/bonito#374]
Hi bonito team!
I want to know how bonito normalize raw signals! I noticed that in the chunks.npy, the signal seem to be normalized to (-1, 1). Does bonito normalize raw signals in per chunk level? or per level? or per run level?
![image](https://github.com/nanoporetech/bonito/assets/76148123/8cd5a9b0-411a-4d9d-be01-32833be0961b)

**Comment by iiSeymour** [comment]
Hi @xieyy46 most commonly, normalization happens per read using `med_mad` or later `quantile` strategies  _(reference implementation can be found in the code)_. However, in the very latest models we have switched to a global strategy.

**Comment by joshtburdick** [comment]
I was thinking about normalization a bit.

In particular, I was thinking about a very naive model of the five bases in a pore, as five resistors connected in series. I'm sure the pore is more complicated than this, but it's a simple model. With that (admittedly way oversimplified) model, the resistance of all five is just the sum, and so a linear function.

So, you could use the assumed voltage, and convert from pA to pico-ohms or nano-ohms.

I'm wondering if this might be *slightly* easier for the NN to parse? I realize that the NN can model all sorts of nonlinear things, and I wouldn't expect a large improvement. But it seems like a (relatively) small software-only thing to try (although no doubt complicated).
