### ISSUE TITLE
reproduce the training

### ISSUE THREAD

**Issue by MarkAlive** [nanoporetech/bonito#38]
Hi,

thanks for the project.

I'm trying to reproduce the model training. I had now trained a model with train data(851972x4800). The mean_acc and median_acc in evaluate data(100000x8192) are 95.5645% and 96.1451%. It is about 0.6% less than the model that download from your repository. Out training setting: 8GPUs, bs=512, lr=1e-3, epochs=400. Could you share something detail about this?

**Comment by iiSeymour** [comment]
Hey @MarkAlive 

Can I confirm you used [dna_r9.4.1.toml](https://github.com/nanoporetech/bonito/blob/master/bonito/models/configs/dna_r9.4.1.toml), not [quartznet5x5.toml](https://github.com/nanoporetech/bonito/blob/master/bonito/models/configs/quartznet5x5.toml)?

**Comment by MarkAlive** [comment]
@iiSeymour I used quartznet5x5.toml. Will the new model be faster or higer acc?

**Comment by MarkAlive** [comment]
Actually, lr set as 2e-3 can get a better result in 8GPUs situation. But when I extend to 64GPUs. It is easy to fall into divergence problem, while lower lr can't reach the baseline acc.

**Comment by iiSeymour** [comment]
Yes, the newer model will coverage faster and reach higher accuracies.

**Comment by MarkAlive** [comment]
Thanks for the quick reply. 

I coverted the hdf5 file to npy format with the defaut args in config.toml and finally got  851972 chunks of data. Does the model trained with this size of data?

**Comment by iiSeymour** [comment]
Yes you will want to train will all the chunks, one of the filters `--min-run` has a default of 5, setting this to 1 will results in more chunks being generated.

**Comment by MarkAlive** [comment]
Thanks, I will try it.
