### ISSUE TITLE
Applying INT8 quantization, just like in Dorado

### ISSUE THREAD

**Issue by wtrinh8** [nanoporetech/bonito#388]
Hello all,

I was curious how actively Bonito is still being used, as I read that Dorado nowadays converted a majority of its neural network code to INT8.

I was interested in experimenting with the current Dorado model, but I could not find a way to create an ONNX model export of the C++ neural network model.

Therefore, is there still a possibility that optimization features from Dorado will be applied to Bonito as well?

Kind regards

![image](https://github.com/nanoporetech/bonito/assets/163990773/23724448-ad5b-44d5-b619-7569a835b5f2)

**Comment by Dragonsky8** [comment]
Hi, I was looking into the Koi lstm.py file and saw you could apply quantisation there via a flag. However, the hac@v4.3.0 does not use the LSTM class from Koi. Is it possible to use the LSTM from Koi, instead of the LSTM from Torch?
