### ISSUE TITLE
how to choose the model?

### ISSUE THREAD

**Issue by baronfairy** [nanoporetech/bonito#393]
is:issue is:open there are so many models,like dna_r10.4.1_e8.2_260bps_sup@v4.0.0 ,dna_r9.4.1_e8_hac@v3.3. which one should me choose to match my data.

**Comment by iiSeymour** [comment]
@baronfairy for basecalling you'll probably want dorado _(not bonito)_. 

Models are explained here https://github.com/nanoporetech/dorado?tab=readme-ov-file#dna-models

Dorado can also select the correct model for you https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex
