### ISSUE TITLE
details about training data

### ISSUE THREAD

**Issue by kishwarshafin** [nanoporetech/bonito#4]
Hello,

Are there any details on how to generate the training data? If you can simply mention the steps, we will hopefully be able to figure it out.

**Comment by iiSeymour** [comment]
A dataset is provided with the project, you just need to run [scripts/get-training-data](https://github.com/nanoporetech/bonito/blob/master/scripts/get-training-data) after you have completed the [quickstart](https://github.com/nanoporetech/bonito#quickstart).

**Comment by kishwarshafin** [comment]
yes, but it only has 66K reads to train on. I have already trained a model and it converges very quickly. And in some cases, I am seeing overfitting issues. I was wondering if there are any instructions so we can generate our own training set.

**Comment by iiSeymour** [comment]
The [convert-data](https://github.com/nanoporetech/bonito/blob/master/scripts/convert-data) script can create 10 of millions of training examples *(chunks)* from the 66K full reads. How many chunks did you use for training?

If you want to generate your own training set you will need to create the following 4 `.npy` files
 
```python
>>> # references.npy
>>> # Integer encoded target sequence {'A': 1, 'C': 2, 'G': 3, 'T': 4}
>>> # Variable length and zero padded (default range between 128 and 256).
>>> np.load('references.npy').shape
(1000000, 256)
>>> np.load('references.npy').dtype
dtype('uint8')
>>>
>>> # reference_lengths.npy
>>> # Lengths of target sequences in references.npy
>>> np.load('reference_lengths.npy').shape
(1000000,)
>>> np.load('reference_lengths.npy').dtype
dtype('uint8')
>>>
>>> # chunks.npy
>>> # Sections of squiggle that correspond with the target reference sequence
>>> # Variable length and zero padded (upto 4096 samples).
>>> np.load('chunks.npy').shape
(1000000, 4096)
>>> np.load('chunks.npy').dtype
dtype('float32')
>>>
>>> # chunk_lengths.npy
>>> # Lengths of squiggle sections in chunks.npy 
>>> np.load('chunk_lengths.npy').shape
(1000000,)
>>> np.load('chunk_lengths.npy').dtype
dtype('uint16')
```

This format matches what [CTCLoss](https://pytorch.org/docs/stable/nn.html#ctcloss) needs for training. The project is only a few weeks old this may not continue to be the format of choice going forward. A better suggestion might be to create a single hdf5 file with the squiggle, mapping and reference that the [convert-data](https://github.com/nanoporetech/bonito/blob/master/scripts/convert-data) uses to create the numpy files.

**Comment by kishwarshafin** [comment]
Thank you so much for the details! So, you are using SquiggleKit to map the reference to the signals to identify the chunks of the signals that belong to a portion of the signal? Just wondering how you derive `Ref_to_signal`.

**Comment by iiSeymour** [comment]
Okay, that explains it. Only 20K chunks will definitely lead to overfitting, typically you will want to train with at least 500K chunks. The number of chunks and the range is still something I am exploring, some results from today suggest that larger chunk sizes *(that is using target sequences > 256)* may perform better.

To create a `Ref_to_signal` mapping you will want to use the un-decoded probabilities from the network which can be achieved with a small modification to the `decode_ctc` function to return both the sequence and the mapping. You can also get this from guppy by using the fast5 output and storing the `move` table. You will, of course, want to include a mapping step back to the reference. I will be looking to add a script to make this whole process simpler in the next few weeks.  

The example data and model provided are for R9.4.1 right now.

Please do share back any interesting results you find.

**Comment by kishwarshafin** [comment]
That totally makes sense now! Great! I am very hopeful that this project will make things a lot easier in terms of signal level application. I'll play around with some data that I have on hand for R941 and give you some results. It would be extremely helpful if you create a script to generate the training examples, that way training on different chemistries would be easier to explore.

Thanks again for the clarification, I'm closing the issue as you are aware of it already. Hoping to see this succeed soon and become a stable basecaller.

**Comment by N-damo** [comment]
> 



> I'm slightly confused. When creating the chunks, `ref_to_signal` is required, as shown [here](https://github.com/nanoporetech/bonito/blob/62050ba32fac20b1e82f1349aaaaf41512a7008c/bonito/cli/convert.py#L57). However, you are saying it can be obtained from the decode_ctc function, which I believe is the output of the model. That becomes a bit circular. How do you get ref_to_signal before you chunk the data and run it through the basecalling algorithm?

tombo resquiggle could do that too
