### ISSUE TITLE
Sequencing Summary File

### ISSUE THREAD

**Issue by snower2010** [nanoporetech/bonito#40]
Hi, bonito can not generate a sequencing_summary.txt like Guppy do. Is there any way to generate this file?

Many thanks!

**Comment by iiSeymour** [comment]
https://github.com/nanoporetech/bonito/commit/8cf85d75c82fe8f5ac58b47afbf2f8e0e9f8f405 adds summary file support with the following subset *(compared to guppy)* of columns. 

```
     1  filename
     2  read_id
     3  run_id
     4  channel
     5  mux
     6  start_time
     7  duration
     8  template_start
     9  template_duration
    10  sequence_length_template
    11  mean_qscore_template
```

The summary file will be created in the same directory as the location used to redirect stdout.

```bash
$ bonito basecaller --half dna_r9.4.1 reads > /tmp/basecalls/output.fasta
> loading model
> calling
100%|###########################################################| 1000/1000 [00:37<00:00, 21.60it/s]
> completed reads: 1000
> samples per second 1.8E+06
> done
$ ls /tmp/basecalls
output.fasta output_summary.tsv
```

@snower2010 @jaquol comments welcome. I need to do a little more validation but I can have this released this week if it meets your requirements.

**Comment by iiSeymour** [comment]
[v0.2.1](https://github.com/nanoporetech/bonito/releases/tag/v0.2.1) is released with summary tsv output.
