### ISSUE TITLE
Modification Detection

### ISSUE THREAD

**Issue by chong-hun** [nanoporetech/bonito#404]
Does Bonito currently support or can it be extended to detect modifications like m6A, m5C, etc.? Are there any suggestions or existing work that I could refer to for this?

**Comment by davidnewman02** [comment]
Hi @chong-hun,

No, unfortunately Bonito does not support modified basecalling and there are no plans to incorporate this. 
To generate modified basecalls, please use Dorado: `dorado basecaller {model} {input_data} --modified-bases {mod_list} > out.bam` or if you are interested in developing/training mod-base models, then please check-out the model training and evaluation tools in Remora: https://github.com/nanoporetech/remora

Thanks

**Comment by chong-hun** [comment]
Thanks for your apply！
