### ISSUE TITLE
IndexError with bonito train

### ISSUE THREAD

**Issue by Serka-M** [nanoporetech/bonito#50]
Hello,

I have been trying out model training with Bonito using a converted Taiyaki training dataset.

Looking at the change in Loss function, the training looks really promising, but at the end of training I get ` IndexError: list index out of range `. Since Bonito doesn't seem to save intermediate files or model checkpoints, all model files get lost because of the error.

Here's the full error report (slightly redacted):

```
[1875010/1875010]: 100%|####################################################| [5:23:58, loss=0.3562]
Traceback (most recent call last):
  File "/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/.local/lib/python3.6/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File ".local/lib/python3.6/site-packages/bonito/train.py", line 78, in main
    val_loss, val_mean, val_median = test(model, device, test_loader)
  File "/.local/lib/python3.6/site-packages/bonito/training.py", line 209, in test
    references = [decode_ref(target, model.alphabet) for target in test_loader.dataset.targets]
  File "/.local/lib/python3.6/site-packages/bonito/training.py", line 209, in <listcomp>
    references = [decode_ref(target, model.alphabet) for target in test_loader.dataset.targets]
  File "/.local/lib/python3.6/site-packages/bonito/util.py", line 115, in decode_ref
    return ''.join(labels[e] for e in encoded if e)
  File "/.local/lib/python3.6/site-packages/bonito/util.py", line 115, in <genexpr>
    return ''.join(labels[e] for e in encoded if e)
IndexError: list index out of range
```

Best,
Mantas

**Comment by iiSeymour** [comment]
Hello @Serka-M 

Bonito does store model checkpoints after every epoch but unfortunately you have run into an issue just prior to that.

The traceback suggests that your converted `references.npy` file has more encoded bases in that it’s expecting.

Can you load the file and check for the highest index?

```python
>>> import numpy as np
>>> r = np.load(“path/to/references.npy”
>>> np.max(r)
4
```

The max index expected is 4 - where the indexes {0, 1, 2, 3, 4} map to the labels {N, A, C, G, T}.

Chris.

**Comment by Serka-M** [comment]
Hey Chris,

The converted Taiyaki dataset is for a modified base, so it has one extra nucleotide letter.

Is there a possibility for a "quick fix" by editing some lines in Bonito code to make it all work?

**Comment by iiSeymour** [comment]
Okay that explains it - the labels for the model are define in the [config](https://github.com/nanoporetech/bonito/blob/master/bonito/models/configs/dna_r9.4.1.toml#L4) so the quick fix would be to add the extra label, this might not be the most effective way to handle modified base however.
