### ISSUE TITLE
Any plans for outputting raw signal based on basecalls?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/bonito#51]
One of the great things about CTC is that the signal segmentation. I'm not exactly certain as to whether this is possible in Bonito, but are there any plans or is there a possible way to extract the raw signal chunks based on specific subsequences in the basecalled data? It would be really useful for a lot of different applications.

**Comment by iiSeymour** [comment]
Yes, it's already possible to get the path for every base to the squiggle location when using the greedy decoder - [see here](https://github.com/nanoporetech/bonito/blob/master/bonito/model.py#L81).

**Comment by billytcl** [comment]
Wow, this is great!!
