### ISSUE TITLE
TCSConv1d stride in pointwise convolution

### ISSUE THREAD

**Issue by rhenzel** [nanoporetech/bonito#53]
Hi Chris,

I may be missing something, but in `TCSConv1D` when `separable=True` shouldnt the pointwise convolution always have `stride=1` instead of `stride=stride`?

Else the separable convolution isn't matching a regular `Conv1D` in output shape for any stride larger 1, also I feel like stride doesnt make sense for the pointwise part.

Best
Robert

**Comment by iiSeymour** [comment]
Hey Robert,

You are correct, it doesn’t make sense - it’s a bug.
