### ISSUE TITLE
GPU memory reset

### ISSUE THREAD

**Issue by esteinig** [nanoporetech/bonito#54]
Hey Chris, just wanted to let you know that failed / canceled `Bonito` runs appear to not reset the memory on our GPUs (Tesla V100, 440.64.00, CUDA: 10.2) and run as `PID`s that are not visible on `nvidia-smi`

I usually check with `lsof /dev/nvidia0` and kill them, but perhaps this is something you might want to consider (if it's a `Bonito` issue)

**Comment by esteinig** [comment]
It looks like it's a common issue with `Pytorch`: https://github.com/pytorch/pytorch/issues/4031 

Sorry for bugging you with this, looks like it's not a `Bonito` issue.

**Comment by iiSeymour** [comment]
Hey @esteinig 

I see this myself and think it should be relatively straight forwards to catch the interrupts and gracefully cancel *(i.e. let the current read finish basecalling before quitting)*.

**Comment by esteinig** [comment]
Ah wonderful, thanks for the quick reply and all the work on the basecaller so far

**Comment by iiSeymour** [comment]
Fixed in https://github.com/nanoporetech/bonito/commit/3615abcc2928e4a9add0786d1c3fbba92cebcf13.
