### ISSUE TITLE
Runtime of Bonito compared to Guppy (CPU and GPU)

### ISSUE THREAD

**Issue by zmunro** [nanoporetech/bonito#57]
I am interested in using the Bonito basecaller, but I am finding much less documentation on it compared to Guppy unfortunately. Is anyone aware of how Bonito compares to Guppy in terms of speed?
Also, depending on its normal speed, can Bonito utilize a GPU during basecalling?

**Comment by iiSeymour** [comment]
Hey @zmunro 

The goals of the two projects are slightly different. Guppy is the official production basecaller which is fully supported and documented, it’s also the most performant. Bonito is an open source research project that provides everything you need for training and basecalling. Bonito is primarily a GPU focused project however it sounds like you want Guppy for the speed and documentation. If you are interested in method development then please do check out the code and feel free to ask for further clarification where needed.

**Comment by zmunro** [comment]
@iiSeymour Thanks for the response! I am still a little confused. Could you confirm my understanding of the following:

- Guppy is, in general, faster than Bonito at basecalling
- Bonito is meant to utilize GPU(s) for basecalling

**Comment by zmunro** [comment]
I am thinking about integrating some interesting technology from this company [Neural Magic](https://neuralmagic.com/) who have an ML prediction engine that allows you to build CNNs that can run on CPUs and get the same performance as GPUs.
There software wont work with Guppy unfortunately since it is built around optimizing CNNs and Guppy is built around an RNN.

**Comment by iiSeymour** [comment]
Yes, you are correct. Guppy is, in general, faster than Bonito at basecalling and Bonito does utilize GPU(s) for basecalling.

Neural Magic make some impressive claims so if you get any results I’d be interesting in hearing about that.

If you are interested in fast CPU inference then you might want to keep an eye on https://github.com/nanoporetech/bonito/pull/52.

**Comment by iiSeymour** [comment]
Bonito basecalling speeds are now inline with guppy.
