### ISSUE TITLE
"CUDA out of memory" error

### ISSUE THREAD

**Issue by ilnamkang** [nanoporetech/bonito#6]
Hi,

I've encountered "CUDA out of memory" error during running bonita. Below is the error message.

RuntimeError: CUDA out of memory. Tried to allocate 1.52 GiB (GPU 0; 5.80 GiB total capacity; 2.30 GiB already allocated; 1.45 GiB free; 1.21 GiB cached)

My command was as follows:
bonito basecaller /path_to_fast5/ ./bonito/models/quartz5x5-s3-4000/

I'm running bonito on Ubuntu 18.04 equipped with GTX 1660 (NVidia Driver Version: 430.50 & CUDA Version: 10.1).

Are there any solution(s) for this error?

Thanks.

Thanks.

**Comment by iiSeymour** [comment]
Hi @ilnamkang 

The read chunking is currently unbounded so a large read or a small amount of free GPU memory will result in this error. I will get a patch submitted shortly.

Thanks.

**Comment by iiSeymour** [comment]
I've added a default batchsize of 64 which should keep the memory bounded to a little over 2GB.

Also, note that the fasta records are printed to stdout so you will want to redirect the output to a file. 

```
bonito basecaller /path_to_fast5/ ./bonito/models/quartz5x5-s3-4000/ > calls.fasta
```

**Comment by ilnamkang** [comment]
Bonito is running nicely. Memory consumption is ~3 GB in my machine.

Thanks a lot.

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2858      G   /usr/lib/xorg/Xorg                            33MiB |
|    0      2890      G   /usr/bin/gnome-shell                          69MiB |
|    0     47975      C   .../user/Programs/bonito/bonito/bin/python  3133MiB |
+-----------------------------------------------------------------------------+
