### ISSUE TITLE
Base quality from bonito v0.3?

### ISSUE THREAD

**Issue by kishwarshafin** [nanoporetech/bonito#61]
Hello,

We were going to try to see if Bonito is now suitable for the `PEPPER-DeepVariant` pipeline but the default commands look like Bonito is still outputting FASTA instead of FASTQ? Is there a way to output FASTQ files on which our pipeline makes few decisions?

**Comment by iiSeymour** [comment]
There is no way to get per base qscores with the new model in this release - it's not obvious how we would do this with beam search decoding and needs some thought.

**Comment by kishwarshafin** [comment]
in that case what would the `--fastq` parameter do? Output random quality or constant value?

**Comment by iiSeymour** [comment]
Erm, just a single constant value actually. I should probably make the qstring length match the sequences length in this case).

Are you making use of the qscores or just looking to avoid a `.fasta` -> `.fastq` conversion?

**Comment by kishwarshafin** [comment]
ah, in that case, I'll just use seqtk to convert fasta to fastq. Thanks! We need fastq for the pipeline. Fasta breaks things.

**Comment by kishwarshafin** [comment]
@iiSeymour ,

Wanted to let you know that bonito is extremely slow on our end:
`> calling: 799967 reads [21:56:22,  3.14 reads/s]`
In this speed, it'd take 14 days for a flowcell of the human genome to be basecalled. I'm running this on 4GPU (2080Ti) machine. If you have any advice on speeding this up, it'll be helpful, otherwise, we would conclude that bonito is still not ready for human genome informatics.

**Comment by iiSeymour** [comment]
I haven't looked at the performance on any gaming cards but that is a lot slower than the performance on the compute cards. Can you report the sample/s for a single 2080Ti? Also, are you running with 4 instances of bonito *(one per gpu)*, or have you patched in multi-gpu calling?

**Comment by kishwarshafin** [comment]
I'm using 4instances of bonito, one per GPU. I've split the input into 4 chunks and feeding them in parallel. The speed is about the same on one 2080Ti, at first it starts at around 500 reads/s but after a while, it goes down to 5~10 reads/s. 

The machine has 72threads with 4GHz CPU and all data is on NVMe drive so no bottleneck is there I/O-wise.

**Comment by iiSeymour** [comment]
Wow, that's quite a drop and not something I have seen.

Of course reads/s doesn't take into account read length so we should rule out that it's not just shorter reads getting processed first. I'd also want to check for any thermal throttling. You can use tools like `nvidia-smi` or `nvtop` to keep an eye on the GPUs clock frequency and temperature.

<img width="851" alt="Screenshot 2020-10-29 at 23 03 10" src="https://user-images.githubusercontent.com/4310904/97641491-f07bc280-1a3a-11eb-8571-5c4e8d65f9fb.png">

**Comment by kishwarshafin** [comment]
I stopped and started on Zymo data. This time I'm using one GPU. Still the same trend. Am I missing something?
```bash
bonito basecaller \
dna_r9.4.1 \
/data/Zymo-GridION-EVEN-BB-SN/ > Zymo_reads_bonito_v0.3.fasta

> loading model
> calling: 2005 reads [13:35, 11.17 reads/s]
```
![image](https://user-images.githubusercontent.com/10559039/97658410-7abb2b00-1a29-11eb-800f-74198ce076da.png)

**Comment by vellamike** [comment]
Hi @kishwarshafin. 4 GPUs are likely to be IO bottlenecked, especially if you have NVME drives on this system contending for bandwidth with the GPUS. 

Can you run the same zymo data to  conclusion (2005 reads should only be 3 minutes) and verify that it is 4 times faster on 4 GPUS? If not then you have an IO bottleneck. 

What CPU model are you paring with the GPUS?  

Could you also report the total size of these 2005 files?

**Comment by kishwarshafin** [comment]
@vellamike ,

Here's the CPU configuration:
```bash
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              72
On-line CPU(s) list: 0-71
Thread(s) per core:  2
Core(s) per socket:  18
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz
Stepping:            7
CPU MHz:             2528.997
CPU max MHz:         4000.0000
CPU min MHz:         1200.0000
BogoMIPS:            6200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-17,36-53
NUMA node1 CPU(s):   18-35,54-71
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
```

and the `nvme` data storage is exclusively used for basecalling:
```bash
nvme1n1     259:0    0   1.5T  0 disk
└─nvme1n1p1 259:2    0   1.5T  0 part /data
```

That Zymo run is still going. I'm planning to let it run so I have some data to run a Shasta assembly. The current state of the run is:
```bash
$ bonito basecaller \
dna_r9.4.1 \
/data/Zymo-GridION-EVEN-BB-SN/ > /data/Zymo_reads_bonito_v0.3.fasta

> loading model
> calling: 193751 reads [4:06:39, 12.22 reads/s]
```

I'll post the read size and other info once the run finishes. Thanks for taking a look at this.

**Comment by vellamike** [comment]
Can you print the output of `lspci -vv` please?

**Comment by kishwarshafin** [comment]
@vellamike , 
here's the lspci output: [lspci.log](https://github.com/nanoporetech/bonito/files/5466119/lspci.log)

**Comment by vellamike** [comment]
Thanks @kishwarshafin 

Can you run again with `sudo` (sorry my mistake). Can you also profile the aplication for 1 minute with nvprof and show the trace?

**Comment by kishwarshafin** [comment]
hi @vellamike , I'm not an admin of the machine so can't run `sudo`. Looks like `nvprof` is also absent. Sorry for not being able to provide any more information :(

**Comment by iiSeymour** [comment]
It's usually not on the path but you should find it in your cuda bin directory -

```bash
$ /usr/local/cuda-10.2/bin/nvprof -o bonito_profile.nvvp bonito basecaller dna_r9.4.1 reads > out.fasta
```

**Comment by kishwarshafin** [comment]
I don't have permission to run it. Ok, let me see if I can get my admin privileges.

**Comment by kishwarshafin** [comment]
Ok, here are the files:
https://storage.googleapis.com/kishwar-helen/misc/bonito_profile.nvvp
https://storage.googleapis.com/kishwar-helen/misc/lspci.log

the `nvvp` is 2.6GB.
