### ISSUE TITLE
Multiple GPU usage

### ISSUE THREAD

**Issue by wharvey31** [nanoporetech/bonito#63]
Hello, we have been trying to use multiple GPUs to basecall and have discovered some interesting behavior. When specifying `--device cuda:0` it runs on our CUDA0 device as intended. When we specify `--device cuda:1` it leaks on to both GPUs as seen in the image below. Is this an intended behavior? The nomenclature with guppy for multiple GPUs is `--device "cuda:0 cuda:1"`. Is bonito basecalling intended for multi-GPU usage?

<img width="571" alt="Screen Shot 2020-11-03 at 3 19 46 PM" src="https://user-images.githubusercontent.com/31748245/98051280-5b851a80-1de8-11eb-8622-f0bae187f81a.png">

**Comment by iiSeymour** [comment]
Hey @wharvey31 

Bonito doesn't currently support multi-gpu calling and the behaviour you are seeing is the default for frameworks like PyTorch and TensorFlow. You can manage which devices are available to the process with `CUDA_VISIBLE_DEVICES`.

```bash

$ CUDA_VISIBLE_DEVICE=0 bonito basecaller dna_r9.4.1 data_set_1 > calls_1.fasta
$ CUDA_VISIBLE_DEVICE=1 bonito basecaller dna_r9.4.1 data_set_2 > calls_2.fasta
```

**Comment by RichardCorbett** [comment]
Hi there,
I too was trying to run bonito on a multi-GPU machine.   I have split a folder fast5s into subfolders once I started to see numbers suggesting it would take roughly 20 days to basecall my flowcell (4 reads/s).    Then I run with these commands:
{code}
CUDA_VISIBLE_DEVICE=0 /opt/bonito-0.3.2/bin/bonito basecaller dna_r9.4.1  1 > 1.fastq
CUDA_VISIBLE_DEVICE=1 /opt/bonito-0.3.2/bin/bonito basecaller dna_r9.4.1  2 > 2.fastq
{code}

After some reads are processed I get the following error:
{code}
CUDA_VISIBLE_DEVICE=1 /opt/bonito-0.3.2/bin/bonito basecaller dna_r9.4.1  2 > 2.fastq
> loading model
> calling: 188 reads [02:58,  2.01 reads/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/bonito-0.3.2/lib/python3.6/site-packages/bonito/multiprocessing.py", line 202, in run
    for (k, v) in self.iterator:
  File "/opt/bonito-0.3.2/lib/python3.6/site-packages/bonito/crf/basecall.py", line 105, in <genexpr>
    stitched = ((read, _stitch(x)) for (read, x) in unbatchify(batches))
  File "/opt/bonito-0.3.2/lib/python3.6/site-packages/bonito/util.py", line 209, in <genexpr>
    for k, group in groupby(batches, itemgetter(0))
  File "/opt/bonito-0.3.2/lib/python3.6/site-packages/bonito/util.py", line 208, in <listcomp>
    (k, concat([v for (k, v) in group], dim))
  File "/opt/bonito-0.3.2/lib/python3.6/site-packages/bonito/util.py", line 203, in <genexpr>
    (k, select_range(v, start, end, dim))
  File "/opt/bonito-0.3.2/lib/python3.6/site-packages/bonito/crf/basecall.py", line 103, in <genexpr>
    for read, batch in thread_iter(batchify(chunks, batchsize=batchsize))
  File "/opt/bonito-0.3.2/lib/python3.6/site-packages/bonito/crf/basecall.py", line 38, in compute_scores
    betas = model.seqdist.backward_scores(scores.to(torch.float32))
RuntimeError: CUDA out of memory. Tried to allocate 450.00 MiB (GPU 0; 10.76 GiB total capacity; 2.61 GiB already allocated; 66.12 MiB free; 3.74 GiB reserved in total by PyTorch)
{code}

Is the above approach still recommended for multi-GPU basecalling?   I see a `--devices` parameter that I'm not using - perhaps I need to provide something there?

**Comment by noncodo** [comment]
despite using different CUDA_VISIBLE_DEVICE values, I'm getting different executions pushed to the same GPU (explains @RichardCorbett's issue).

**Comment by iiSeymour** [comment]
Sorry @noncodo @RichardCorbett it should be `CUDA_VISIBLE_DEVICES`.

**Comment by Psy-Fer** [comment]
Thanks  Martin (@noncodo) saved me a headache, I owe you a beer.

**Comment by ttbond** [comment]
Hi~
I run bonito with multiple GPUs by --device cuda:x.
For example:
`bonito basecaller --device cuda:0 modelDirectory fast5Directory0
 bonito basecaller --device cuda:1 modelDirectory fast5Directory1
bonito basecaller --device cuda:2 modelDirectory fast5Directory2
bonito basecaller --device cuda:3 modelDirectory fast5Directory3`
But the first process that runs on cuda:0, seems get blocked.
![image](https://user-images.githubusercontent.com/19239349/123567978-ebebf180-d7f5-11eb-9c39-bfcd039fdaf4.png)

**Comment by iiSeymour** [comment]
For performant multi-gpu inference see https://github.com/nanoporetech/dorado https://github.com/nanoporetech/dorado
