### ISSUE TITLE
add -v option

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/bonito#68]
Hi

It would be great to see the version number of bonito.

Best regards
Rasmus

**Comment by iiSeymour** [comment]
Hey @Kirk3gaard 

That's already supported *(see [here](https://github.com/nanoporetech/bonito/blob/master/bonito/__init__.py#L22))*.

```
$ bonito -v
bonito 0.3.1
```

Are you seeing something different or perhaps trying `bonito basecaller -v`?

**Comment by Kirk3gaard** [comment]
Yep I did exactly that :D Thanks!!!
