### ISSUE TITLE
suggestions on choosing the training set to train your own model

### ISSUE THREAD

**Issue by defendant602** [nanoporetech/bonito#72]
Hi @iiSeymour 

Thanks for your work on developing this basecaller! I have been trying to train my own model for a specific species, but there are some questions confusing me on how to choose the training data set. Could you give some suggestions on choosing the training set? 

My questions are like:

1. It sounds like the current pre-trained models are trained from mixed data which come from human, yeast and E. coli. Does the reference.fasta contain genome sequences of all these three species? If I want to train my own model for a specific species, for example, rice, how should I choose the training reads and the reference.fasta? Are the training reads supposed to come from different rice samples?

2. How many reads do I need to train a taxon-specific model and what's the corresponding GPU memory consumption of this amount of reads when doing `bonito train`?

Thanks in advance!

**Comment by iiSeymour** [comment]
Hey @defendant602 

I can provide some guidance however the training data size and composition is an active area of research so my best advice is just experiment. The last set of commits contain changes that make putting together and experimenting with dataset easier so make sure you checkout https://github.com/nanoporetech/bonito/commit/128c8bf987465e6ec8eb7c441f48283c7550ce07.

 1. Yes, you can put together a reference fasta with all the species you are interested in or you can create a training set per genome/chromosome and combine them together after the fact.

 2. The available dataset has ~66,000 reads but we are experimenting with much larger sets. You should think about the number of reads in context with the size and complexity of genomes you are targeting. For training, reads are split into fixed-sized chunks and chunks are batched on to the GPU, so the GPU memory consumption is driven by the batch size not the training set size.

You might also want to checkout @menickname et al. paper here - https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03856-0#Sec8

**Comment by mattdmem** [comment]
Hijacking this a little... How do you achieve number 1? Combining models?

**Comment by iiSeymour** [comment]
No, not by combining models, just by stacking the the training `*.npy` files.

Say you had three organism of interest - you could create a single reference file with all three and run basecalling with `--save-ctc`. Alternatively _(and probably recommended)_ if you have your reads already separated then:

```
$ bonito basecaller dna_r9.4.1 --reference organism_1.mmi --save-ctc organism_1_reads > organism_1_data
$ bonito basecaller dna_r9.4.1 --reference organism_2.mmi --save-ctc organism_2_reads > organism_2_data
$ bonito basecaller dna_r9.4.1 --reference organism_3.mmi --save-ctc organism_3_reads > organism_3_data
```

Would give you three sets of `{chunks, references, reference_lengths}.npy` which you could stack with the _(the very rough)_ code below:

```python

import numpy as np

def load(path, max_size=600):
    c = np.load("%s/chunks.npy" % path).astype(np.float16).squeeze()
    r = np.load("%s/references.npy" % path)
    r = np.pad(r, [(0, 0), (0, max_size - r.shape[1])], mode='constant', constant_values=0)
    l = np.load("%s/reference_lengths.npy" % path)
    return c, r, l

a_c = None
a_r = None
a_l = None

for path in  ['organism_1_data', 'organism_2_data', 'organism_3_data']:
    c, r, l = load(path)

    if a_r is None:
        a_c = c
        a_r = r
        a_l = l
    else:
        a_c = np.concatenate([a_c, c])
        a_r = np.concatenate([a_r, r])
        a_l = np.concatenate([a_l, l])

np.save("all/chunks.npy", a_c)
np.save("all/references.npy", a_r)
np.save("all/reference_lengths.npy", a_l)
```

@mattdmem does that make sense and answer your question?
