### ISSUE TITLE
Procedures for generating training file

### ISSUE THREAD

**Issue by cathoderaymission** [nanoporetech/bonito#8]
Can you please post documentation on generating the training data (eg: bonito.hdf5)? 

Thanks!

**Comment by iiSeymour** [comment]
Hello @cathoderaymission 

The hdf5 file was prepared with this [script]( https://github.com/nanoporetech/taiyaki/blob/master/bin/prepare_mapped_reads.py) and there is a discussion on this here #4. This is an active area of research at the moment and will be the focus in Jan.

HTH

Chris.

**Comment by cathoderaymission** [comment]
Thanks for that!

Is the original fast5 data available which generated this training set? It seems it has most of the same reads when compared to the Taiyaki data generation [walk through](https://github.com/nanoporetech/taiyaki/blob/master/docs/walkthrough.rst) however there's about 17k additional samples. I'd like to use the same training data.

**Comment by iiSeymour** [comment]
Hi @cathoderaymission 

We haven't made the original reads available but the training file available here is the Taiyaki format so you can use it to train both.

Chris.
