### ISSUE TITLE
Missing `crf-beam` dependency for aarch64 (Jetson Nano/Jetson Xavier NX)

### ISSUE THREAD

**Issue by pgrzesik** [nanoporetech/bonito#80]
Hello,

for starters, I wanted to thank you for open-sourcing Bonito basecaller :bow:. I'm currently trying to evaulate/run it on NVIDIA's Jetson-family devices (Nano/Xavier NX), however, one of the dependencies, `crf-beam` is not available for that architecture (in pypi there are only wheels built for x86). Would it be possible to either publish `aarch64` wheels for that dependency to pypi or, even better, publish `sdist` version and/or release the source code of that dependency on Github? 

Thanks in advance :bow:

**Comment by iiSeymour** [comment]
Thanks @pgrzesik

The `crf-beam` package needs a little more work before we can consider open sourcing it but I can get an `aarch64` wheel pushed for you - what version of Python are you targeting?

**Comment by pgrzesik** [comment]
@iiSeymour Thank you for lightning-fast response. I'm currently working with Python 3.6.x but anything equal to or above 3.6 would be fine. :bow:

**Comment by iiSeymour** [comment]
Here's a wheel for py3.6 linux_aarch64 - [crf_beam-0.0.1a0-cp36-cp36m-linux_aarch64.whl.zip](https://github.com/nanoporetech/bonito/files/5647203/crf_beam-0.0.1a0-cp36-cp36m-linux_aarch64.whl.zip)

**Comment by pgrzesik** [comment]
Thank you @iiSeymour - worked like a charm :bow:
