### ISSUE TITLE
More unclassified reads in demultiplexing.

### ISSUE THREAD

**Issue by rajwanir** [nanoporetech/bonito#81]
Hello,

I am trying to basecall some multiplexed r9.4 flongle runs with bonito standard model (dna_r9.4.1), however, I see a greater number unclassified reads upon demultiplexing with qcat.

**Bonito + qcat:**

Adapters detected in 47391 of 77425 reads
  NBD103/NBD104  47391: |         ############ |  61.21 %
           none  27814           : |              ####### |  35.92 %

**Guppy + qcat**

Adapters detected in 66724 of 77425 reads
  NBD103/NBD104  66724: |    ################# |  86.18 %
           none  10621           : |                   ## |  13.72 %

The issue seems somewhat related to the one described [here](https://github.com/nanoporetech/bonito/issues/26 ) but I am using standard model. Could you please suggest on how to resolve this?

Thank you.

**Comment by iiSeymour** [comment]
Hey @rajwanir 

This is most likely a result of how the training set is put together with `bonito basecaller --save-ctc ...`. Each training example has to pass a coverage threshold of 90% but thinking about it this is probably too low. I will have to retrain some models to verify this and get back to you.

**Comment by rajwanir** [comment]
Thanks @iiSeymour for your prompt response.

**Comment by iiSeymour** [comment]
Demultiplexing performance should be on par with guppy in [v0.3.6](https://github.com/nanoporetech/bonito/releases/tag/v0.3.6).
