### ISSUE TITLE
bonito performance

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/bonito#82]
Hi, 

I am recalling with bonito 0.3.2 but it runs with about 1.5 reads/s. Any suggestions how i might speed up recalling? 

Running on Nvidia Quadro RTX 8000

I saw @kishwarshafin reporting a similar problem. 

Logs from two jobs running for 3 days now: 
```
==> logs/bonito-3211570594_4.out <==
gn-3
Thu Dec  3 22:56:21 CET 2020
fast5_pass 20200702_0852_1-E9-H9_PAF14553_ce6f8d61_fast5_pass
bonito 0.3.2
> loading model
> calling: 287240 reads [83:36:02,  1.40 reads/s]

==> logs/bonito-3211570594_6.out <==
gn-3
Thu Dec  3 22:56:21 CET 2020
fast5_pass 20200702_1519_2-E1-H1_PAF06148_1fab50a2_fast5_pass
bonito 0.3.2
> loading model
> calling: 275868 reads [83:35:53,  1.80s/ reads](base) 

```

**Comment by iiSeymour** [comment]
Hey @MichelMoser 

It's hard to make a judgment on performance in reads per seconds - when basecalling is completed bonito will report the performance `samples per second 1.5E+06 `. Can you do a smaller scale test to find the performance in samples per second so we can judge if it looks about right?

**Comment by MichelMoser** [comment]
There are already some finished runs, which i can send you: 

```
fast5_pass 20200703_0925_1-E9-H9_PAF14553_f880ea80_fast5_pass
bonito 0.3.2
> loading model
> completed reads: 183199
> duration: 2 days, 5:59:36
> samples per second 3.0E+05
> done
Sun Dec  6 15:45:46 CET 2020
runtime 194403
```

and 

````
fast5_pass 20200703_1842_1-E9-H9_PAF14553_2e17f1d1_fast5_pass
bonito 0.3.2
> loading model
> completed reads: 140992
> duration: 1 day, 18:10:09
> samples per second 3.0E+05
> done
Sun Dec  6 15:26:59 CET 2020
runtime 151829
```

**Comment by MichelMoser** [comment]
GPU usage of an ongoing run is at 33 %.  

```
Mon Dec  7 11:24:18 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     On   | 00000000:01:00.0 Off |                  Off |
| 33%   28C    P8    12W / 260W |      0MiB / 48601MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 8000     On   | 00000000:81:00.0 Off |                  Off |
| 33%   50C    P2   115W / 260W |   8380MiB / 48601MiB |     32%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Quadro RTX 8000     On   | 00000000:A1:00.0 Off |                  Off |
| 33%   26C    P8     4W / 260W |      0MiB / 48601MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

 

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A      4178      C   ...envs/bonito/bin/python3.8     8365MiB |
+-----------------------------------------------------------------------------+
```

**Comment by iiSeymour** [comment]
Okay, that is quite a bit lower than the expected performance.

cc @vellamike

**Comment by MichelMoser** [comment]
Thank you. Let me know if you need other data.

**Comment by iiSeymour** [comment]
On a node with a Quadro RTX 8000 can you check that bonito is running using half precision - 
 
```bash
$ python3 
>>> from bonito.util import half_supported
>>> half_supported()
True
```

**Comment by MichelMoser** [comment]
Looks all fine. 

```
(bonito) [michelmo@gn-2 ~]$ python3
Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 19:31:52)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bonito.util import half_supported
>>> half_supported()
True
```

**Comment by jgaspard** [comment]
@MichelMoser  do you know how to use nsight systems to generate a profile of the GPU activity? I would appreciate if you could share a qdrep file with me so I can look into this. Let me know if you need support in getting this profile.

**Comment by vellamike** [comment]
@MichelMoser do you know how to use [Nsight Systems](https://developer.nvidia.com/nsight-systems) to profile GPU activity? Could you share a QDREP file with me? Let me know if you need support.

**Comment by mawa86** [comment]
I too have bonito running at ca. 40 reads/s, using only <30% of the GPU  capacity (3.1/11 GB). 
Was there any further indication here?

**Comment by vellamike** [comment]
@mawa86 

1. Do you know how to use Nsight Systems to profile GPU activity? Could you share a QDREP file with me? This will help diagnose why your GPU is running at low utilisation.
2. What is your CPU model and CPU utilisation during the run? 
3. Is your data stored locally (on the same machine as the GPU) or networked?

**Comment by mawa86** [comment]
@vellamike 
1. Haven't done it before but I can check, seems pretty straightforward from the documentation page. Which command switch (profile?) and which options would you need to make an assessment? GPU is a GeForce 2080Ti by the way.
2. CPU is AMD Ryzen 9 3900X (3.8/4.6 GHz, 12/24 cores), utilisation under run is: 
![Picture1](https://user-images.githubusercontent.com/86239377/123629067-1cdb1f00-d814-11eb-910c-685ea86ae8df.png)

3. data is stored locally, yes.
Thank you for your help!

**Comment by vellamike** [comment]
@mawa86  you can generate a QDREP file from a profile like this:

`nsys profile <CMD> <ARGS> -o  outfile.qdrep`

you can load the qdrep file on nsight systems and view it if you're interested, if you share it with me I'll be able to diagnose why your performance is poor.

Your CPU load average seems fine and if the data is stored locally IO shouldn't be an issue.

**Comment by iiSeymour** [comment]
@mawa86 do you have the reported samples/s from the end of the calling? This is a stable metric of performance, unlike read/s which is variable _(as it depends on the read lengths)_.

**Comment by iiSeymour** [comment]
The performance of basecalling is much improved in the latest release (v0.5.0).
