### ISSUE TITLE
Non-random distribution of errors from bonito 0.3.1 data

### ISSUE THREAD

**Issue by danrdanny** [nanoporetech/bonito#85]
Was just looking at some adaptive sampling data from a 9.4.1 pore that I basecalled with bonito 0.3.1 (aligned to hg38 with minimap2) and noticed that the errors appear non-randomly distributed. The error seems lower over the SINE/Alu elements and can be seen in this ~3kb view of chr6:51,993,375-51,996,386.

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/3186059/101447180-8bd54280-38d9-11eb-8531-6fff4e89a906.png">

Similar result nearby (chr6:51,984,029-51,987,040):

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/3186059/101447357-ecfd1600-38d9-11eb-82c9-f42c5df3d410.png">

I never saw this with guppy or albacore. Is this expected?

Thanks.

**Comment by iiSeymour** [comment]
Hey @danrdanny 

Thanks for reporting - we will need some time to investigate this in detail.

**Comment by iiSeymour** [comment]
So the effect can be seen with guppy to a lesser extent so I don't think it's totally surprising given the improvement in quality in the latest bonito version.

![Screenshot 2020-12-09 at 18 28 27](https://user-images.githubusercontent.com/4310904/101785433-a7686500-3af4-11eb-9b87-285957464fba.png)
![Screenshot 2020-12-09 at 18 26 28](https://user-images.githubusercontent.com/4310904/101785444-aafbec00-3af4-11eb-8f21-ad8420d2104c.png)
![Screenshot 2020-12-09 at 18 28 27](https://user-images.githubusercontent.com/4310904/101785450-ad5e4600-3af4-11eb-9653-94c68eba2b99.png)

This is certainly something to consider however w.r.t training set composition which we are currently evaluating.

**Comment by danrdanny** [comment]
Interesting, I had never noticed that before. Thanks for looking into it.
