### ISSUE TITLE
training set for included models

### ISSUE THREAD

**Issue by biolene** [nanoporetech/bonito#89]
I am just wondering about the training data set that was used for the models (i.e. dna_r9.4.1). 
Is this the same as what is used for the Guppy model with the same name?

**Comment by iiSeymour** [comment]
Yes for the first 2 released models, no for V0.3.X where we have increased the training set size.

**Comment by biolene** [comment]
okay, thanks for the fast follow-up. Looking forward to further developments with Bonito!

**Comment by protein2019** [comment]
Hi, so I guess dna_r9.4.1 downloaded now is still training set for V0.1 and V0.2. Could you please provide the training set for V0.3.X bonito model?
