### ISSUE TITLE
Low evaluation accuracy for r10.3 model

### ISSUE THREAD

**Issue by dkurt** [nanoporetech/bonito#90]
```
$ bonito evaluate dna_r10.3@v3

* loading data
* loading model 0
* calling
* mean      13.91%
* median    0.00%
* time      2.26
* samples/s 1.59E+06
```
r9.4.1 model evaluated fine.

**Comment by iiSeymour** [comment]
Hey @dkurt 

r9.4.1 is the reference to nanopore chemistry *(r = reader)*. The signal produced by r10.3 is very difference from r9.4.1 so you should expect poor performance when evaluating a r10.3 model on r9.4.1 data.

HTH.

**Comment by dkurt** [comment]
@iiSeymour, got it, thanks for clarification! Will focus on `bonito basecaller`.

**Comment by iiSeymour** [comment]
👍 from a software point of view, everything is the same so it's sufficient to stick with r9.4.1.
