### ISSUE TITLE
bonito basecaller runs out of memory

### ISSUE THREAD

**Issue by biolene** [nanoporetech/bonito#93]
Hi, 

I've tried to run bonito with the following command:

bonito basecaller dna_r9.4.1 --recursive --fastq --device cuda:0 /fast5_folder > bonito_basecalled.fastq

fter a few minutes it crashes with the following error:

RuntimeError: CUDA out of memory. Tried to allocate 450.00 MiB (GPU 0; 5.79 GiB total capacity; 3.50 GiB already allocated; 305.12 MiB free; 4.69 GiB reserved in total by PyTorch)

Also, as a side remark: after this happens, the process does not terminate automatically and continues claiming the memory, so you have to kill it explicitly

Is there a minimal memory requirement for Bonito? I realize that 6 GB is not particularly much, but for Guppy it works fine.
Thanks in advance for your feedback!

**Comment by iiSeymour** [comment]
Hey @biolene 

With the default parameters bonito needs around ~8GB of GPU memory - to reduce this you can tune down the batch size [here](https://github.com/nanoporetech/bonito/blob/master/bonito/crf/basecall.py#L85) to 24.

**Comment by iiSeymour** [comment]
The GPU memory usage can now be set by adjusting the batchsize like so - `bonito basecaller --batchsize 256 ...`
