### ISSUE TITLE
PyTorch dependency (version <=1.5, >=1.1.0)

### ISSUE THREAD

**Issue by MaximilianStammnitz** [nanoporetech/bonito#94]
Hi,

Currently struggling to install Bonito via pip due to what seems like a strict version dependency:

ERROR: Could not find a version that satisfies the requirement torch<=1.5,>=1.1.0 (from ont-bonito==0.3.2) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1)

Without having had a deeper look into the package, I guess torch==1.7.1 would not be expected to raise any issues down the line? As an alternative to relaxing this requirement, would you - for now - recommend users to install PyTorch 1.5.0 [from source](https://github.com/pytorch/pytorch/tree/v1.5.0)?

Cheers,
Max

**Comment by iiSeymour** [comment]
My guess is you are using Python 3.9 which PyTorch <=1.5 doesn't support _(as it wasn't released at the time)_. 

The reason I've stuck with torch<=1.5 is to keep compatibility with Python 3.5 and Cuda 10.X - I've done some limited testing with torch==1.7 and didn't have any issues.

**Comment by MaximilianStammnitz** [comment]
Ah, thanks @iiSeymour! To keep things simple and consistent, I'll just stick to Python 3.5 then. Maybe worth adding a note to the README about this.

**Comment by iiSeymour** [comment]
Python 3.5, 3.6, 3.7, 3.8 are fine - just no support for 3.9 yet, I'll look to get this added to the README, thanks.
